This algorithm traverses a source model and checks that each use
refers to definition.
It also constructs the use-def map.

== Input

. A list _tul_ of translation units.

. An
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[analysis
data structure] _a_
representing the results of analysis so far.

== Output

. An analysis data structure _a_ with updated use-def map.

== Procedure

. *Translation unit lists:* Visit each translation unit _tu_ in _tul_ in order.

. *Translation units:* Visit a translation unit _tu_ by visiting its members _tum_.

. *Translation unit members:* Visit a translation unit member _tum_ as follows:

.. *Module definitions:* If _tum_ is a module definition _d_ with name _n_, then

... Look up the
https://github.com/nasa/fpp/wiki/Analysis#data-structures[module
symbol] _sym_ associated with the unqualified name _n_ as described in
*Expressions* below.

... Look up the mapping from _sym_ to _s_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[symbol-scope
map] of _a_.
If no such mapping exists, then throw an internal error.

... Push _s_ onto the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

... Visit each translation unit member of _d_.

... Pop _s_ off the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

.. *Template expansion specifiers*: If _tum_ is a template expansion specifier _tem_, then

... Look up the template expansion _e_ with definition scope _sd_,
parameter scope _sp_, and local scope map _lsm_ for _tem_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[template
expansion map] of _a_.

... Save the current https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested scope] _ss_ of _a_.

... Look up the template use _t_ found in _tem_ in the https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[use-def map] of _a_.

... Compute the nested scope _ts_ of _t_ using the https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[parent-symbol map].

... Replace the current https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested scope] of _a_ with _ts_.

... Push _sp_ onto the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

... Push _sd_ onto the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

... Visit all the expanded members of _tem_, looking up the scope of each
symbol in _lsm_ before the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[symbol-scope
map] of _a_.

... Restore the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_ with _ss_.

... Visit each argument of _tem_: a constant argument as an expression, a
type argument as a type name, and a port interface instance argument as a
component instance use.

.. *Enum definitions:* If _tum_ is an enum definition _d_ with name _n_, then

... Visit the type of _d_ if it is present.

... Construct the unique
https://github.com/nasa/fpp/wiki/Analysis#data-structures[enum
symbol] _sym_ corresponding to _d_.

... Look up the mapping from _sym_ to _s_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[symbol-scope
map] of _a_.
If no such mapping exists, then throw an internal error.

... Push _s_ onto the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

... Visit each enumerated constant definition of _d_.

... Pop _s_ off the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

.. *Component definitions:* If _tum_ is a component definition _d_
with name _n_, then

... Construct the unique
https://github.com/nasa/fpp/wiki/Analysis#data-structures[component
symbol] _sym_ corresponding to _d_.

... Look up the mapping from _sym_ to _s_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[symbol-scope
map] of _a_.
If no such mapping exists, then throw an internal error.

... Push _s_ onto the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

... Visit each member of _d_.

... Pop _s_ off the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_.

.. *Interface definitions:*
If _tum_ is a component instance definition, then
visit all the expressions, and port uses
uses appearing in _tum_.

.. *Component instance definitions:*
If _tum_ is a component instance definition, then
visit all the type names, expressions, and component
uses appearing in _tum_.

.. *Topology definitions:* If _tum_ is a topology definition, then

... Visit all the implied uses of _tum_.

... Visit all the type names, expressions, and component instance
uses appearing in _tum_.

.. *Other definitions:*
If _tum_ is an abstract type, array,
constant, or port definition, then visit all the
type names and expressions appearing in _tum_.

. *Enumerated constant definitions:* Visit an enumerated constant definition
_d_ as follows:

.. If _d_ contains an expression _e_, then visit _e_.

. *Component members:* Visit a component member _cm_ as follows:

.. If _cm_ corresponds to a translation member _tum_, then visit _cm_
in the same manner as _tum_.

.. Otherwise visit all the expressions, types, port uses, implied uses,
and state machine uses appearing in _cm_.

. *Expressions:* Visit an expression _e_ as follows:

.. *Relative unqualified names:* If _e_ is a relative unqualified name _n_,
then

... Look up the mapping from _n_ to _sym_ in the innermost
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_ in the value name group.
If no such mapping exists, then throw a semantic error.

... Record the mapping from _e_ to _sym_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[use-def map]
of _a_.

.. *Absolute unqualified names:* Otherwise if _e_ is an absolute unqualified
name `.`_n_, then

... Look up the mapping from _n_ to _sym_ in the outermost (global) scope of
the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[nested
scope] of _a_ in the value name group.
If no such mapping exists, then throw a semantic error.

... Record the mapping from _e_ to _sym_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[use-def map]
of _a_.

.. *Dot expressions:* Otherwise if _e_ is a dot expression _e'.n_, then

... Visit _e'_.

... Look up the mapping of _e'_ to _sym'_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[use-def map]

.... If _sym'_ does not exist, or _sym'_ exists and is a constant symbol
or a
https://github.com/nasa/fpp/wiki/Enter-Template-Symbols#bound-parameter-symbols[constant
parameter symbol], this dot expression selects
a member of the constant and therefore does not introduce an additional use. Exit this visitor.

.... Otherwise if _sym'_ exists, get the mapping from sym' to s in the symbol-scope map of a.
If no such mapping exists, then throw an internal error.

.... Look up the mapping from _n_ to _sym_ in _s_.
If no such mapping exists, then throw a semantic error.

.... Record the mapping from _e_ to _sym_ in the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[use-def map]
of _a_.

.. *Other expressions:* Otherwise visit each expression and type appearing in
_e_.

. *Type names:* Visit a type name _tn_ as follows:

.. *Relative unqualified names:* Use the same algorithm as for relative
unqualified name expressions, but use the type name group instead of the
value name group.

.. *Absolute unqualified names:* Use the same algorithm as for absolute
unqualified name expressions, but use the type name group instead of the
value name group.

.. *Qualified names:* Use the same algorithm as for dot expressions,
but use the type name group instead of the value name group.

.. *Other types*: Nothing to do.

. *Port uses:* A port use _pu_ is a qualified or unqualified name.
Visit _pu_ in the same way as a qualified or unqualified type name,
but use the port name group instead of the type name group.

. *Component instance uses:* A component instance use _ciu_ is
a qualified or unqualified name.
Visit _ciu_ in the same way as for a port use, but use
the component instance name group instead of the port
name group.

. *Implied uses:* An implied use _iu_ is a qualified or
unqualified name provided by the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[implied
use map].

Visit _iu_ like a constant expression, a type use, or a port use.
Report an error if _iu_ resolves to a
https://github.com/nasa/fpp/wiki/Enter-Template-Symbols#bound-parameter-symbols[bound
parameter symbol], or if the qualified name of the symbol it resolves to
is not the name of _iu_.
