For implementation, see
https://github.com/nasa/fpp/blob/main/compiler/lib/src/main/scala/analysis/CheckSemantics/ExpandSyntaxAndEnterSymbols.scala[`ExpandSyntaxAndEnterSymbols.scala`].

This algorithm enters the symbols of a source model and expands all
syntax in the source model.
In general, entering symbols requires expanding templates and vice versa.

== Input

. An https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[analysis
data structure] _a_.

. A list _tul_ of translation units.

== Output

. If the algorithm succeeds, then

.. An updated analysis data structure _a_ with symbols entered, the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[use-def map]
filled in for template names, and the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[template
expansion map] filled in.

.. An updated list _tul_ of translation units with all syntax expanded.

. Otherwise an error and no output.

== Procedure

. Recursively resolve include specifiers. Check for include cycles. Upon
  detecting an include cycle, halt with an error message.

. https://github.com/nasa/fpp/wiki/Add-State-Enums[Add state enums] for
_tul_, yielding a new list of translation units _tul_ in which each state
machine definition that has a body has a state enum definition.

. https://github.com/nasa/fpp/wiki/Enter-Symbols[Enter symbols] for _a_ and _tul_.

. https://github.com/nasa/fpp/wiki/Check-Template-Uses[Check template uses] for _a_ and _tul_.

. https://github.com/nasa/fpp/wiki/Expand-Templates[Expand templates] for _a_ and _tul_,
yielding a new list of translation units _tul_ in which each template
expansion specifier carries the members that it expands.

. https://github.com/nasa/fpp/wiki/Enter-Template-Expansion-Symbols[Enter 
  template expansion symbols] for _a_ and _tul_.
