For implementation, see
https://github.com/nasa/fpp/blob/main/compiler/lib/src/main/scala/analysis/CheckSemantics/ResolveTemplates.scala[`ResolveTemplates.scala`].

This algorithm enters the symbols of a source model and expands its
template expansion specifiers.
Each tool runs it on the translation units produced by resolving include
specifiers, and then runs
https://github.com/nasa/fpp/wiki/Checking-Semantics[semantic checking] on
the result.

== Input

. An https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[analysis
data structure] _a_.

. A list _tul_ of translation units.

== Output

. An updated analysis data structure _a_ with symbols entered, the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[use-def map]
filled in for template names, and the
https://github.com/nasa/fpp/wiki/Analysis-Data-Structure[template
expansion map] filled in.

. A list _tul'_ of translation units with state enums added and templates
expanded.

. Otherwise an error and no output.

== Procedure

. https://github.com/nasa/fpp/wiki/Add-State-Enums[Add state enums] for
_tul_, yielding a new list of translation units _tul_ in which each state
machine definition that has a body has a state enum definition.

. https://github.com/nasa/fpp/wiki/Enter-Symbols[Enter symbols] for _a_ and _tul_.

. https://github.com/nasa/fpp/wiki/Check-Template-Uses[Check template uses] for _a_ and _tul_.

. https://github.com/nasa/fpp/wiki/Expand-Templates[Expand templates] for _a_ and _tul_,
yielding a new list of translation units _tul_ in which each template
expansion specifier carries the members that it expands.

. https://github.com/nasa/fpp/wiki/Enter-Template-Symbols[Enter template symbols] for _a_ and _tul_.
