#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_syntax=../../../bin/fpp-syntax

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_syntax $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

update "" parse-error
update "" syntax
update -a syntax syntax-ast
update -i cycle-1 include-cycle-1
update -i cycle-2 include-cycle-2
update -a empty
update -i include-parse-error
update -ia include-component
update -ia include-constant-1 include-constant-1
update -ia include-module
update -ia subdir/include-parent-dir
update -ia include-subdir
update -ia include-topology
update -ia syntax syntax-include-ast
