#!/bin/sh

# ----------------------------------------------------------------------
# Compile ref files, to check them for XML validity
# ----------------------------------------------------------------------

fprime_codegen=../../../scripts/fprime-codegen

for file in `find . -name '*Ai.ref.xml'`
do
  base=`basename $file .ref.xml`
  src_file=$base.xml
  cp $file $src_file
  echo "compiling $src_file"
  $fprime_codegen $src_file
done
