#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_to_xml=../../../bin/fpp-to-xml

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_to_xml $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

. ./tests.sh

# Default update ref
for t in $tests
do
  echo "
$t()
{
  update '' $t
}"
done > default-update-ref.sh
. ./default-update-ref.sh

struct_ok()
{
  update "-n struct_ok.names.txt -p $PWD" struct_ok
  mv struct_ok.names.txt struct_ok.names.ref.txt
  mv StructOK1SerializableAi.xml StructOK1SerializableAi.ref.xml 
  mv StructOK2SerializableAi.xml StructOK2SerializableAi.ref.xml 
}

for t in $tests
do
  echo "updating ref output for $t"
  $t
done
