#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_to_xml=../../../bin/fpp-to-xml

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_to_xml $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

. ./tests.sh

# Default update ref
for t in $tests
do
  echo "
$t()
{
  update '-p '$PWD $t
}"
done > default-update-ref.sh
. ./default-update-ref.sh

array_enum()
{
  update "-p $PWD" array_enum
  mv ArrayEnumE1EnumAi.xml ArrayEnumE1EnumAi.ref.xml
  mv ArrayEnumE2EnumAi.xml ArrayEnumE2EnumAi.ref.xml
  mv ArrayEnum1ArrayAi.xml ArrayEnum1ArrayAi.ref.xml
  mv ArrayEnum2ArrayAi.xml ArrayEnum2ArrayAi.ref.xml
}

array_ok()
{
  update "-p $PWD" array_ok
  mv ArrayOK1ArrayAi.xml ArrayOK1ArrayAi.ref.xml
  mv ArrayOK2ArrayAi.xml ArrayOK2ArrayAi.ref.xml
  mv ArrayOK3ArrayAi.xml ArrayOK3ArrayAi.ref.xml
  mv ArrayOK4ArrayAi.xml ArrayOK4ArrayAi.ref.xml
  mv ArrayOK5ArrayAi.xml ArrayOK5ArrayAi.ref.xml
}

enum_explicit()
{
  update '' enum_explicit
  mv ExplicitEnumAi.xml ExplicitEnumAi.ref.xml 
}

enum_implicit()
{
  update '' enum_implicit
  mv ImplicitEnumAi.xml ImplicitEnumAi.ref.xml 
}

struct_abs_type()
{
  update "-p $PWD" struct_abs_type
  mv StructAbsTypeSerializableAi.xml StructAbsTypeSerializableAi.ref.xml 
}

struct_enum_member()
{
  update "-i enum_explicit.fpp -p $PWD" struct_enum_member
  mv StructEnumMemberSerializableAi.xml StructEnumMemberSerializableAi.ref.xml 
}

struct_ok()
{
  update "-n struct_ok.names.txt -p $PWD" struct_ok
  mv struct_ok.names.txt struct_ok.names.ref.txt
  mv StructOK1SerializableAi.xml StructOK1SerializableAi.ref.xml 
  mv StructOK2SerializableAi.xml StructOK2SerializableAi.ref.xml 
}

struct_format()
{
  update '' struct_format
  mv StructFormatSerializableAi.xml StructFormatSerializableAi.ref.xml 
}

struct_modules()
{
  update "-p $PWD" struct_modules
  mv StructModules1SerializableAi.xml StructModules1SerializableAi.ref.xml 
  mv StructModules2SerializableAi.xml StructModules2SerializableAi.ref.xml 
  mv StructModules3SerializableAi.xml StructModules3SerializableAi.ref.xml 
}

struct_output_dir()
{
  update '-d output_dir' output_dir/struct_output_dir
  mv output_dir/StructOutputDirSerializableAi.xml output_dir/StructOutputDirSerializableAi.ref.xml
}

struct_string()
{
  update '' struct_string
  mv StructStringSerializableAi.xml StructStringSerializableAi.ref.xml 
}

for t in $tests
do
  echo "updating ref output for $t"
  $t
done
