name: 'native-tools-setup'
description: 'Set Up GraalVM Native Image Tools'
inputs:
  binary-directory:
    required: true
  trace-directory:
    required: false
    default: ""
runs:
  using: "composite"
  steps:
  - name: "Setting up GraalVM/Java Environment"
    run: |
      echo "Run Native Image Build"
      if [ -d "${{ inputs.trace-directory }}" ]; then
        export CLASSPATH="`cd ${{ inputs.trace-directory }}/../..; pwd`:${CLASSPATH}"
      fi
      ${{ github.action_path }}/native-images ${{ inputs.binary-directory }}
    shell: bash