#!/bin/sh -e

fpp_to_cpp=../../../../../../bin/fpp-to-cpp
fprime_gcc=../../../../../../scripts/fprime-gcc

echo '  removing old files'
./clean

dir=`cd ../..; echo $PWD`

tops="
<NoInstances>
"

echo '  generating C++'
$fpp_to_cpp -p $dir -i ../../builtin.fpp ../../tlm_packets.fpp
for suffix in hpp cpp
do
  top_acs=`echo $tops | sed -e "s;<;../../;" -e "s;>;TopologyAc.ref.$suffix;"`
  for file in ../../*TlmPacketsAc.ref.$suffix $top_acs
  do
    base=`basename $file .ref.$suffix`
    cp $file $base.$suffix
  done
done

echo '  compiling C++'
top_cpps=`echo $tops | sed -e "s;<;;" -e "s;>;TopologyAc.cpp;"`
for file in *TlmPacketsAc.cpp $top_cpps
do
  echo "    compiling $file"
  $fprime_gcc -I.. -I../../../fprime -I../../../fprime/config -Wno-unused-parameter -c $file
done
