#!/bin/sh -e

echo '  removing old files'
./clean

dir=`cd ../..; echo $PWD`

echo '  generating XML'
fpp-to-xml -p $dir -i ../../builtin.fpp ../../commands.fpp
cp ../Fw/Cmd/*Ai.xml .

echo '  generating C++'
(cd ../Fw/Cmd; fprime-codegen CmdResponseEnumAi.xml > /dev/null)
for file in CComponent CmdPort CmdRegPort CmdResponsePort
do
  fprime-codegen $file'Ai.xml' > /dev/null
done
for suffix in hpp cpp
do
  cp ../../CommandsTopologyAc.ref.$suffix CommandsTopologyAc.$suffix
done

echo '  compiling C++'
fprime-gcc -I .. -c CommandsTopologyAc.cpp
