#!/bin/sh -e

cd ../..
. ./defs.sh
cd check-cpp-dir/Commands

echo '  removing old files'
./clean

echo '  generating C++'
(
  cd ../../commands;
  fpp_to_cpp=../../../../../bin/fpp-to-cpp
  $fpp_to_cpp -p $PWD -i $FPRIME_DEPS,../phases.fpp -d ../check-cpp-dir/Commands components.fpp topology.fpp
)

fprime_gcc=../../../../../../scripts/fprime-gcc
flags="-I.. -I../../../fprime -I../../../fprime/config -Wno-unused-parameter -c"
echo '  compiling C++'
for variable_flags in '' '-DFW_DIRECT_PORT_CALLS'
do
  echo "    variable_flags=$variable_flags"
  $fprime_gcc $variable_flags $flags CommandsTopologyAc.cpp
done
