// ======================================================================
// \title  OuterVectorAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Outer vector
// ======================================================================

#ifndef OuterVectorAc_HPP
#define OuterVectorAc_HPP

#include <initializer_list>

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"
#include "Fw/Types/SuccessEnumAc.hpp"
#include "InnerVectorAc.hpp"
#include "config/FwSizeStoreTypeAliasAc.hpp"

//! A vector of vectors with a default value
class Outer :
  public Fw::Serializable
{

  public:

    // ----------------------------------------------------------------------
    // Types
    // ----------------------------------------------------------------------

    //! The element type
    using ElementType = Inner;

  public:

    // ----------------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------------

    enum {
      //! The maximum size of the vector
      CAPACITY = 3,
      //! The serialized size of each element
      ELEMENT_SERIALIZED_SIZE = Inner::SERIALIZED_SIZE,
      //! The serialized size of the length prefix
      SIZE_PREFIX_SERIALIZED_SIZE = sizeof(FwSizeStoreType),
      //! The maximum size of the serial representation
      SERIALIZED_SIZE = SIZE_PREFIX_SERIALIZED_SIZE + CAPACITY * ELEMENT_SERIALIZED_SIZE
    };

  public:

    // ----------------------------------------------------------------------
    // Constructors
    // ----------------------------------------------------------------------

    //! Constructor (default value)
    Outer();

    //! Constructor (initializer list)
    Outer(
        const std::initializer_list<ElementType>& il //!< The initializer list
    );

    //! Copy constructor
    Outer(
        const Outer& obj //!< The source object
    );

  public:

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    //! Subscript operator
    ElementType& operator[](
        const FwSizeType i //!< The subscript index
    );

    //! Const subscript operator
    const ElementType& operator[](
        const FwSizeType i //!< The subscript index
    ) const;

    //! Copy assignment operator (object)
    Outer& operator=(
        const Outer& obj //!< The source object
    );

    //! Copy assignment operator (initializer list)
    Outer& operator=(
        const std::initializer_list<ElementType>& il //!< The initializer list
    );

    //! Equality operator
    bool operator==(
        const Outer& obj //!< The other object
    ) const;

    //! Inequality operator
    bool operator!=(
        const Outer& obj //!< The other object
    ) const;

#ifdef BUILD_UT

    //! Ostream operator
    friend std::ostream& operator<<(
        std::ostream& os, //!< The ostream
        const Outer& obj //!< The object
    );

#endif

  public:

    // ----------------------------------------------------------------------
    // Public member functions
    // ----------------------------------------------------------------------

    //! Get the current length of the vector
    FwSizeType getLength() const;

    //! Set the current length of the vector
    void setLength(
        const FwSizeType len //!< The length
    );

    //! Push an element onto the end of the vector
    Fw::Success push(
        const ElementType& e //!< The element to push
    );

    //! Pop the last element off the vector
    Fw::Success pop(
        ElementType& e //!< The popped element
    );

    //! Serialization
    Fw::SerializeStatus serializeTo(
        Fw::SerialBufferBase& buffer, //!< The serial buffer
        Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
    ) const;

    //! Deserialization
    Fw::SerializeStatus deserializeFrom(
        Fw::SerialBufferBase& buffer, //!< The serial buffer
        Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
    );

    //! Get the dynamic serialized size of the vector
    FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

    //! Convert vector to string
    void toString(
        Fw::StringBase& sb //!< The StringBase object to hold the result
    ) const;

#endif

  private:

    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! The vector elements
    ElementType elements[CAPACITY];

    //! The current length of the vector
    FwSizeType length;

};

#endif
