== Detailed Description

This section provides a detailed description of the tnet language. We
fully describe each syntactic element of the language. We also describe
semantics as appropriate. Additional general semantic rules are
described in subsequent sections.

**Language Elements:** We divide the language syntax into the following elements:

* <<Detailed-Description_Lexical-Elements,Lexical Elements>>:
The lexical elements of a tnet program.

* <<Detailed-Description_Identifiers,Identifiers>>:
The names of the definitions and parameters
that are defined and used in a tnet program.

* <<Detailed-Description_Types,Types>>:
The types of the expressions and values in a tnet program.

* <<Detailed-Description_Expressions,Expressions>>:
Syntactic units that have types and that evaluate to values.

* <<Detailed-Description_Definitions,Definitions>>:
Definitions appearing in a tnet program. Module definitions
themselves contain definitions, including definitions of other modules.
Enum definitions contain definitions of enumerated constants.

* <<Detailed-Description_Element-Sequences,Element
Sequences>>: Sequences of elements, for example, all the definitions
appearing in a module.

* <<Detailed-Description_Comments-and-Annotations,Comments
and Annotations>>: Program text that is not parsed and is there solely
for human users to read.

* <<Detailed-Description_Translation-Units-and-Programs,Translation
Units and Programs>>: Groupings of definitions that can be checked for
semantic correctness and translated.

**Syntax Notation:** We use the following notation to describe the syntax of language
elements:

* `fixed-width font` denotes literal program text.

* _italics_ denote grammar nonterminals.

* Italicized brackets _[ ]_ enclose optional elements.

