== Definitions and Uses

=== Uses

A *use* is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> appearing in an
<<Detailed-Description_Expressions,expression>>
or a
<<Detailed-Description_Types,type>>
that refers to a
<<Detailed-Description_Definitions,definition>>
according to the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,scoping rules for names>>.

Not all qualified identifiers are uses. For example, in line 2 of this
program

[source,tnet]
----
include::./src/Definitions_and_Uses/Uses_1.tnt[tag=visible]
----

`c1` is a use, but `c1.x` is not. `c1` refers to the definition of the
constant `c1`, while `c1.x` refers to an element of a structure value.

=== Use-Def Graph

The set of definitions and uses in a tnet program induces a directed
graph called the *use-def graph*. In this graph,

. The nodes are the definitions.

. There is an edge from each definition _d_ to the definitions 
stem:[d_1, ..., d_n] corresponding to the uses 
stem:[u_1, ..., u_n] appearing in _d_.

For example, in the code above, the use-def graph has two nodes `c1` and
`c2` and one edge `c2` stem:[rarr] `c1`.

In a legal tnet program, the use-def graph must be acyclic. For example,
this program is illegal:

[source,tnet]
----
include::./src/Definitions_and_Uses/Use_Def_Graph_1.tnt[tag=visible]
----

This program is also illegal:

[source,tnet]
----
include::./src/Definitions_and_Uses/Use_Def_Graph_2.tnt[tag=visible]
----

=== Order of Definitions and Uses

So long as the
<<Definitions-and-Uses_Use-Def-Graph,use-def graph>> is acyclic, there is no 
constraint either on the ordering of
definitions and uses within a
<<Detailed-Description_Translation-Units-and-Programs,translation unit>>, 
or on the distribution of definitions and uses among translation
units. For example, if the definition `constant c = 0` appears anywhere
in any translation unit of a program _P_, then the use of `c` as a
constant value of type U8 is legal anywhere in any translation unit of
_P_. In particular, this program is legal:

[source,tnet]
----
include::./src/Definitions_and_Uses/Order_of_Definitions_and_Uses_1.tnt[tag=visible]
----

The program consisting of two translation units

[source,tnet]
----
include::./src/Definitions_and_Uses/Order_of_Definitions_and_Uses_2.tnt[tag=visible]
----

and

[source,tnet]
----
include::./src/Definitions_and_Uses/Order_of_Definitions_and_Uses_3.tnt[tag=visible]
----

is also legal, and the order in which the units are presented to the
translator does not matter.
