= The F Prime Prime (FPP) Modeling Language
:toc: left
:toclevels: 3
:stem:

[[Introduction]]
== Introduction

This document describes **F Prime Prime**, also known as FPP or F Double Prime.
FPP is a modeling language for the 
https://github.com/nasa/fprime[F Prime flight software framework].

The goals of FPP are as follows:

* To provide a modeling language for F Prime that is simple, easy to use, and
well-tailored to the domain.

* To provide semantic checking and error reporting for F Prime models.

* To support code generation to the various formats that F Prime uses, e.g.,
C++, Python, XML.

[[Syntax-Notation]]
== Syntax Notation

Throughout this document, we use the following notation to describe
language syntax:

* `fixed-width font` denotes literal program text.

* _italics_ denote grammar nonterminals.

* Italicized brackets _[ ]_ enclose optional elements.


[[Lexical-Elements]]
== Lexical Elements

Before parsing an FPP program, the compiler converts the source
text into a list of **tokens**.
This process is called **lexing**.

A token is one of the following:

* A <<Lexical-Elements_Reserved-Words,reserved word>>.

* A <<Lexical-Elements_Symbols,symbol>>.

* An <<Lexical-Elements_Identifiers,identifier>>.

* An <<Lexical-Elements_Integer-Literals,integer literal>>.

* A <<Lexical-Elements_Floating-Point-Literals,floating-point literal>>.

* A <<Lexical-Elements_Boolean-Literals,Boolean literal>>.

* A <<Lexical-Elements_Newlines,newline character>>.

* A line of an <<Comments-and-Annotations_Annotations,annotation>>
beginning with `@` or `@<`.

[[Lexical-Elements_Reserved-Words]]
=== Reserved Words

The following are reserved words in FPP.
They may not be used as identifiers.

----
F32
F64
I16
I32
I64
I8
U16
U32
U64
U8
array
boolean
component
enum
false
instance
namespace
port
string
struct
true
type
----

[[Lexical-Elements_Symbols]]
=== Symbols

The following sequences of characters are symbol tokens in FPP:

----
,
-
.
:
;
[
]
{
}
----

[[Lexical-Elements_Identifiers]]
=== Identifiers

An *identifier* is an unqualified name
consisting of one or more characters. The first character
must be a letter or an underscore. Characters after the first character
may be letters, digits, and underscores.

**Examples:**

----
Identifier
MultiPartIdentifier
_identifier_
identifier
identifier_
multiPartIdentifier
multi_part_identifier
----

[[Lexical-Elements_Integer-Literals]]
=== Integer Literals

An *integer literal expression* is one of the following:

* A sequence of decimal digits `0` through `9` denoting the decimal
representation of a nonnegative integer.

* `0x` or `0X` followed by a sequence of hexadecimal digits
`0` through `9`, `A` through `F`, or `a` through `f` denoting the hexadecimal 
representation of a nonnegative
integer.

**Examples:**

----
1234
0xABCD
----

[[Lexical-Elements_Floating-Point-Literals]]
=== Floating-Point Literals

A *floating-point literal expression* is a C-style representation of an
IEEE floating-point number.

**Examples:**

----
1e-10
0.001
3.14159
6.02E23
----

[[Lexical-Elements_Boolean-Literals]]
=== Boolean Literals

A *Boolean literal expression* is one of the values `true` and `false`.

[[Lexical-Elements_Newlines]]
=== Newlines

The newline character is a token. Sequences of one or more newlines separate 
the elements of <<Element-Sequences,element sequences>>.

[[Lexical-Elements_Comments]]
=== Comments

<<Comments-and-Annotations_Comments,Comments>>
are ignored during lexing.

[[Lexical-Elements_Whitespace-and-Non-Printing-Characters]]
=== Whitespace and Non-Printing Characters

Apart from <<Lexical-Elements_Newlines,newlines>>, the lexer treats whitespace 
as follows:

* Space characters are ignored, except to separate tokens.

* No other whitespace or non-printing characters are allowed
outside of a comment, annotation, or string.
In particular, the tab character may not appear
in an FPP program outside of a comment, annotation, or string.

[[Lexical-Elements_Line-Continuations]]
=== Line Continuations

The character `\`, when appearing before a newline, causes the newline to
be ignored. For example, this
```
constant a = \
  1
```
is equivalent to this:
```
constant a = 1 + 1
```

Note that the `\` character is required in this case.
For example, the following is not syntactically correct:
```
constant a = # Error
  1
```
The newline indicates the end of an element sequence, but
`constant a =` is not a valid element sequence.

The lexer ignores any space characters appearing between `\` and the next 
newline.
