= F Prime Prime (FPP)

This repository contains the code and documentation for F Prime Prime (FPP for 
short).
FPP is a modeling language for the
https://nasa.github.io/fprime/[F Prime flight software framework].

== Contents

`compiler`: The FPP analysis and translation tools.

`docs`: The FPP User's Guide and language specification.

`editors`: Syntax highlighting for code editors. Currently vim is supported.

== Building and Installing

=== Tools

See `compiler/README.adoc`.
To use or develop FPP in a standalone mode, you should install these tools.
To use FPP as part of F Prime development, you can install the F Prime tool set,
which includes FPP.
See the F Prime installation instructions
https://github.com/nasa/fprime/blob/master/docs/INSTALL.md[here].

=== Spec and User's Guide

See `docs/README.adoc`.
Build these documents from source only if you are developing them.
Otherwise, read the copies available on the 
https://github.com/fprime-community/fpp/wiki[wiki].

== Design and Implementation

See the
https://github.com/fprime-community/fpp/wiki[wiki].
