#!/bin/sh -e

cd `dirname $0`

fpp_to_cpp=../../../../../bin/fpp-to-cpp
echo "generating C++ files for harness"

state_machine=`dirname $PWD`
harness=$state_machine/harness
fpp_flags="-p $state_machine"
$fpp_to_cpp $fpp_flags harness.fpp
