#!/bin/sh -e

# ----------------------------------------------------------------------
# Compile ref FPP files, to check them for validity
# ----------------------------------------------------------------------

fpp_syntax=../../../bin/fpp-syntax

files=`find . -name '*.ref.txt' | egrep -v 'error|missing'`
for file in $files
do
  echo "checking $file"
  $fpp_syntax < $file
done
