== Analysis and Translation

=== Analysis

*Analysis* is the process of checking a source model.
It usually involves the following steps:

. Lexing and parsing to generate an abstract syntax tree (AST).

. If step (1) succeeded, semantic analysis of the AST.

=== Analysis Tools

An *analysis tool* is a tool that reads in and analyzes FPP
source files, but does not generate any code.
Source files for analysis are provided in one of two ways:

1. Via command-line arguments; or

2. On standard input, if there are no arguments.

For example, the command `analyze file1.fpp file2.fpp`
says to read in the translation units `file1.fpp` and `file2.fpp` and perform 
analysis on the model consisting of these two translation units.
The command `cat file1.fpp file2.fpp | analyze` is functionally equivalent.

=== Translation

*Translation* is the process of performing analysis and 
generating code.

Translation usually involves the following steps:

. <<Analysis-and-Translation_Analysis,Analysis>>.

. If step (1) succeeded, code generation.

FPP is intended to support a variety of translation
strategies. For example, we need to generate (1) C++ code for FSW and 
(2) XML, Python, or other code to export to ground tools.

=== Translation Tools

A *translation tool* is a tool that translates FPP source files.
A translation tool typically accepts the following two kinds of
input:

1. Source files to be translated.

2. Source files that are *imported* for their symbol definitions,
but are not translated.

For example, when translating a component _C_, a tool may read
in files containing the definitions of the ports used in _C_,
but not translate those files.

Source files for translation are provided as for 
<<Analysis-and-Translation_Analysis-Tools,analysis tools>>.
Imported source files are specified as arguments to a `-i` flag.

For example, the command `translate -i file1.fpp,file2.fpp file3.fpp`
says to import `file1.fpp` and `file2.fpp` and translate `file3.fpp`.
The command `translate -i file1.fpp,file2.fpp < file3.fpp` is functionally 
equivalent.
