== Definitions and Uses

=== Uses

A *use* is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>>
that refers to a
<<Definitions,definition>>
according to the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,scoping rules for names>>.

A use is a *qualifying use* if it qualifies another use. For example, in
the following code

* The expression `M.a` contains the expression `M`, which is a qualifying use 
of the module `M`. It qualifies the use `M.a`.
* The expression `M.a` is not a qualifying use.

[source,FPP]
----
module M {

  constant a = 0

  constant b = M.a

}
----

If a use _u_ is not a qualifying use, then we say it is a *non-qualifying use*.

=== Use-Def Graph

The set of definitions and 
<<Definitions-and-Uses_Uses,non-qualifying uses>>
in an FPP model induces a directed
graph called the *use-def graph*. In this graph,

. The nodes are the definitions.

. There is an edge from each definition _d_ to the definitions 
stem:[d_1, ..., d_n] corresponding to the non-qualifying uses 
stem:[u_1, ..., u_n] appearing in _d_.

For example, in the following code, the use-def graph has two nodes `a` and
`b` and one edge `b` stem:[rarr] `a`.

[source,FPP]
----
constant a = 0
constant b = a
----

In a legal FPP model, the use-def graph must be acyclic. For example,
this model is illegal:

[source,FPP]
----
constant a = b
constant b = a
----

This model is also illegal:

[source,FPP]
----
constant a = a
----

This model is legal:

[source,FPP]
----
module M {

  constant a = 0

  constant b = M.a

}
----

The use `M` appears inside the definition of `M`.
However, it is a qualifying use.

=== Order of Definitions and Uses

So long as the
<<Definitions-and-Uses_Use-Def-Graph,use-def graph>> is acyclic, there is no 
constraint either on the ordering of
definitions and uses within a
<<Translation-Units-and-Models,translation unit>>, 
or on the distribution of definitions and uses among translation
units. For example, if the definition `constant c = 0` appears anywhere
in any translation unit of a model _M_, then the use of `c` as a
constant value of type U8 is legal anywhere in any translation unit of
_M_. In particular, this model is legal:

[source,FPP]
----
constant b = a
constant a = 0
----

The model consisting of two translation units

[source,FPP]
----
constant b = a
----

and

[source,FPP]
----
constant a = 0
----

is also legal, and the order in which the units are presented to the
translator does not matter.
