== Expansion of Templates

Expansion of templates performs partial analysis
and syntactic expansion.
It produces a new model in which each
<<Specifiers_Template-Expansion-Specifiers,template
expansion specifier>> _S_ is transformed into an
*expanded template* stem:[E = S { X }], where _X_
is a copy of the syntax provided
by the template definition to which _S_ refers.
The expanded template _E_ is not expressible in the syntax
of the source language, but it is expressible in the internal
representation of the model.
The syntax _X_ behaves as if it were literally included in
the model at the point of _E_, except that there are
special rules for resolving 
<<Scoping-of-Names_Resolution-of-Identifiers_Inside-an-Expanded-Template,
resolving names>> that appear inside _E_.

=== Algorithm

Let _M_ be the model initially presented to the analyzer,
with <<Specifiers_Include-Specifiers,include specifiers>> resolved.
Construct the output model _M'_ as follows:

. Perform enough analysis on _M_ to match all template expansion
  specifiers with the template definitions to which they refer.
  The bodies of the template definitions are not analyzed in this step;
  see the section on
  <<Definitions_Module-Template-Definitions,module template definitions>>.

. For each template expansion specifier _S_ in _M_,
  do the following:

.. Let _T_ be the template definition referred to in _S_.

.. Let _X_ be a copy of the syntax specified in the body of _T_.

.. Replace _S_ with stem:[S { X }].

=== Termination

Expansion of templates always terminates, and one pass of step 2 of the
algorithm is sufficient. No
<<Definitions_Module-Template-Definitions,module template definition>>
may be the ancestor in the abstract syntax tree of another module
template definition or of a
<<Specifiers_Template-Expansion-Specifiers,template expansion specifier>>.

An implementation must report an error if a module template definition
or a template expansion specifier appears inside the body of a module
template definition.

=== Example

*Model _M_:*

[source,fpp]
----
module M {

  constant a = 0

  module template T(constant b: U32) {

    constant c = a + b

  }

}

module N {

  expand M.T(constant 1)

}
----

*Model _M'_:*

[source,fpp]
----
module M {

  constant a = 0

  module template T(constant b: U32) {

    constant c = a + b

  }

}

module N {

  # The expanded template is expand M.T(constant 1) { constant c = a + b }
  expand M.T(constant 1)

}
----

