== Formal Parameter Lists

A *formal parameter list* is an
<<Element-Sequences,element sequence>>
in which the elements are formal parameters,
and the terminating punctuation is a comma.

A *formal parameter* is a typed symbol to which a value becomes bound
at runtime.
Formal parameters appear, for example, in
<<Definitions_Port-Definitions,port definitions>>.

=== Syntax

Formal parameters have the following syntax:

_[_ `ref` _]_
<<Lexical-Elements_Identifiers,_identifier_>>
`:`
<<Type-Names,_type-name_>>
_[_ `size` <<Expressions,_expression_>> _]_

=== Semantics

If present, the keyword `ref` specifies that the value
bound to the formal parameter is to be passed by reference.

The identifier is the name of the formal parameter.
No two parameters in the same formal parameter list
may have the same name.

The type name specifies the type _T_ of the formal parameter _P_.

The optional expression following the keyword `size` is called the *size 
expression* of the formal parameter _P_.
The size expression is allowed only when _T_ is `string`.
If present, it specifies the maximum length of a string
that may be bound to _P_.
If it is not present, then the translator uses the maximum string length
specified for the `string` type.

=== Examples

[source,fpp]
----
a : U32
b : string size 100
ref c : Fw.Com
----
