== Instance Member Identifiers

A *instance member identifier* refers to the member of a <<Definitions_Component-Instance-Definitions,
component instance definition>> or <<Definitions_Topology-Definitions,topology definition>>.
There are two types of instance member identifiers: <<Instance-Member-Identifiers_Port-Instance-Identifiers,
port instance identifiers>> and <<Instance-Member-Identifiers_Telemetry-Channel-Identifiers,
telemetry channel identifiers>>.

=== Port Instance Identifiers

A port instance identifier identifies a port instance that
is part of a <<Ports_Port-Interfaces,port interface>> instance. Port instance
identifiers appear in <<Specifiers_Connection-Graph-Specifiers,
connection graph specifiers>>.

==== Syntax

<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
`.`
<<Lexical-Elements_Identifiers,_identifier_>>

==== Semantics

For each port instance identifier _Q_ `.` _P_:

. The qualified identifier _Q_ must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
an <<Ports_Port-Interface-Instances,interface instance _I_>>.

. _I_ must refer to a <<Ports_Port-Interfaces,port interface _I'_>>

. The identifier _P_ must refer to a <<Specifiers_Port-Instance-Specifiers,
port instance>> in _I'_.

==== Examples

[source,fpp]
----
a.b
A.b.c
----

In the first example, `a` names a topology, and `b` names an exported
port instance.
In the second example, `A.b` names a component instance, and `c` names a
port instance.

=== Telemetry Channel Identifiers

A *telemetry channel identifier* identifies a telemetry channel that is part of
a component instance.  Telemetry channel identifiers appear in
<<Specifiers_Telemetry-Packet-Set-Specifiers,telemetry packet set
specifiers>> and <<Specifiers_Telemetry-Packet-Specifiers,telemetry packet
specifiers>>.

==== Syntax

<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
`.`
<<Lexical-Elements_Identifiers,_identifier_>>

==== Semantics

For each telemetry channel identifier _Q_ `.` _T_:

. The qualified identifier _Q_ must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a component instance _I_.

. _I_ must refer to a <<Definitions_Component-Instance-Definitions,component
instance definition _I'_>>.

. _I'_ must refer to a <<Definitions_Component-Definitions,component
definition _C_>>.

. The identifier _T_
must refer to a
<<Specifiers_Telemetry-Channel-Specifiers,telemetry channel specifier>>
of _C_.

==== Examples

[source,fpp]
----
a.b
A.b.c
----

In the first example, `a` names a component instance, and `b` names a
telemetry channel.
In the second example, `A.b` names a component instance, and `c` names a
telemetry channel.
