== Instance Member Identifiers

A *instance member identifier* is a unit of syntax that refers to a member of a
<<Definitions_Component-Instance-Definitions,
component instance>> or a <<Definitions_Topology-Definitions,topology>>.
There are two kinds of instance member identifiers:
<<Instance-Member-Identifiers_Port-Instance-Identifiers,
port instance identifiers>> and
<<Instance-Member-Identifiers_Telemetry-Channel-Identifiers,
telemetry channel identifiers>>.

=== Port Instance Identifiers

A *port instance identifier* names a port instance that is part of a
component instance or a topology.
Port instance identifiers appear in <<Specifiers_Connection-Graph-Specifiers,
connection graph specifiers>>.

==== Syntax

<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
`.`
<<Lexical-Elements_Identifiers,_identifier_>>

==== Semantics

For each port instance identifier _Q_ `.` _P_:

. The qualified identifier _Q_ must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a <<Ports_Port-Interface-Instances,port interface instance>>
with associated port interface _I_.

.. If _Q_ refers to a component instance definition, then _Q_ `.` _P_ is called
   a *component instance port*.

.. If _Q_ refers to a topology definition, then _Q_ `.` _P_ is called
   a *topology port*.

. The identifier _P_ must name a <<Ports_Port-Instances,port instance>> 
  contained in _I_.

==== Example

[source,fpp]
----
passive component C {

  sync input port p: P

}

instance c: C base id 0x100

module M {

  topology T {

    instance c

    port p = c.p

  }

}
----

In this example,

* `c.p` names the port instance `p` of the component instance `a`.

* `M.T.p` names the port instance `p` of the topology `M.T`.

=== Telemetry Channel Identifiers

A *telemetry channel identifier* identifies a telemetry channel that is part of
a component instance.  Telemetry channel identifiers appear in
<<Specifiers_Telemetry-Packet-Set-Specifiers,telemetry packet set
specifiers>> and <<Specifiers_Telemetry-Packet-Specifiers,telemetry packet
specifiers>>.

==== Syntax

<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
`.`
<<Lexical-Elements_Identifiers,_identifier_>>

==== Semantics

For each telemetry channel identifier _Q_ `.` _T_:

. The qualified identifier _Q_ must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a component instance _I_.

. _I_ must refer to a <<Definitions_Component-Instance-Definitions,component
instance definition _I'_>>.

. _I'_ must refer to a <<Definitions_Component-Definitions,component
definition _C_>>.

. The identifier _T_
must refer to a
<<Specifiers_Telemetry-Channel-Specifiers,telemetry channel specifier>>
of _C_.

==== Example

[source,fpp]
----
passive component C {

  time get port timeGetOut

  telemetry T: U32

}

instance c: C base id 0x100
----

In this example, `c.T` names the telemetry channel `T` of component instance
`c`.
