== Interfaces

Interfaces in F Prime define a set of
<<Specifiers_Port-Instance-Specifiers,port
instances>>. Interfaces can be explicitely named
through a <<Definitions_Port-Interface-Definitions,
port interface definition>>.

=== Named Interfaces

A named interface is an interface associated
with an <<Definitions_Port-Interface-Definitions,
interface definition>>. Named interfaces can be used
in <<Template-Parameter-Lists,template parameter lists>>.

=== Anonymous Interfaces

There are definitions in FPP that will implicitly define an interface
so that instances of these definitions may be bound to an interface.
These implicitly defined interfaces are known as anonymous interfaces
as they do not have explicit names associated with them.

==== Anonymous Component Interfaces

A <<Definitions_Component-Definitions,component definition>>
will create a corresponding anonymous interface. This interface includes
the set of all <<Specifiers_Port-Instance-Specifiers,port instances>>
inside the component definition (either explicitely, or via an
<<Specifiers_Interface-Import-Specifiers,interface import>>).

==== Anonymous Topology Interfaces

A <<Definitions_Topology-Definitions,topology definition>>
will create a corresponding anonymous interface. This interface includes
the set of all <<Specifiers_Topology-Port-Specifiers,topology port specifiers>>
inside the topology definition.

=== Instance Values

The interface concept is simply a set of port instances.
F Prime applies this concept to abstract connections
between ports in <<Specifiers_Connection-Graph-Specifiers,
connection graphs>>.

An *interface instance value* is a instance of a definition
that contains port instances. FPP has two types of interface
instance values:

. <<Definitions_Component-Instance-Definitions,Component Instances>>

.. Component instance values are bound to their corresponding
<<Interfaces_Anonymous-Interfaces_Anonymous-Component-Interfaces,
anonymous component interface>>.

. <<Definitions_Topology-Definitions,Topologies>>

.. Topology values are bound to their corresponding
<<Interfaces_Anonymous-Interfaces_Anonymous-Topology-Interfaces,
anonymous topology interface>>.

=== Binding

Interface binding refers to converting an interface value to a value
from another interface. This is done when passing interface arguments during
<<Specifiers_Template-Instantiation-Specifiers,template instantiation>>.

For an interface instance value _A_ associated with an anonymous interface _A'_,
the following conditions must be met for _A_ to bind to an interface _I_:

. For every <<Specifiers_Port-Instance-Specifiers,port instance>> _P_ in _I_:

.. There exists a port instance _P'_ in _A'_ that has the same name of _P_.

.. If _P_ is a <<Specifiers_Port-Instance-Specifiers_Semantics_General-Port-Instances,
general port instance>>, _P'_ must also be a general port instance:

... _P_ and _P'_ have the same port type

... If _P_ is an `input` port, _P'_ must also be an `input` port.

.... _P'_ must have the same calling behavior as _P_ (i.e. `async`,
`guarded`, `sync`).

... If _P_ is an `output` port, _P'_ must also be an `output` port.

... _P_ and _P'_ must share the same _number_ of ports.

.. If _P_ is a <<Specifiers_Port-Instance-Specifiers_Semantics_Special-Port-Instances,
special port instance>>, _P'_ must also be a special port instance:

... _P_ and _P'_ must share the same _special-port-kind_ and _special-port-input-kind_.
