==== Timeline Definitions

A *timeline definition* identifies an element of a
<<Detailed-Description_Definitions_State-Data-Definitions,state
data structure>> as a variable stored in a planning timeline.

===== Syntax

`timeline`
<<Detailed-Description_Expressions,_expression_>>
_[_ `in`
<<Detailed-Description_Expressions,_expression_>>
_]_

===== Semantics

* The first expression must be a
<<Detailed-Description_Expressions_Dot-Expressions,dot expression>>
or an
<<Detailed-Description_Expressions_Array-Index-Expressions,array index 
expression>>, and it must refer to a *transitive element* of a
structure stem:[S] appearing in a
<<Detailed-Description_Definitions_State-Data-Definitions,state
data definition>>. A transitive element of stem:[S] is one of the following:
(1) a structure member of stem:[S]; (2) a structure member of a transitive
element of stem:[S]; or (3) an array cell of a transitive element of stem:[S]. For
example, if `s` refers to a state data definition stem:[S], then `s.x`,
`s.x.y`, and `s.x[0]` are all transitive elements of stem:[S].

* <<Type-Checking,Type checking the first expression>> must produce a valid 
type stem:[T], and stem:[T] must be a 
<<Detailed-Description_Types_Set-Element-Types, set element type>>.

* The part of a timeline definition starting with the keyword `in` is
called the *in clause*. It is optional. If the in clause appears, then
<<Type-Checking,type checking the expression in the in clause>> must produce a 
type that is
<<Type-Checking_Type-Conversion,convertible to>> the
<<Detailed-Description_Types_Set-Types,set type>> `set` stem:[T].

* If no in clause appears, then the defined timeline may attain all the
values that are legal for the type stem:[T]. Otherwise, the timeline is
restricted to the values specified by the expression in the in clause,
after
<<Evaluation,evaluating the expression>> and
<<Evaluation_Type-Conversion_Converting-Values-to-Ranges-and-Sets,converting
the value to a set value>> if necessary.

===== Examples

See the examples in the
<<Overview_Defining-Planning-Timelines,Overview section on timeline definitions>>.
