// ======================================================================
// \title  StateToState_StateEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for StateToState_State enum
// ======================================================================

#include <cstring>
#include <limits>

#include "StateToState_StateEnumAc.hpp"

namespace FppTest {

  namespace SmState {

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    StateToState_State& StateToState_State ::
      operator=(const StateToState_State& obj)
    {
      this->e = obj.e;
#ifdef BUILD_UT
      this->m_serializeNumericValue = obj.m_serializeNumericValue;
      this->m_numericValue = obj.m_numericValue;
#endif
      return *this;
    }

    StateToState_State& StateToState_State ::
      operator=(enum T e1)
    {
      FW_ASSERT(isValid(e1), static_cast<FwAssertArgType>(e1));
      this->e = e1;
#ifdef BUILD_UT
      this->m_serializeNumericValue = false;
      this->m_numericValue = __FPRIME_UNINITIALIZED;
#endif
      return *this;
    }

#ifdef BUILD_UT

    std::ostream& operator<<(std::ostream& os, const StateToState_State& obj) {
      Fw::String s;
      obj.toString(s);
      os << s;
      return os;
    }

#endif

    // ----------------------------------------------------------------------
    // Member functions
    // ----------------------------------------------------------------------

    bool StateToState_State ::
      isValid() const
    {
      return isValid(this->e);
    }

    Fw::SerializeStatus StateToState_State ::
      serializeTo(
          Fw::SerialBufferBase& buffer,
          Fw::Endianness mode
      ) const
    {
      SerialType es = static_cast<SerialType>(this->e);
#ifdef BUILD_UT
      // Unit testing only: On request, override the enum value
      // with the numeric value, which is allowed to be invalid
      if (this->m_serializeNumericValue) {
        es = this->m_numericValue;
      }
#endif
      const Fw::SerializeStatus status = buffer.serializeFrom(es, mode);
      return status;
    }

    Fw::SerializeStatus StateToState_State ::
      deserializeFrom(
          Fw::SerialBufferBase& buffer,
          Fw::Endianness mode
      )
    {
      SerialType es;
      Fw::SerializeStatus status = buffer.deserializeTo(es, mode);
      if ((status == Fw::FW_SERIALIZE_OK) && !isValid(es)) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
      if (status == Fw::FW_SERIALIZE_OK) {
        this->e = static_cast<enum T>(es);
      }
      return status;
    }

#if FW_SERIALIZABLE_TO_STRING

    void StateToState_State ::
      toString(Fw::StringBase& sb) const
    {
      Fw::String s;
      switch (e) {
        case __FPRIME_UNINITIALIZED:
          s = "__FPRIME_UNINITIALIZED";
          break;
        case S1_S2:
          s = "S1_S2";
          break;
        case S1_S3:
          s = "S1_S3";
          break;
        case S4_S5:
          s = "S4_S5";
          break;
        default:
          s = "[invalid]";
          break;
      }
      sb.format("%s (%" PRIu8 ")", s.toChar(), e);
    }

#endif

#ifdef BUILD_UT

    void StateToState_State ::
      setSerializeValue(SerialType serializeValue)
    {
      this->m_numericValue = serializeValue;
      this->m_serializeNumericValue = true;
    }

#endif

    // ----------------------------------------------------------------------
    // Static functions
    // ----------------------------------------------------------------------

    bool StateToState_State ::
      isValid(SerialType serialTypeValue)
    {
      return ((serialTypeValue >= __FPRIME_UNINITIALIZED) && (serialTypeValue <= S4_S5));
    }

  }

}
