#!/bin/sh

# ----------------------------------------------------------------------
# Compile ref C++ files, to check them for validity
# ----------------------------------------------------------------------

cd `dirname $0`

fprime_gcc=../../../../scripts/fprime-gcc
export FPRIME_GCC_FLAGS="-Iinclude"

../fprime/generate_cpp

echo "running tests to generate the headers"
./run

for file in `find . -name '*Ac.ref.cpp'`
do
  echo "compiling $file"
  base=`echo $file | sed 's;\.cpp;;'`
  dest_base=`echo $base | sed 's;\(.*Ac\).*;\1;'`
  cp $base.hpp $dest_base.hpp
  cp $base.cpp $dest_base.cpp
  $fprime_gcc -I../../.. -c $dest_base.cpp -Wno-gnu-zero-variadic-macro-arguments
done
