#!/bin/sh

cd `dirname $0`

fprime_gcc=../../../../scripts/fprime-gcc
export FPRIME_GCC_FLAGS="-Iinclude"

../fprime/generate_cpp

echo "running tests to generate the headers"
./run

for file in `find . -name '*.ref.cpp'`
do
  base=`basename $file .ref.cpp`
  cp $base.ref.hpp $base.hpp
  cp $base.ref.cpp $base.cpp
  echo "compiling $base.cpp"
  $fprime_gcc -I../fprime/config -c $base.cpp
done
