// ======================================================================
// \title  PrimitiveStructSerializableAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PrimitiveStruct struct
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "PrimitiveStructSerializableAc.hpp"

// ----------------------------------------------------------------------
// Constructors
// ----------------------------------------------------------------------

PrimitiveStruct ::
  PrimitiveStruct() :
    Serializable(),
    m_s1(0.0f, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, false, Fw::String(""))
{

}

PrimitiveStruct ::
  PrimitiveStruct(const Primitive& s1) :
    Serializable(),
    m_s1(s1)
{

}

PrimitiveStruct ::
  PrimitiveStruct(const PrimitiveStruct& obj) :
    Serializable(),
    m_s1(obj.m_s1)
{

}

// ----------------------------------------------------------------------
// Operators
// ----------------------------------------------------------------------

PrimitiveStruct& PrimitiveStruct ::
  operator=(const PrimitiveStruct& obj)
{
  if (this == &obj) {
    return *this;
  }

  set(obj.m_s1);
  return *this;
}

bool PrimitiveStruct ::
  operator==(const PrimitiveStruct& obj) const
{
  return (this->m_s1 == obj.m_s1);
}

bool PrimitiveStruct ::
  operator!=(const PrimitiveStruct& obj) const
{
  return !(*this == obj);
}

#ifdef BUILD_UT

std::ostream& operator<<(std::ostream& os, const PrimitiveStruct& obj) {
  Fw::String s;
  obj.toString(s);
  os << s.toChar();
  return os;
}

#endif

// ----------------------------------------------------------------------
// Member functions
// ----------------------------------------------------------------------

Fw::SerializeStatus PrimitiveStruct ::
  serializeTo(
      Fw::SerialBufferBase& buffer,
      Fw::Endianness mode
  ) const
{
  Fw::SerializeStatus status;

  status = buffer.serializeFrom(this->m_s1, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  return status;
}

Fw::SerializeStatus PrimitiveStruct ::
  deserializeFrom(
      Fw::SerialBufferBase& buffer,
      Fw::Endianness mode
  )
{
  Fw::SerializeStatus status;

  status = buffer.deserializeTo(this->m_s1, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  return status;
}

FwSizeType PrimitiveStruct ::
  serializedSize() const
{
  FwSizeType size = 0;
  size += this->m_s1.serializedSize();
  return size;
}

#if FW_SERIALIZABLE_TO_STRING

void PrimitiveStruct ::
  toString(Fw::StringBase& sb) const
{
  Fw::String tmp;
  sb = "( ";

  // Format s1
  sb += "s1 = ";
  this->m_s1.toString(tmp);
  sb += tmp;
  sb += " )";
}

#endif

// ----------------------------------------------------------------------
// Setter functions
// ----------------------------------------------------------------------

void PrimitiveStruct ::
  set(const Primitive& s1)
{
  this->m_s1 = s1;
}

void PrimitiveStruct ::
  set_s1(const Primitive& s1)
{
  this->m_s1 = s1;
}
