#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_locate_defs=../../../bin/fpp-locate-defs

compare()
{
  outfile=$1
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_locate_defs $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  compare $outfile
}

. ./tests.sh

# Default tests
for t in $tests
do
  echo "
$t()
{
  run_test '' $t
}"
done > default-tests.sh
. ./default-tests.sh

stdin()
{
  $fpp_locate_defs < defs/defs-1.fpp > stdin.out.txt
  compare stdin
}

defs()
{
  run_test '' 'defs/defs-1.fpp defs/defs-2' defs
}

defs_dir()
{
  run_test '-d defs' 'defs/defs-1.fpp defs/defs-2' defs_dir
}

run_suite $tests
