#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_locate_defs=../../../bin/fpp-locate-defs

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_locate_defs $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

. ./tests.sh

# Default update ref
for t in $tests
do
  echo "
$t()
{
  update '' $t
}"
done > default-update-ref.sh
. ./default-update-ref.sh

defs()
{
  update '' 'defs/defs-1.fpp defs/defs-2' defs
}

defs_dir()
{
  update '-d defs' 'defs/defs-1.fpp defs/defs-2' defs_dir
}

stdin()
{
  $fpp_locate_defs < defs/defs-1.fpp > stdin.ref.txt
}

for t in $tests
do
  echo "updating ref output for $t"
  $t
done
