#!/bin/sh

compiler=../../../..

. $compiler/scripts/test-utils.sh

fpp_to_xml=$compiler/bin/fpp-to-xml

compare()
{
  outfile=$1
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_to_xml $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  compare $outfile
}

. ./tests.sh

# Default tests
for t in $tests
do
  echo "
$t()
{
  run_test '-p '$PWD $t
}"
done > default-tests.sh
. ./default-tests.sh

diff_xml()
{
  for file in $@
  do
    if ! diff $file'Ai.xml' $file'Ai.ref.xml'
    then
      return 1
    fi
  done
}

port_kwd_name()
{
  run_test "-p $PWD" port_kwd_name && \
    diff_xml PortKwdNamePort
}

port_ok()
{
  files=""
  for i in `seq 1 4`; do files="$files PortOK${i}Port"; done
  run_test "-i `fpp-depend port_ok.fpp | tr '\n' ','`  -p $PWD" port_ok && \
    diff_xml $files
}

types()
{
  for file in A E S
  do
    run_test "-p $PWD" $file
  done
}

run_suite $tests
