#!/bin/sh

compiler=../../../..

. $compiler/scripts/test-utils.sh

fpp_to_xml=$compiler/bin/fpp-to-xml
fpp_depend=$compiler/bin/fpp-depend

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_to_xml $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -maxdepth 1 -name '*.ref.txt'`
do
  rm $file
done

. ./tests.sh

# Default update ref
for t in $tests
do
  echo "
$t()
{
  update '-p '$PWD $t
}"
done > default-update-ref.sh
. ./default-update-ref.sh

move_xml()
{
  for file in $@
  do
    mv $file'Ai.xml' $file'Ai.ref.xml'
  done
}

port_kwd_name()
{
  update "-p $PWD" port_kwd_name
  move_xml PortKwdNamePort
}

port_ok()
{
  update "-i `fpp-depend port_ok.fpp | tr '\n' ','`  -p $PWD" port_ok
  move_xml PortOK1Port PortOK2Port PortOK3Port PortOK4Port
}

types()
{
  for file in A E S
  do
    update "-p $PWD" $file
  done
  move_xml AArray EEnum SSerializable
}

for t in $tests
do
  echo "updating ref output for $t"
  $t
done
