#!/bin/sh -e

codegen=../../../src/main/scala/codegen

files="
$codegen/Indentation.scala
$codegen/LineUtils.scala
$codegen/Line.scala
`ls $codegen/CppWriter/*.scala`
Main.scala
"

scalac -deprecation $files
