#!/bin/sh

cd `dirname $0`

. ../../../../scripts/test-utils.sh

cpp_doc_ok()
{
  ./gen_hpp > C.hpp && \
  ./gen_cpp > C.cpp && \
  ./gen_otherCpp > Other.cpp && \
  gcc -c C.cpp Other.cpp
}

tests="
cpp_doc_ok
"

scala --version
echo 'compiling Scala source'
if ./build > build_log.txt 2>&1
then
  run_suite $tests
else
  echo 'compilation failed'
  echo 'scalac version 2.13.1 or greater required'
  echo 'see build_log.txt for details'
fi
