#!/bin/sh

. ../../../../scripts/test-utils.sh

cpp_doc_ok()
{
  ./hpp > C.hpp && \
  ./cpp > C.cpp && \
  ./otherCpp > Other.cpp && \
  gcc -c C.cpp Other.cpp
}

tests="
cpp_doc_ok
"

# As of scala 3.5.0, the runner has changed
if scala --version 2>&1 | grep -q 'Scala code runner version:'
then
  echo 'installed scala version is incompatible with this test'
  exit 0
fi

echo 'compiling Scala source'
if ./build > build_log.txt 2>&1
then
  run_suite $tests
else
  echo 'compilation failed'
  echo 'scalac version 2.13.1 or greater required'
  echo 'see build_log.txt for details'
fi
