#!/bin/sh

. ../../../../scripts/test-utils.sh

cpp_doc_ok()
{
  ./hpp > C.hpp && \
  ./cpp > C.cpp && \
  ./otherCpp > Other.cpp && \
  gcc -c C.cpp Other.cpp
}

tests="
cpp_doc_ok
"

echo 'compiling Scala source'
if ! ./build > build_log.txt 2>&1
then
  echo 'compilation failed'
  echo 'scalac version 2.13.1 or greater required'
  echo 'see build_log.txt' for details
  exit 0
fi

if ! ./hpp > hpp_log.txt 2>&1
then
  echo 'cannot run hpp'
  echo 'scala version 3.4 or earlier is required'
  echo 'see hpp_log.txt' for details
  exit 0
fi

run_suite $tests
