#!/bin/sh -e

# ======================================================================
# Compile F Prime source files
# ---------------------------------------------------------------------- 
# Setup:
#
# 1. Set FPRIME to point to the root of your F Prime working repo
#
# ======================================================================

if test -z "$FPRIME"
then
  echo 'fprime-gcc: environment variable FPRIME is not set' 1>&2
  echo '  set FPRIME to the root of your F Prime working repo' 1>&2
  exit 1
fi

gcc -I $FPRIME -I $FPRIME/config -I $FPRIME/Fw/Types/Linux -I . $@
