#!/bin/sh -e

# ======================================================================
# Compile F Prime source files
# ---------------------------------------------------------------------- 
# Setup:
#
# 1. Set FPRIME to point to the root of your F Prime working repo
#
# ======================================================================

if test -z "$FPRIME"
then
  echo 'fprime-gcc: environment variable FPRIME is not set' 1>&2
  echo '  set FPRIME to the root of your F Prime working repo' 1>&2
  exit 1
fi

unset os_flags
os=`uname`
case "$os" in
  Darwin)
    os_type=DARWIN
    os_flags='-Wno-nullability-completeness'
    ;;
  Linux)
    os_type=LINUX
    ;;
  *)
    echo "fprime-gcc: unsupported OS $os" 1>&2
    exit 1
    ;;
esac

gcc --std=c++11 $os_flags -DTGT_OS_TYPE_$os_type -I $FPRIME -I $FPRIME/config -I $FPRIME/Fw/Types/Linux -I . -ferror-limit=1 $@
