=== Component Instance Definitions

A *component instance definition* defines an instance
of a
<<Definitions_Component-Definitions,component>>
that you can refer to in a
<<Specifiers_Component-Instance-Specifiers,topology definition>>.

==== Syntax

`instance`
<<Lexical-Elements_Identifiers,_identifier_>>
`:`
<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
`base` `id` <<Expressions,_expression_>>
_[_
`queue` `size` <<Expressions,_expression_>>
_]_
_[_
`stack` `size` <<Expressions,_expression_>>
_]_
_[_
`priority` <<Expressions,_expression_>>
_]_

==== Semantics

* The identifier names the component instance.

* The qualified identifier must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a
<<Definitions_Component-Definitions,component definition _D_>>.

* The expression following the keywords `base` `id` must have a
<<Types_Internal-Types_Numeric-Types,numeric type>>.
It associates a base identifier with the component instance.
The base identifier is used when resolving command opcodes and
event, telemetry, and parameter identifiers.

* If present, the expression following the keywords `queue` `size` must 
have a <<Types_Internal-Types_Numeric-Types,numeric type>>.
It specifies the queue size for active and queued components.
The queue size is required for active and queued components
and is not allowed for passive components.

* If present, the expression following the keywords `stack` `size` must
have a <<Types_Internal-Types_Numeric-Types,numeric type>>.
It specifies the stack size in bytes for active components.
The stack size is required for active components and is not allowed
for queued or passive components.

* If present, the expression following the keyword `priority` must
have a <<Types_Internal-Types_Numeric-Types,numeric type>>.
It specifies the thread priority for active components.
The priority is required for active components and is not allowed
for queued or passive components.

==== Example

[source,fpp]
----
instance commandDispatcher: Svc.CommandDispatcher \
  base id 0x100 \
  queue size 10 \
  stack size 4096 \
  priority 30
----
