=== Enumerated Constant Definitions

An *enumerated constant definition* is an element of an
<<Definitions_Enum-Definitions,enum
definition>>. Like a 
<<Definitions_Constant-Definitions,constant
definition>>, it associates a value with a named constant. It also
establishes that the constant is one of the values of the type defined
in the enum definition.

==== Syntax

<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`=` <<Expressions,_expression_>>
_]_

==== Semantics

If present, _expression_ must
<<Evaluation,evaluate>>
to a compile-time constant value _v_. At any model point where the
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> _Q_ refers to 
the enumerated constant definition according to the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,scoping
rules for names>>, you can use _Q_ as a name for the value that results
from converting _v_ to the
<<Definitions_Enum-Definitions_Semantics,type
of the enclosing enum definition>>.

The expression must be present or absent for all enumerated constant
definitions appearing in an
<<Definitions_Enum-Definitions,enum definitions>>.
If there are no expressions, then the enumerated constant definitions
are assigned increasing values starting with zero, as for
enumerations in C.

Note that the type of an enumerated constant value is the
<<Types_Enum-Types,enum
type>> defined by the enclosing enum definition. This may be
<<Type-Checking_Type-Conversion,converted
to the representation type of the enum>>. However, the reverse conversion
is not allowed: you can convert an enum type to a `U32` (for example),
but not a `U32` to an enum type. Nor can you convert one enum type to a
different one.

==== Example

The
<<Definitions_Enum-Definitions_Examples,examples
given for enum definitions>> include enumerated constant definitions.
