=== Interface Definitions

An *interface definition* defines a pure F Prime interface. An interface is
a collection of input and output ports that is expose functionality from
a component.

==== Syntax

`interface` <<Lexical-Elements_Identifiers,_identifier_>>
`{` _interface-member-sequence_ `}`

_interface-member-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is a *interface member*,
and the terminating punctuation is a semicolon.
An interface member is one of the following:

* A <<Specifiers_Port-Instance-Specifiers,port instance specifier>>

* An <<Specifiers_Interface-Import-Specifiers,interface import specifier>>

* An <<Specifiers_Interface-Template-Import-Specifiers,interface template import specifier>>

==== Semantics

The identifier is the name of the interface.
A component is said to *implement* an interface if it contains all
of the ports specified in the interface with matching names and port
types.

Interfaces can be <<Specifiers_Component-Import-Specifiers,imported>>
into an existing component. Importing an interface into a component will
place the port definitions in the interface into the component. This is
equivalent to places the port instances into the component directly.

==== Examples

[source,fpp]
----
interface I {
  output port p1: P
  guarded input port p2: P
}

active component C {
    import I
}

----
