=== Module Template Definitions

A *module template definition* associates a name
with a *module template*.
A module template is a set of syntactic elements, each of which
becomes a member of a <<Translation-Units-and-Models_Translation-Units,
translation unit>> or a
<<Definitions_Module-Definitions,module definition>>
at the point where the template is <<Expansion-of-Templates,expanded>>.
Each template may be expanded any number of times, and
each expansion creates a distinct set of translation unit
or module members.
Templates may have parameters that become bound
to <<Specifiers_Template-Expansion-Specifiers,arguments>>
at the point of expansion.

==== Syntax

`module` `template`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`(` <<Template-Parameter-Lists,_template-param-list_>> `)`
_]_
`{`
_module-member-sequence_
`}`

_module-member-sequence_ is identical to the module member sequence
of a <<Definitions_Module-Definitions,module definition>>.

==== Semantics

The identifier is the name of the template.

No module template definition may be the ancestor in the
abstract syntax tree of another module template definition
or of a <<Specifiers_Template-Expansion-Specifiers,template expansion specifier>>.
This rule ensures that <<Expansion-of-Templates,expanding a template>>
never causes another template to be defined or another
template expansion to occur.

A module template definition _M_ must pass the following analysis,
which does not depend on the body of _M_:

. The syntactic rule stated above.

. The rules governing the
  <<Template-Parameter-Lists,template parameter list>> of _M_.

. The rules governing <<Scoping-of-Names_Multiple-Global-Definitions-with-the-Same-Qualified-Name_Conflicting-Definitions,conflicting definitions>>.

. The rules governing <<Definitions-and-Uses_Uses,definitions and uses>>.

[NOTE] 
.Implementation Gap
==== 
In this version of FPP, the body of _M_ receives no analysis at the point
of the definition of _M_.
In particular, if no template expansion specifier refers to _M_, then
the body of _M_ is checked for syntactic correctness, but it is not
otherwise analyzed.
An error that occurs only in the body of _M_, such as a use of an
undefined symbol or a type error, is reported at each expansion of _M_,
and is not reported at all if _M_ is never expanded.
The <<Scoping-of-Names_Conflicting-Parameter-Names,rules for conflicting
parameter names>> are checked in the same way: at each expansion of _M_,
and not at the point of the definition of _M_.
As an exception to the above, a
<<Specifiers_Location-Specifiers,location specifier>> appearing in the body
of _M_ is analyzed at the point of the definition of _M_, whether or not
_M_ is expanded.
====

==== Example

[source,fpp]
----
module template MT(
    constant baseId: FwIdType
    instance comDriver: Drv.ByteStreamDriver
) {

    instance comStub: Svc.ComStub base id \
        baseId + 0x0800

    topology T {
        instance comDriver
        instance comStub

        # Connect to the driver from the parameter list
        connections Downlink {
            comStub.drvSendOut      -> comDriver.$send
            comDriver.sendReturnOut -> comStub.drvSendReturnIn
            comDriver.ready         -> comStub.drvConnected
        }
    }

}
----
