=== Module Template Definitions

A *module template definition* associates a name
with a *module template*.
A module template is a set of syntactic elements, each of which
becomes a member of a <<Translation-Units-and-Models_Translation-Units,
translation unit>> or a
<<Definitions_Module-Definitions,module definition>>
at the point where the template is <<Expansion-of-Templates,expanded>>.
Each template may be expanded any number of times, and
each expansion creates a distinct set of translation unit
or module members.
Templates may have parameters that become bound
to <<Specifiers_Template-Expansion-Specifiers,arguments>>
at the point of expansion.

==== Syntax

`module` `template`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`(` <<Template-Parameter-Lists,_template-param-list_>> `)`
_]_
`{`
_module-member-sequence_
`}`

_module-member-sequence_ is identical to the module member sequence
of a <<Definitions_Module-Definitions,module definition>>.

==== Semantics

The identifier is the name of the template.

_TODO: Specify the checking that is done on a module template definition.
Ideally, we should do all checking that can be done without knowing
the constants, types, and interface instances bound to the parameters._

==== Example

[source,fpp]
----
template MT(
    constant baseId: U32
    instance comDriver: ByteStreamDriver
) {

    instance comStub: Svc.ComStub base id \
        baseId + 0x0800

    topology T {
        instance comStub

        # Connect to the driver from the parameter list
        connections Downlink {
            # ComStub <-> ComDriver
            comStub.drvSendOut      -> comDriver.$send
            comDriver.sendReturnOut -> comStub.drvSendReturnIn
            comDriver.ready         -> comStub.drvConnected
        }
    }

}
----
