=== State Machine Definitions

A *state machine definition* defines a state machine.

There are two kinds of state machine definitions:

. An *external state machine definition*
introduces a name and informs the FPP analyzer that
a state machine implementation with that name will be provided to the
FSW build.

. An *internal state machine definition*
specifies the behavior of a state machine and
causes an implementation to be generated.

*Implementation note:*
Support for state machines will be implemented in two phases.
Phase 1 will implement external state machine definitions only.
Phase 2 will add support for internal state machine definitions.

==== Syntax

`state machine` <<Lexical-Elements_Identifiers,_identifier_>>
_[_ `{` _state-machine-member-sequence_ `}` _]_

_state-machine-member-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is a *state machine member*,
and the terminating punctuation is a semicolon.
A state machine member is one of the following:

* An <<State-Machine-Behavior-Elements_Action-Definitions,action definition>>
* A <<State-Machine-Behavior-Elements_Guard-Definitions,guard definition>>
* A <<State-Machine-Behavior-Elements_Initial-Transition-Specifiers,initial transition specifier>>
* A <<State-Machine-Behavior-Elements_Junction-Definitions,junction definition>>
* A <<State-Machine-Behavior-Elements_Signal-Definitions,signal definition>>
* A <<State-Machine-Behavior-Elements_State-Definitions,state definition>>

==== Semantics

. The identifier is the name of the state machine.

. If present, the optional state machine member sequence defines the
behavior of the state machine.
In this case, the state machine definition is internal.
If the state machine member sequence is absent, then the state machine
definition is external, i.e., the state machine
behavior is not specified in FPP.

. If present, the optional state machine member sequence _M_ must
satisfy the following rules:

.. _M_ must contain exactly one
<<State-Machine-Behavior-Elements_Initial-Transition-Specifiers,initial transition specifier>>.
The initial transition occurs when the state machine starts up.

.. _M_ must satisfy the rules described
<<Definitions_State-Machine-Definitions_The-Transition-Graph,below>>
for the induced transition graph.

==== The Transition Graph

If present, the optional state machine member sequence _M_
induces a directed graph called the *transition graph*, defined as
follows:

. The nodes of the transition graph are the initial transition specifiers,
state definitions, and
junction definitions that are transitive members of _M_.

. The *transitive members* of _M_ are (i) the elements of _M_ and (ii)
the members of any state definition that is a transitive member of _M_.

. The arcs of the transition graph are given by the <<State-Machine-Behavior-Elements_Enter-Expressions,
enter expressions>> _e_ that are parts of transitive members of _M_.
Each enter expression represents an arc from an *initial node* to a *terminal node*.
The initial node is defined as follows:

.. If _e_ appears in an
<<State-Machine-Behavior-Elements_Initial-Transition-Specifiers,
initial transition specifier>> _I_, then the initial node
is _I_.

.. If _e_ appears in a
<<State-Machine-Behavior-Elements_State-Transition-Specifiers,
state transition specifier>> _T_, then the initial
node is the
<<State-Machine-Behavior-Elements_State-Definitions,state definition>>
immediately enclosing _T_.

.. If _e_ appears in a
<<State-Machine-Behavior-Elements_Junction-Definitions,junction definition>>
_J_, then the initial node is _J_.

+
In any case,
the terminal node is the state definition or junction definition
<<Definitions_State-Machine-Definitions_Scoping-of-Names,referred to>>
in _e_ after the keyword `enter`.

If the optional state machine member sequence is present, then
the transition graph _T_ must satisfy the following rules:

. Each state machine definition and each junction definition in
_T_ must be the terminal node of at least one arc.

. Let _S_ be the subgraph of _T_ consisting of all
and only the junction definitions and the arcs whose initial
and terminal nodes are junction definitions.
There must be no cycles in _S_.

==== Scoping of Names

Inside the optional state machine member sequence, the following
rules govern the assignment of names to definitions and the resolution
of names in uses.

*State machine member definitions:*
There are five kinds of *state machine member definitions*:
Action definitions, guard definitions, junction definitions, state
definitions, and state machine signal definitions.

*Qualified names:*
Each state machine member definition has an associated qualified
name.
Within a state machine member sequence,
the association of names to state machine member definitions is
the same as for <<Scoping-of-Names_Names-of-Definitions,FPP definitions>>,
after replacing "`definition`" with "`state machine member definition.`"

For example:

[source,fpp]
----
state machine S {

  # Qualified name is A
  action A

  # Qualified name is S1
  state S1 {

    # Qualified name is S1.S2
    state S2

  }

}
----

*Conflicting names:*
Each kind of definition resides in its own name group, except
that states and junctions both reside in the state name group.
No two state machine definitions that reside in the same name group
may have the same qualified name.

*Resolution of names:*
Names are resolved in the ordinary way for
<<Scoping-of-Names_Resolution-of-Identifiers,identifiers>>
and
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,qualified identifiers>> in FPP,
with the following modifications:

. The top level is the state machine member sequence.

. The definitions are the state machine member definitions.

. Each kind of definition resides in its own name group.

. The brace-delimited definitions are state definitions.

==== Examples

[source,fpp]
----

state machine MonitorSm {

  signal Complete
  signal Drive
  signal Calibrate
  signal RTI
  signal Stop
  signal Fault

  action init2
  action doCalibrate
  action motorControl
  action reportFault

  guard calibrateReady

  initial enter DeviceOn

  state DeviceOn {

    initial do init2 enter Initializing

    state Initializing {
      on Complete enter Idle
    }

    state Idle {
      on Drive enter Driving
      on Calibrate if calibrateReady enter Calibrating
    }

    state Calibrating {
      on RTI do doCalibrate
      on Fault do reportFault enter Idle
      on Complete enter Idle
    }

    state Driving {
      on RTI do motorControl
      on Stop enter Idle
    }

  }

}
----
