=== State Machine Definitions

A *state machine definition* defines a state machine.

There are two ways to define a state machine:

. An *externally defined state machine* is an FPP definition
that introduces a name and informs the FPP analyzer that
a state machine with that name will be provided to the
implementation.

. An *internally defined state machine* is a state machine
that is fully specified in FPP.

*Implementation note:*
Support for state machines will be implemented in two phases.
Phase 1 will implement externally defined state machines only.
Phase 2 will add support for internally defined state machines.

==== Syntax

`state machine` <<Lexical-Elements_Identifiers,_identifier_>> 
_[_ `{` _state-machine-member-sequence_ `}` _]_

_state-machine-member-sequence_ is an 
<<Element-Sequences,element sequence>> in
which each element is a *state machine member*,
and the terminating punctuation is a semicolon.
A state machine member is one of the following:

* An <<State-Machine-Behavior-Elements_Action-Definitions,action definition>>
* A <<State-Machine-Behavior-Elements_Guard-Definitions,guard definition>>
* A <<State-Machine-Behavior-Elements_State-Definitions,state definition>>
* A <<State-Machine-Behavior-Elements_Initial-Transition-Specifiers,state initial>>
* A <<State-Machine-Behavior-Elements_State-Junction,state junction>>
* A <<State-Machine-Behavior-Elements_State-Machine-Event-Definitions,state machine event definition>>

==== Semantics

. The identifier is the name of the state machine.

. If present, the optional state machine member sequence defines the
behavior of the state machine.
In this case, the state machine is internally defined.
If the state machine member sequence is absent, then the state machine
behavior is not specified in FPP.
In this case, the state machine is externally defined.

. The state machine member sequence must contain exactly one
<<State-Machine-Behavior-Elements_Initial-Transition-Specifiers,initial transition specifier>>.

==== Examples

[source,fpp]
----

state machine MonitorSm {

  event Complete
  event Drive
  event Calibrate
  event RTI
  event Stop
  event Fault
  
  action init2
  action doCalibrate
  action motorControl
  action reportFault

  guard calibrateReady

  initial DeviceOn
  
  state DeviceOn {

    initial Initializing do init2

    state Initializing {
      on Complete visit Idle
    }

    state Idle {
      on Drive visit Driving
      on Calibrate if calibrateReady visit Calibrating
    }

    state Calibrating {
      on RTI do doCalibrate
      on Fault go Idle do reportFault
      on Complete visit Idle
    }

    state Driving {
      on RTI do motorControl
      on Stop visit Idle
    }

  }

}
----
