=== Struct Definitions

A *struct definition* defines a new structure type and associates a name
with it.

==== Syntax

`struct` <<Lexical-Elements_Identifiers,_identifier_>>
`{` _struct-type-member-sequence_ `}`
_[_ `default` <<Expressions,_expression_>> _]_

_struct-type-member-sequence_ is an <<Element-Sequences,element sequence>>
in which the elements are struct type members, and the terminating
punctuation is a comma.
A *struct type member* has the following syntax:

<<Lexical-Elements_Identifiers,_identifier_>> `:` <<Type-Names,_type-name_>>

==== Semantics

The identifier is the name _N_ of the type.  The definition associates the name
_N_ with a type, _T'_ representing a structure with named members, each
of the specified type.  Each
identifier appearing in the struct type member sequence must be distinct.

The expression is optional.
If present, it specifies the <<Types_Default-Values,default value>>
associated with the type.
The type of the expression must be
<<Type-Checking_Type-Conversion,convertible to>> _T'_.

The type name _N_ is not in scope in the body of the definition.

==== Examples

[source,fpp]
----
# Defines a struct type A with members x and y
# and default value { x = 0, y = 0 }
struct A {
  x: U32
  y: F32
}
# Defines a struct type B with members x and y
# and default value { x = 0, y = 1 }
struct B {
  x: U32
  y: F32
} default { y = 1 }
----
