=== Topology Import Specifiers

A *topology import specifier* imports one topology into another one.

==== Syntax

`import` <<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>

==== Semantics

The qualified identifier must 
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a
<<Definitions_Topology-Definitions,topology definition>>.

FPP uses the following algorithm to compute _T_, which is the result of 
importing a topology _T'_ into a topology _T_:

. Let _I_ be the set of 
<<Definitions_Component-Instance-Specifiers,instances>>
of _T_.  Let _I'_ be the set of 
<<Definitions_Component-Instance-Specifiers,public instances>>
of _T'_.

. Let _I_ be the set union of _I_ and _I'_.
That means that if either or both of _I_ and _I'_ contain the 
instance _i_,
then _N_ contains the instance _i_ once.

. Let _C_ be the set of 
<<Definitions_Connection-Graph-Definitions,connections>>
of _T_.
Let _C'_ be the set of
<<Definitions_Connection-Graph-Definitions,connections>>
of _T'_.

. Let _C_ be the disjoint union of _C_ and _C'_.
That means that if _C_ contains _n_ connections between port
_p_ and port _p'_, and _C'_ contains _m_ connections between
port _p_ and port _p'_, then _C_ contains _n + m_ connections
between port _p_ and port _p'_.

. Let _T_ be the topology constructed from _I_ and _C_,
after applying
<<Definitions_Topology-Definitions_Semantics_Automatic-Numbering-of-Array-Indices,
automatic numbering of array indices>>.

==== Examples

TODO
