=== Topology Definitions

A *topology definition* defines an F Prime topology,
that is, a set of interface instances, port instances,
and the connections between their port instances.
The connections are divided into named *connection graphs*.
The different graphs capture different aspects of FSW
function, such as commanding and telemetry.

One topology can be imported into another one.
The connections are merged graph by graph.

==== Syntax

`topology`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_ `implements` _interface-list_ _]_
`{` _topology-member-sequence_ `}`

The optional _interface-list_ is an
<<Element-Sequences,element sequence>> in which
each element is a <<Scoping-of-Names_Qualified-Identifiers,
qualified identifier>> and the terminating puncuation is a comma.

_topology-member-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is a *topology member*,
and the terminating punctuation is a semicolon.
A topology member is one of the following:

* A <<Specifiers_Interface-Instance-Specifiers,interface
instance specifier>>

* A <<Specifiers_Connection-Graph-Specifiers,connection graph specifier>>

* A <<Specifiers_Telemetry-Packet-Set-Specifiers,telemetry packet set specifier>>

* A <<Specifiers_Topology-Import-Specifiers,topology import specifier>>

* A <<Specifiers_Topology-Port-Instance-Specifiers,topology port instance specifier>>

* An <<Specifiers_Include-Specifiers,include specifier>>

==== Semantics

The identifier is the name of the topology.

All <<Specifiers_Topology-Port-Instance-Specifiers,topology port instance specifiers>>
inside the topology must have a distinct name.

The set of all <<Specifiers_Topology-Port-Instance-Specifiers,topology port instance specifiers>>
make up the enclosing topology's <<Port-Interfaces_Anonymous-Port-Interfaces_Anonymous-Topology-Port-Interfaces,
anonymous port interface>>. Each port specifier maps an unqualified name to a port instance
satifying the <<Specifiers_Topology-Port-Instance-Specifiers_Semantics,rules>>
for topology port instance specifiers.

If _interface-list_ is provided, each element of the list must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>> an
<<Definitions_Port-Interface-Definitions,interface definition stem:[K_i]>>.
This optional clause is a compile-time check that
verifies that this topology can <<Port-Interfaces_Binding,bind to>> all stem:[K_i].

A topology definition _D_ must be resolvable to a topology _T_,
according to the following algorithm:

. Resolve _D_ to a
<<Definitions_Topology-Definitions_Semantics_Resolving-to-a-Partially-Numbered-Topology,
partially numbered topology>> _T'_.

. <<Definitions_Topology-Definitions_Semantics_Checking-Telemetry-Packet-Set-Specifiers,
Check telemetry packet set specifiers>> for _T'_.

. Apply
<<Definitions_Topology-Definitions_Semantics_Automatic-Numbering-of-Ports,
automatic numbering of ports>>
to _T'_.

===== Resolving to a Partially Numbered Topology

A *partially numbered topology* is a topology in which port number
assignments may or may not exist for each connection.
A port number assignment exists if
it is specified in the model source.

. For each endpoint _E_ (output or input) in each connection _C_
appearing in _D_,
if _E_ has a port number  expression _e_ in the FPP source, then
<<Evaluation,evaluate>> _e_,
<<Type-Checking_Type-Conversion,convert>> the result to a value _n_ of type
_Integer_, and assign the port number _n_ at that position.
Check that _n_ is in bounds for the port instance being numbered.

. Recursively resolve all the topologies directly imported into _D_.

. Construct the connection graphs of _T_ given by the
<<Specifiers_Connection-Graph-Specifiers,direct connection graphs>>
appearing in
_D_, after merging each set of connection graphs with the same name into
a single graph.
For example, the two connection graphs
+
[source,fpp]
----
connections C { a.b -> c.d }
----
+
and
+
[source,fpp]
----
connections C { e.f -> g.h }
----
+
are treated as the single graph
+
[source,fpp]
----
connections C { a.b -> c.d, e.f -> g.h }
----
+

. Compute the set _S_ of topologies transitively imported into _T_.

.. A topology is imported either through an
<<Specifiers_Topology-Import-Specifiers,import specifier>>
or through an <<Specifiers_Interface-Instance-Specifiers,
instance specifier>>.

. For each topology _T'_ in _S_,
<<Specifiers_Topology-Import-Specifiers,import the instances>>
of _T'_ into _T_.

. For each connection discovered in step 3, check that each endpoint _I_ `.` _P_ is available
in _T_ through at least one of the following conditions:

.. _I_ is <<Scoping-of-Names_Resolution-of-Qualified-Identifiers,referred to>>
in an <<Specifiers_Interface-Instance-Specifiers,
instance specifier>> or <<Specifiers_Topology-Import-Specifiers,import specifier>>
in _T_ and _P_ exists in the <<Port-Interfaces,port interface>> of _I_.

.. _I_ is an instance interface available in a topology in _S_.

. For each topology _T'_ in _S_,
<<Specifiers_Topology-Import-Specifiers,import the connections>>
of _T'_ into _T_.

. For each <<Instance-Member-Identifiers_Port-Instance-Identifiers,
connection endpoint>> _Q_ . _I_ in _T_, resolve the endpoint to a
port instance in a <<Definitions_Component-Instance-Definitions,component instance>>:

.. If _Q_ is a component instance, this endpoint is resolved.

.. If _Q_ refers to a <<Definitions_Topology-Definitions,
topology definition>>, find the <<Specifiers_Topology-Port-Instance-Specifiers,
topology port instance specifier>> that corresponds to _I_ in the topology referenced
by _Q_. Re-apply these rules with the port instance refered to in the topology
port specifier.

. Resolve
<<Specifiers_Connection-Graph-Specifiers,graph pattern specifiers>>,
adding connections to _T_.
Add only connections that are not already present in _T_.
For example, if a command pattern indicates a command
registration connection between two ports, and there is already
a command registration connection between those ports, then
do not add the connection.

===== Checking Telemetry Packet Set Specifiers

FPP checks telemetry packet set specifiers as follows:

. Check that no two telemetry packet set specifiers have
the same name.

. Check that each telemetry packet set specifier is
<<Specifiers_Telemetry-Packet-Set-Specifiers_Semantics,valid>>.

Note that a telemetry packet set specifier is not required.
If there is no specifier, then the topology has no packet definitions.
Note also that two or more telemetry packet set specifiers
are allowed.
Each one specifies a way of assigning the telemetry channels
of the topology to a set of packets.

===== Automatic Numbering of Ports

FPP automatically assigns port numbers as follows.

*Check output port numbers:*
At each output port _p_ of each <<Definitions_Component-Instance-Definitions,
component instance _I_>>, check the following:

. The number of connections is in bounds for the
size of _I_ `.` _p_.

. There is no pair of connections stem:[c_1] and stem:[c_2]
at the same port number of _I_ `.` _p_.
For example, the following pair of connections is not allowed:
+
[source,fpp]
----
a.p[0] -> b.p
a.p[0] -> c.p
----

*Apply matched numbering:*
Assign matching numbers to matched pairs of ports.
For each component instance definition _I_ in the topology:

. Let _C_ be the <<Definitions_Component-Definitions,component definition>> of _I_.

.  For each
<<Specifiers_Port-Matching-Specifiers,port matching specifier>>
`match` stem:[p_1] `with` stem:[p_2] appearing in _C_:

.. For each of _i_ = 1 and _i_ = 2, check that no two distinct connections
at _I_ `.` stem:[p_i] have the same port number assigned to them.

.. Any connection that names _I_ `.` stem:[p_1] or _I_ `.` stem:[p_2]
is *match constrained*. If a match constrained connection is marked
`unmatched` then it is *unmatched*; otherwise it is *matched*.

..  For each matched connection stem:[c_1] with an endpoint at _I_ `.` stem:[p_1]:

... Let _I'_ be the port interface instance at the other endpoint
of stem:[c_1].

... Check that there is one and only one matched connection
stem:[c_2] between _I'_ and _I_ `.` stem:[p_2].

.. Check that the connections stem:[c_2] computed in the previous
step are all the matched connections at _I_ `.` stem:[p_2].

.. For each pair stem:[(c_1,c_2)] computed in step c:

... If stem:[c_1] has a port number stem:[n_1] assigned at _I_ `.` stem:[p_1] and 
stem:[c_2] has a port number stem:[n_2] assigned at
_I_ `.` stem:[p_2], then check that stem:[n_1 = n_2].

... Otherwise if stem:[c_1] has a port number _n_ assigned at _I_ `.` stem:[p_1],

.... If no connection at _I_ `.` stem:[p_2] has port number _n_ assigned to it,
then assign _n_ to stem:[c_2] at _I_ `.` stem:[p_2].

.... Otherwise an error occurs.

... Otherwise if stem:[c_2] has a port number _n_ assigned at _I_ `.` stem:[p_2],

.... If no connection at _I_ `.` stem:[p_1] has port number _n_ assigned to it,
then assign _n_ to stem:[c_1] at _I_ `.` stem:[p_1].

.... Otherwise an error occurs.

.. Traverse the pairs stem:[(c_1,c_2)] computed in step c according to the
<<Definitions_Topology-Definitions_Semantics_Ordering-of-Connections,
order>> of the connections stem:[c_1], least to greatest.
For each pair stem:[(c_1,c_2)] that does not yet have assigned
port numbers, find the lowest available port number
and assign it at _I_ `.` stem:[p_1] and _I_ `.` stem:[p_2].
A port number _n_ is available if (a) _n_ is in bounds for _I_ `.` stem:[p_1]
and _I_ `.` stem:[p_2]; and (b)
_n_ is not already assigned to a connection at _I_ `.` stem:[p_1]; and (c)
_n_ is not already assigned to a connection at _I_ `.` stem:[p_2].
If no port number is available, then an error occurs.
Note that stem:[p_1] and stem:[p_2]
<<Specifiers_Port-Matching-Specifiers_Semantics,are required to have the
same size for their port arrays>>.

*Apply general numbering:*
Fill in any remaining port numbers.

. Traverse the connections
<<Definitions_Topology-Definitions_Semantics_Ordering-of-Connections,
in order>>, least to greatest.

. For each output endpoint _P_ in each connection _C_,
if no port number is already assigned, then assign the lowest available port
number at position _P_.


. For each input endpoint _P_ in each connection _C_, if no port number is
already assigned, then assign the port number zero.

See Example 4 in the <<Definitions_Topology-Definitions_Examples,Examples section>>.

===== Ordering of Connections

For purposes of port numbering, FPP orders connections as follows.

A connection endpoint in an FPP topology refers to a
<<Instance-Member-Identifiers_Port-Instance-Identifiers,port instance identifier>>.

**TODO(tumbar)** Should we just directly reference <<Port-Interfaces,port interfaces>>
here and just call out to <<Port-Interfaces_Port-Interface-Instance,port interface instance>>?

A *connection endpoint* is _I_ `.` _p_ or _I_ `.` _p_ `[` _n_ `]`, where

. _I_ is an <<Port-Interfaces_Port-Interface-Instance,
port interface instance>> that is included in the topology via a
<<Specifiers_Interface-Instance-Specifiers,interface instance specifier>> or implicitely
a <<Specifiers_Topology-Import-Specifiers,topology import specifier>>.

. And _p_ meets the following conditions:

.. If _I_ refers to a **component instance**, _p_ is an identifier that names a port instance specified in
the component definition associated with _I_.

.. If _I_ refers to a **topology definition**, _p_ identifiers an
<<Specifiers_Topology-Port-Instance-Specifiers,topology port instance>> inside _I_.

. _n_ is an optional port number that is present if and only
if it appears in the model source.

When a connection endpoint _e_ has the form _I_ `.` _p_ `[` _n_ `]`,
we say that the endpoint *has source port number* _n_.

Each connection endpoint has a *fully qualified name*.
The fully qualified name is _Q_ `.` _p_, where _Q_ is the
<<Scoping-of-Names_Names-of-Definitions,fully qualified name>>
of the instance _I_.

FPP orders connection endpoints stem:[e_1] and stem:[e_2] as follows:

. If the fully qualified name of stem:[e_1] is lexically less
than (respectively greater than) the fully qualified name of
stem:[e_2], then stem:[e_1] is less than (respectively greater than) stem:[e_2].

. Otherwise if stem:[e_1] and stem:[e_2] have source port numbers
port numbers stem:[n_1] and stem:[n_2],
then the ordering of stem:[e_1]
and stem:[e_2] is the same as the numerical ordering of stem:[n_1]
and stem:[n_2].

. Otherwise stem:[e_1] and stem:[e_2] are equal in the ordering.

*Connections:* A *connection* is stem:[e_1] `pass:[->]`
stem:[e_2],
where stem:[e_1] and stem:[e_2] are the connection endpoints.
FPP orders connections stem:[c_1] and stem:[c_2] as follows:

. Let connection stem:[c_1] be stem:[e_1] `pass:[->]`
stem:[e'_1].

. Let connection stem:[c_2] be stem:[e_2] `pass:[->]`
stem:[e'_2].

. If stem:[e_1] is less than (respectively greater than)
stem:[e_2],
then stem:[c_1] is less than (respectively greater than) stem:[c_2].

. Otherwise if stem:[e'_1] is less than (respectively greater than)
stem:[e'_2], then stem:[c_1] is less than (respectively greater than)
stem:[c_2].

. Otherwise stem:[c_1] and stem:[c_2] are equal in the ordering.

==== Implied Uses

When generating a dictionary from a topology _T_, the analyzer may
treat the definition of _T_ as if it contained uses of
one or more <<Definitions_Framework-Definitions,
framework alias type definitions>> that are required by the dictionary.
These uses are called *implied uses*.

The management of these implied uses is left up to the FPP implementation.
The only requirement levied here is that, when generating a dictionary,
the FPP implementation must guarantee that all the framework definitions
required by the dictionary specification are available in the model.
Those framework definitions are specified
in the https://fprime.jpl.nasa.gov/latest/docs/reference/fpp-json-dict/[F Prime 
dictionary specification].

==== Examples

*Example 1.*

[source,fpp]
----
@ Command and data handling topology
topology CDH {

  # ----------------------------------------------------------------------
  # Public instances
  # ----------------------------------------------------------------------

  instance commandSequencer
  instance engineeringRateGroup
  instance engineeringTelemetryLogger
  instance engineeringTelemetryConverter
  instance engineeringTelemetrySplitter
  instance eventLogger
  instance rateGroupDriver
  instance telemetryDatabase
  instance timeSource

  # ----------------------------------------------------------------------
  # Connection patterns
  # ----------------------------------------------------------------------

  command connections instance commandDispatcher
  event connections instance eventLogger
  time connections instance timeSource

  # ----------------------------------------------------------------------
  # Connection graphs
  # ----------------------------------------------------------------------

  connections CommandSequences {
    commandSequencer.comCmdOut -> commandDispatcher.comCmdIn
  }

  connections Downlink {
    eventLogger.comOut -> socketGroundInterface.comEventIn
    telemetryDatabase.comOut -> socketGroundInterface.comTlmIn
  }

  connections EngineeringTelemetry {
    commandDispatcher.tlmOut -> engineeringTelemetrySplitter.tlmIn
    commandSequencer.tlmOut -> telemetryDatabase.tlmIn
    engineeringRateGroup.tlmOut -> engineeringTelemetrySplitter.tlmIn
    engineeringTelmetryConverter.comTlmOut -> engineeringTelemetryLogger.comTlmIn
    engineeringTelemetrySplitter.tlmOut -> engineeringTelemetryConverter.tlmIn
    engineeringTelemetrySplitter.tlmOut -> telemetryDatabase.tlmIn
  }

  connections RateGroups {
    engineeringRateGroup.schedOut -> commandSequencer.schedIn
    engineeringRateGroup.schedOut -> telemetryDatabase.schedIn
    rateGroupDriver.cycleOut -> engineeringRateGroup.cycleIn
  }

  connections Uplink {
    socketGroundInterface.comCmdOut -> commandDispatcher.comCmdIn
  }

}
----

*Example 2.*

[source,fpp]
----
@ Attitude control topology
topology AttitudeControl {

  # ----------------------------------------------------------------------
  # Imported topologies
  # ----------------------------------------------------------------------

  import CDH

  # ----------------------------------------------------------------------
  # Public instances
  # ----------------------------------------------------------------------

  instance acsRateGroup
  instance attitudeControl
  instance socketGroundInterface
  ...

  # ----------------------------------------------------------------------
  # Connection patterns
  # ----------------------------------------------------------------------

  command connections instance commandDispatcher
  event connections instance eventLogger
  time connections instance timeSource


  # ----------------------------------------------------------------------
  # Connection graphs
  # ----------------------------------------------------------------------

  connections AttitudeTelemetry {
    ...
  }

  connections Downlink {
    eventLogger.comOut -> socketGroundInterface.comEventIn
    telemetryDatabase.comOut -> socketGroundInterface.comTlmIn
  }

  connections EngineeringTelemetry {
    acsRateGroup.tlmOut -> engineeringTelemetrySplitter.tlmIn
    ...
  }

  connections RateGroups {
    acsRateGroup.schedOut -> attitudeControl.schedIn
  }

  connections Uplink {
    socketGroundInterface.comCmdOut -> commandDispatcher.comCmdIn
  }

}
----

*Example 3.*

[source,fpp]
----
@ Release topology
topology Release {

  # ----------------------------------------------------------------------
  # Imported topologies
  # ----------------------------------------------------------------------

  import AttitudeControl
  import CDH
  import Communication
  ...

  # Connecting sub topologies together
  connections CDH {
    Communication.uplink -> CDH.dataUp
    CDH.dataDown -> Communication.downlink
  }

}
----

*Example 4.*

Here is the topology that results from automatic numbering of ports
applied to topology `B` in the
<<Specifiers_Topology-Import-Specifiers_Example,example for topology import
specifiers>>:

[source,fpp]
----
topology B {

  instance a
  instance c
  instance d
  instance e
  instance f

  connections C1 {
    a.p1[0] -> c.p[0]
    a.p1[1] -> d.p[0]
  }

  connections C2 {
    a.p2[0] -> e.p[0]
  }

  connections C3 {
    a.p3[0] -> f.p[0]
  }

}
----
