=== Topology Definitions

A *topology definition* defines an F Prime topology,
that is, a set of component instances and the connections
between their ports.
The connections are divided into named *connection graphs*.
The different graphs capture different aspects of FSW
function, such as commanding and telemetry.

One topology can be imported into another one.
The connections are merged graph by graph.

==== Syntax

`topology` 
<<Lexical-Elements_Identifiers,_identifier_>>
`{` _topology-member-sequence_ `}`

_topology-member-sequence_ is an
<<Element-Sequences,element sequence>> in 
which each element is a *topology member*,
and the terminating punctuation is a semicolon.
A topology member is one of the following:

* A <<Specifiers_Component-Instance-Specifiers,component 
instance specifier>>

* A <<Specifiers_Connection-Graph-Specifiers,connection graph specifier>>

* A <<Specifiers_Topology-Import-Specifiers,topology import specifier>>

* An <<Specifiers_Include-Specifiers,include specifier>>

==== Semantics

A topology definition _D_ must be resolvable to a topology _T_,
according to the following algorithm:

. Resolve _D_ to a
<<Definitions_Topology-Definitions_Semantics_Resolving-to-a-Partially-Numbered-Topology,
partially numbered topology>> _T'_.

. Apply 
<<Definitions_Topology-Definitions_Semantics_Automatic-Numbering-of-Ports,
automatic numbering of ports>>
to _T'_.

===== Resolving to a Partially Numbered Topology

A *partially numbered topology* is a topology in which port number
assignments may or may not exist for each connection.
A port number assignment exists if
it is specified in the model source.

. For each endpoint _E_ (output or input) in each connection _C_
appearing in _D_,
if _E_ has a port number  expression _e_ in the FPP source, then
<<Evaluation,evaluate>> _e_,
<<Type-Checking_Type-Conversion,convert>> the result to a value _n_ of type 
_Integer_, and assign the port number _n_ at that position.
Check that _n_ is in bounds for the port instance being numbered.

. Recursively resolve all the topologies directly imported into _D_.

. Construct the connection graphs of _T_ given by the
<<Specifiers_Connection-Graph-Specifiers,direct connection graphs>>
appearing in
_D_, after merging each set of connection graphs with the same name into
a single graph.
For example, the two connection graphs
+
[source,fpp]
----
connections C { a.b -> c.d }
----
+
and
+
[source,fpp]
----
connections C { e.f -> g.h }
----
+
are treated as the single graph
+
[source,fpp]
----
connections C { a.b -> c.d, e.f -> g.h }
----
+

. Compute the set _S_ of topologies transitively imported into _T_.

. For each topology _T'_ in _S_, 
<<Specifiers_Topology-Import-Specifiers,import the instances>>
of _T'_ into _T_.

. Check that the connections discovered in step 3 are between port 
instances present in _T_.

. For each topology _T'_ in _S_, 
<<Specifiers_Topology-Import-Specifiers,import the connections>>
of _T'_ into _T_.

. Resolve 
<<Specifiers_Connection-Graph-Specifiers,graph pattern specifiers>>,
adding connections to _T_.
Add only connections that are not already present in _T_.
For example, if a command pattern indicates a command
registration connection between two ports, and there is already
a command registration connection between those ports, then
do not add the connection.

===== Automatic Numbering of Ports

FPP automatically assigns port numbers as follows.

*Check output port numbers:*
At each output port _p_ of each component instance _I_, check that

. The number of connections is in bounds for the 
size of _I_ `.` _p_.

. There is no pair of connections stem:[c_1] and stem:[c_2]
at the same port number of _I_ `.` _p_.
For example, the following pair of connections is not allowed:
+
[source,fpp]
----
a.p[0] -> b.p
a.p[0] -> c.p
----

*Apply matched numbering:*
Assign matching numbers to matched pairs of ports.
For each instance _I_ in the topology:

. Let _C_ be the component type of _I_.

.  For each
<<Specifiers_Port-Matching-Specifiers,port matching specifier>>
`match` stem:[p_1] `with` stem:[p_2] appearing in the definition of _C_:
 
..  For each connection stem:[c_1] with an endpoint at _I_ `.` stem:[p_1]:
 
... Let _I'_ be the component instance at the other endpoint
of stem:[c_1].
 
... Check that there is one and only one connection
stem:[c_2] from _I'_ to _I_ `.` stem:[p_2].

.. Check that the connections stem:[c_2] computed in the previous
step are all the connections at _I_ `.` stem:[p_2].
 
.. For each pair stem:[(c_1,c_2)] that has both port numbers assigned,
check that the port numbers match.
For each pair stem:[(c_1,c_2)] that has exactly one port number assigned,
assign the other one to match.
 
.. Traverse the pairs stem:[(c_1,c_2)] according to the
<<Definitions_Topology-Definitions_Semantics_Ordering-of-Connections,
order>> of the connections stem:[c_1], least to greatest.
For each pair stem:[(c_1,c_2)] that does not yet have assigned
port numbers, find the lowest available port number
and assign it at _I_ `.` stem:[p_1] and _I_ `.` stem:[p_2].
A port number is available if (a) it is in bounds for the 
port instance being numbered; and (b)
it is not already assigned to the same port instance
in the topology.

Note that in the last step,
the two ports _I_ `.` stem:[p_1] and _I_ `.` stem:[p_2].
have the same array size and
the same port numbers assigned so far, so the lowest
available port number is the same for both.

*Apply general numbering:* 
Fill in any remaining port numbers.

. Traverse the connections
<<Definitions_Topology-Definitions_Semantics_Ordering-of-Connections,
in order>>, least to greatest.

. For each output endpoint _P_ in each connection _C_,
if no port number is already assigned, then assign the lowest available port 
number at position _P_.


. For each input endpoint _P_ in each connection _C_, if no port number is 
already assigned, then assign the port number zero.

See Example 4 below.

===== Names of Connections

The fully qualified name of a connection _I_ `.` _p_
is _Q_ `.` _p_, where _Q_ is the
<<Scoping-of-Names_Names-of-Definitions,fully qualified name>>
of the instance _I_.

===== Ordering of Connections

For purposes of numbering, FPP orders connections
stem:[c_1] and stem:[c_2] as follows:

. Let connection stem:[c_1] be stem:[I_1] `.` stem:[p_1] `pass:[->]`
stem:[I'_1] `.` stem:[p'_1],
ignoring any port numbers that may be assigned to the endpoints.

. Let connection stem:[c_2] be stem:[I_2] `.` stem:[p_2] `pass:[->]`
stem:[I'_2] `.` stem:[p'_2].

. If the
<<Definitions_Topology-Definitions_Semantics_Names-of-Connections,
fully qualified name>>
of stem:[I_1] `.` stem:[p_1] is lexically less
than (respectively greater than) the fully qualified name of
stem:[I_2] `.` stem:[p_2], then
stem:[c_1] is less than (respectively greater than) stem:[c_2].

. Otherwise if the fully qualified name of stem:[I'_2] `.` stem:[p'_2]
is lexically less than (respectively greater than) the fully qualified name of
stem:[I'_2] `.` stem:[p'_2], then stem:[c_1]
is less than (respectively greater than) stem:[c_2].

. Otherwise stem:[c_1] and stem:[c_2] are equal.

==== Examples

*Example 1.*

[source,fpp]
----
@ Command and data handling topology
topology CDH {

  # ----------------------------------------------------------------------
  # Public instances 
  # ----------------------------------------------------------------------

  instance commandDispatcher
  instance commandSequencer
  instance engineeringRateGroup
  instance engineeringTelemetryLogger
  instance engineeringTelemetryConverter
  instance engineeringTelemetrySplitter
  instance eventLogger
  instance rateGroupDriver
  instance telemetryDatabase
  instance timeSource

  # ----------------------------------------------------------------------
  # Private instances 
  # ----------------------------------------------------------------------

  private instance socketGroundInterface

  # ----------------------------------------------------------------------
  # Connection patterns
  # ----------------------------------------------------------------------

  command connections instance commandDispatcher
  event connections instance eventLogger
  time connections instance timeSource

  # ---------------------------------------------------------------------- 
  # Connection graphs
  # ---------------------------------------------------------------------- 

  connections CommandSequences {
    commandSequencer.comCmdOut -> commandDispatcher.comCmdIn
  }

  connections Downlink {
    eventLogger.comOut -> socketGroundInterface.comEventIn
    telemetryDatabase.comOut -> socketGroundInterface.comTlmIn
  }

  connections EngineeringTelemetry {
    commandDispatcher.tlmOut -> engineeringTelemetrySplitter.tlmIn
    commandSequencer.tlmOut -> telemetryDatabase.tlmIn
    engineeringRateGroup.tlmOut -> engineeringTelemetrySplitter.tlmIn
    engineeringTelmetryConverter.comTlmOut -> engineeringTelemetryLogger.comTlmIn
    engineeringTelemetrySplitter.tlmOut -> engineeringTelemetryConverter.tlmIn
    engineeringTelemetrySplitter.tlmOut -> telemetryDatabase.tlmIn
  }

  connections RateGroups {
    engineeringRateGroup.schedOut -> commandSequencer.schedIn
    engineeringRateGroup.schedOut -> telemetryDatabase.schedIn
    rateGroupDriver.cycleOut -> engineeringRateGroup.cycleIn
  }

  connections Uplink {
    socketGroundInterface.comCmdOut -> commandDispatcher.comCmdIn
  }

}
----

*Example 2.*

[source,fpp]
----
@ Attitude control topology
topology AttitudeControl {

  # ----------------------------------------------------------------------
  # Imported topologies 
  # ----------------------------------------------------------------------

  import CDH

  # ----------------------------------------------------------------------
  # Public instances 
  # ----------------------------------------------------------------------

  instance acsRateGroup
  instance attitudeControl
  ...

  # ----------------------------------------------------------------------
  # Private instances 
  # ----------------------------------------------------------------------

  instance socketGroundInterface

  # ----------------------------------------------------------------------
  # Connection patterns
  # ----------------------------------------------------------------------

  command connections instance commandDispatcher
  event connections instance eventLogger
  time connections instance timeSource


  # ----------------------------------------------------------------------
  # Connection graphs
  # ----------------------------------------------------------------------

  connections AttitudeTelemetry {
    ...
  }

  connections Downlink {
    eventLogger.comOut -> socketGroundInterface.comEventIn
    telemetryDatabase.comOut -> socketGroundInterface.comTlmIn
  }

  connections EngineeringTelemetry {
    acsRateGroup.tlmOut -> engineeringTelemetrySplitter.tlmIn
    ...
  }

  connections RateGroups {
    acsRateGroup.schedOut -> attitudeControl.schedIn
  }

  connections Uplink {
    socketGroundInterface.comCmdOut -> commandDispatcher.comCmdIn
  }

}
----

*Example 3.*

[source,fpp]
----
@ Release topology
topology Release {

  # ----------------------------------------------------------------------
  # Imported topologies 
  # ----------------------------------------------------------------------

  import AttitudeControl
  import CDH
  import Communication
  ...

}
----

*Example 4.*

Here is one topology that can result from automatic numbering of ports
applied to topology `B` in the
<<Specifiers_Topology-Import-Specifiers_Example,example for topology import
specifiers>>:

[source,fpp]
----
topology B {

  instance a
  instance c
  instance d
  instance e
  instance f 

  connections C1 {
    a.p1[0] -> c.p[0]
    a.p1[1] -> d.p[0]
  }

  connections C2 {
    a.p2[0] -> e.p[0]
  }

  connections C3 {
    a.p3[0] -> f.p[0]
  }

}
----

In general, where there are multiple connections to a single port array, the 
exact assignment of indices is not specified by the automatic numbering 
algorithm.
Another valid topology would reverse the assignment of 0 and 1 to `a.p1 
pass:[->] c.p` and `a.p1 pass:[->] d.p`.

