=== Topology Template Definitions

A *topology template definition* defines a an F Prime template that
can parameterize <<Definitions_Topology-Definitions,topology definitions>>.
The pattern enables reuse across applications with similar use-cases.

Topology templates are essentially parameterized functions that generate
topology definitions.

==== Syntax

`topology`
<<Lexical-Elements_Identifiers,_identifier_>>
`(` _topology-parameter-sequence_ `)`
_[_ `implements` <<Scoping-of-Names_Qualified-Identifiers,_interface-ident>> _]_
`{` _topology-template-member-sequence_ `}`

The _identifier_ specifies the name of the topology template.

_topology-parameter-sequence_ is an
<<Template-Parameter-Lists,template parameter sequence>> in
which each element is a *parameter*, and
the the terminating punctuation is a comma.

The optional _interface-ident_ refers to a <<Definitions_Port-Interface-Definitions,
interface definition, _ID_>>. This optional clause is a compile-time check that
verify that this topology definition fully <<Interface-Binding,implements>> _ID_.

_topology-template-member-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is a *topology template member*,
and the terminating punctuation is a semicolon.
A topology template member is one of the following:

* A <<Specifiers_Component-Instance-Specifiers,component
instance specifier>>

* A <<Specifiers_Connection-Graph-Specifiers,connection graph specifier>>

* ??? **I don't this we want this** A <<Specifiers_Telemetry-Packet-Set-Specifiers,telemetry packet set specifier>> ???

* ??? **I don't this we want this** A <<Specifiers_Topology-Import-Specifiers,topology import specifier>> ???

* A <<Specifiers_Port-Export-Specifiers,topology port export specifier>>

* An <<Specifiers_Include-Specifiers,include specifier>>

* A <<Definitions_Component-Instance-Definitions,component instance definition>>

==== Semantics

Topology _template_ definitions differ from topology definitions in that they
cannot be resolved until they are instatiated inside a full topology.
Topology _template_ definitions include a set of parameters which are passed
concrete values when instantiating the template.

===== Template Instantiation

