#!/bin/sh -e

fpp_to_xml=../../../../../../bin/fpp-to-xml

echo '  removing old files'
./clean

dir=`cd ../..; echo $PWD`

echo '  generating XML'
$fpp_to_xml -p $dir -i ../../builtin.fpp ../../basic.fpp

echo '  generating C++'
for file in ActiveComponent PassiveComponent PPort
do
  fprime-codegen $file'Ai.xml' > /dev/null
done
for suffix in hpp cpp
do
  cp ../../BasicTopologyAc.ref.$suffix BasicTopologyAc.$suffix
done

echo '  compiling C++'
fprime-gcc -c BasicTopologyAc.cpp
