#!/bin/sh -e

fpp_to_cpp=../../../../../../bin/fpp-to-cpp

echo '  removing old files'
./clean

dir=`cd ../..; echo $PWD`

echo '  generating C++'
$fpp_to_cpp -p $dir -i ../../builtin.fpp ../../basic.fpp

for suffix in hpp cpp
do
  cp ../../BasicTopologyAc.ref.$suffix BasicTopologyAc.$suffix
done

echo '  compiling C++'
fprime-gcc -I.. -I../../../fprime -I../../../fprime/config -Wno-unused-parameter -Wno-unused-variable -c BasicTopologyAc.cpp
