#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_locate_uses=../../../bin/fpp-locate-uses

compare()
{
  outfile=$1
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_locate_uses $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  compare $outfile
}

. ./tests.sh

# Default tests
for t in $tests
do
  echo "
$t()
{
  run_test '' $t
}"
done > default-tests.sh
. ./default-tests.sh

uses()
{
  run_test '-i defs.fpp' 'uses/uses' uses
}

uses_dir()
{
  run_test '-d uses -i defs.fpp' 'uses/uses' uses_dir
}

stdin()
{
  $fpp_locate_uses -i defs.fpp < uses/uses.fpp > stdin.out.txt
  compare stdin
}

run_suite $tests
