#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_locate_uses=../../../bin/fpp-locate-uses

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_locate_uses $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

. ./tests.sh

# Default update ref
for t in $tests
do
  echo "
$t()
{
  update '' $t
}"
done > default-update-ref.sh
. ./default-update-ref.sh

uses()
{
  update '-i defs.fpp' 'uses/uses' uses
}

uses_dir()
{
  update '-d uses -i defs.fpp' 'uses/uses' uses_dir
}

stdin()
{
  $fpp_locate_uses -i defs.fpp < uses/uses.fpp > stdin.ref.txt
}

for t in $tests
do
  echo "updating ref output for $t"
  $t
done
