#!/bin/sh -e

export COMPILER_ROOT=$PWD/../../../..

skip_xml_names="
"

for name in $skip_xml_names
do
  export SKIP_XML_FOR_$name=1
done

skip_cpp_names="
CommandsComponent
EventsComponent
ParametersComponent
TelemetryComponent
"

for name in $skip_cpp_names
do
  export SKIP_CPP_FOR_$name=1
done

export FPRIME_GCC_FLAGS="-Wno-zero-length-array -Wno-vla-extension -Wno-sign-conversion"
sh ../scripts/check-xml.sh
