#!/bin/sh -e

. ../../../../scripts/utils.sh

clean
rm -f default-tests.sh default-update-ref.sh
for file in `find . -maxdepth 1 -name '*out.*' -or -name '*.names.txt' -or -name '*o' -or -name '*Ac.hpp' -or -name '*Ac.cpp'`
do
  rm $file
done
(cd check-cpp-dir; ./clean)
