// ======================================================================
// \title  NestedNamespacesTopologyAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for NestedNamespaces topology
//
// \copyright
// Copyright (c) 2021 California Institute of Technology.
// U.S. Government sponsorship acknowledged.
// All rights reserved.
// ======================================================================

#include "NestedNamespacesTopologyAc.hpp"

namespace A {

  namespace B {


    // ----------------------------------------------------------------------
    // Public interface functions
    // ----------------------------------------------------------------------

    void setup(const TopologyState& state) {

    }

    void teardown(const TopologyState& state) {

    }

  }

}
