#!/bin/sh

# ----------------------------------------------------------------------
# Compile ref C++ files, to check them for validity
# ----------------------------------------------------------------------

cd `dirname $0`

fprime_gcc=../../../../scripts/fprime-gcc

for file in `find . -name '*.ref.cpp'`
do
  base=`basename $file .ref.cpp`
  cp $base.ref.hpp $base.hpp
  cp $base.ref.cpp $base.cpp
  echo "compiling $base.cpp"
  for guards in "-DFW_ENABLE_TEXT_LOGGING=0 -DFW_SERIALIZABLE_TO_STRING=0" \
    "-DFW_ENABLE_TEXT_LOGGING=0 -DFW_SERIALIZABLE_TO_STRING=1" \
    "-DBUILD_UT -DFW_ENABLE_TEXT_LOGGING=0 -DFW_SERIALIZABLE_TO_STRING=1" \
    "-DFW_ENABLE_TEXT_LOGGING=1 -DFW_SERIALIZABLE_TO_STRING=1" \
    "-DBUILD_UT -DFW_ENABLE_TEXT_LOGGING=1 -DFW_SERIALIZABLE_TO_STRING=1"
  do
    echo "compiling $base.cpp with $guards"
    $fprime_gcc $guards -I../fprime -c $base.cpp
  done
done
