#!/bin/sh

# ----------------------------------------------------------------------
# Compile ref C++ files, to check them for validity
# ----------------------------------------------------------------------

cd `dirname $0`

fprime_gcc=../../../../scripts/fprime-gcc

for file in `find . -name '*.ref.cpp'`
do
  base=`basename $file .ref.cpp`
  cp $base.ref.hpp $base.hpp
  cp $base.ref.cpp $base.cpp
  echo "compiling $base.cpp"
  $fprime_gcc -I../fprime/config -c $base.cpp
done
