=== Initial Transition Specifiers

An *initial transition specifier* is part of a
<<Definitions_State-Machine-Definitions,state machine definition>>
or a
<<State-Machine-Behavior-Elements_State-Definitions,state definition>>.
It specifies an initial transition, i.e., a transition taken
when starting up a state machine or entering a state with
substates.

==== Syntax

`initial` 
<<State-Machine-Behavior-Elements_Transition-Expressions,_transition-expression_>>

==== Semantics

The state definition or junction definition referred to in the
transition expression must *lead to a member* of the same 
state machine definition or state definition in which the initial
transition specifier appears.

. A state definition _D_ leads to a member of a state machine definition _M_
(respectively a state _S_) if _D_ is a member of _M_ (respectively _S_).

. A junction definition _D_ leads to a member of a state machine definition _M_
(respectively as state _S_) if it is a member of _M_ (respectively _S_)
and the state or junction definitions referred to in _D_ lead to members of
_M_ (respectively _S_).

==== Examples

[source,fpp]
----
state machine Device {

  action initDev1
  action initDev2

  # When the state machine starts up, enter the ON state
  initial enter ON

  state ON {

    # When entering the ON state, enter the POWERING_UP substate
    initial do {
      initDev1
      initDev2
    } \
    enter POWERING_UP

    state POWERING_UP

  }

}
----
