=== State Transition Specifiers

A *state transition specifier* is part of a
<<State-Machine-Behavior-Elements_State-Definitions,state definition>>.
It specifies a transition from the state in which it appears.

==== Syntax

A state transition is one of the following:

* `on` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`if` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
<<State-Machine-Behavior-Elements_Enter-Expressions,_enter-expression_>>

* `on` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`if` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
`do` <<Lexical-Elements_Identifiers,_identifier_>>

==== Semantics

. The identifier after the keyword `on` must
<<Definitions_State-Machine-Definitions_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_State-Machine-Signal-Definitions,state machine signal definition>>.
It names the signal that causes the transition to occur.

. If present, the optional identifier after the keyword `if` must
<<Definitions_State-Machine-Definitions_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_Guard-Definitions,guard definition>>.
It specifies a guard for the transition.

. The first form of the syntax specifies a target state and an optional action.
The enter expression must be valid.
The target state in the enter expression may be the same as the
enclosing state; in this case the transition is called a *self transition*.
When making a self transition, the state machine runs the code associated with
exiting and then re-entering the state.

. Second form of the syntax specifies an
*internal transition*, i.e., an action to take while remaining
in the same state.
When making an internal transition, the exit and re-entry code is not run.
The identifier after the keyword `do` must
<<Definitions_State-Machine-Definitions_Scoping-of-Names,refer>>
to an
<<State-Machine-Behavior-Elements_Action-Definitions,action definition>>.

==== Examples

[source,fpp]
----
state machine Device {

  signal RTI
  signal PowerOn
  
  action performStuff
  action getReady

  guard initComplete

  initial OFF

  state OFF {
    on PowerOn if initComplete do getReady enter ON
  }

  state ON {
    on RTI do performStuff
  }

}
----
