=== State Transition Specifiers

A *state transition specifier* is part of a
<<State-Machine-Behavior-Elements_State-Definitions,state definition>>.
It specifies a transition from the state in which it appears.

==== Syntax

`on` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`if` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
_transition-or-do_

_transition-or-do_ is one of the following:

.  <<State-Machine-Behavior-Elements_Transition-Expressions,_transition-expression_>>

.  <<State-Machine-Behavior-Elements_Do-Expressions,_do-expression_>>

==== Semantics

. The identifier after the keyword `on` must
<<Definitions_State-Machine-Definitions_Semantics_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_Signal-Definitions,signal definition>>.
It names the signal that causes the transition to occur.

. If present, the optional identifier after the keyword `if` must
<<Definitions_State-Machine-Definitions_Semantics_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_Guard-Definitions,guard definition>>.
It specifies a guard for the transition.

. The first form of the _transition-or-do_ syntax specifies an *external
transition*, i.e., an optional list of actions and a target state or junction.

. The second form of the _transition-or-do_ syntax specifies an
*internal transition*, i.e., a list of actions to take while remaining
in the same state.
The do expression must be valid.

. Let _S_ be the enclosing state of a state transition specifier _T_.

.. If _S_ is a leaf state, then _T_ specifies an external or internal
transition with source _S_.

.. Otherwise _T_ specifies one external or internal transition with source _S~i~_ 
for each leaf state _S~i~_ that is transitively contained _S_.

. An external transition whose source is a leaf state _S_ is called a
*self transition* if the target is a state _S'_, and one of the following is true:

..  _S = S'_; or

.. _S_ is a transitive substate of _S'_.

+
Each self transition has an associated *outer state*.
In case (a), the outer state is the source state, which is also the
target state.
In case (b), the outer state is the target state.
When a self transition occurs the state machine runs the exit actions
for the outer state just before running the actions (if any)
specified in the transition; and it runs the entry actions for the
outer state just after running the actions (if any) specified
in the transition.

==== Examples

[source,fpp]
----
state machine Device {

  action performStuff
  action powerHeater
  action powerSensor

  guard initComplete

  signal PowerOn
  signal RTI
  
  initial enter OFF

  state OFF {
    on PowerOn if initComplete do {
      powerHeater
      powerSensor
    } \
    enter ON
  }

  state ON {
    on RTI do { performStuff }
  }

}
----
