=== State Machine Event Definitions

A *state machine event definition* is part of a
<<Definitions_State-Machine-Definitions,state machine definition>>.
It defines an event that may be sent to the enclosing state machine.
Events are inputs to state machines that cause state transitions
to occur.

Events can be external or internal.
An external event is sent to the state machine from outside,
e.g., by a command to an F Prime component.
An internal event is sent by the state machine implementation
to itself.

All events sent to a state machine (internal and external)
are placed on a first-in first-out (FIFO) queue.
The state machine dequeues and processes events when it is
visiting a state, and after it has run the entry function
for that state.

==== Syntax
`event`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`:` 
<<Type-Names,_type-name_>>
_]_

==== Semantics

. The identifier specifies the event name.

. If present, the optional type name specifies the type of the
data carried by the event.
If _type-name_ is not present, then the event carries no data.

==== Examples

[source,fpp]
----
struct FaultData {
  id: U32
  data: U32
}

@ A state machine with event definitions
state machine EventDefs {

  @ An event without data
  event RTI

  @ An event with data
  event Fault: FaultData

  ...

}
----
