=== State Transition Specifiers

A *state transition specifier* is part of a
<<State-Machine-Behavior-Elements_State-Definitions,state definition>>.
It specifies a transition from the state in which it appears.

==== Syntax

`on` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`if` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
_transition-or-do_

_transition-or-do_ is one of the following:

.  <<State-Machine-Behavior-Elements_Transition-Expressions,_transition-expression_>>

.  <<State-Machine-Behavior-Elements_Do-Expressions,_do-expression_>>

==== Semantics

. The identifier after the keyword `on` must
<<Definitions_State-Machine-Definitions_Semantics_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_Signal-Definitions,signal definition>>.
It names the signal that causes the transition to occur.

. If present, the optional identifier after the keyword `if` must
<<Definitions_State-Machine-Definitions_Semantics_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_Guard-Definitions,guard definition>>.
It specifies a guard for the transition.

. The first form of the _transition-or-do_ syntax specifies an *external
transition*, i.e., an optional list of actions and a target state or junction.

. The second form of the _transition-or-do_ syntax specifies an
*internal transition*, i.e., a list of actions to take while remaining
in the same state.
When making an internal transition, the exit and entry code is not run.
The do expression must be valid.

. In any of the following cases of an external transition to a state target,
the transition is called a *self transition*:

..  The target is the same as the enclosing state.

.. The target is a transitive substate of the enclosing state.

.. The enclosing state is a transitive substate of the target.

+
Each self transition has an associated *outer state*.
In case 1, the outer state is the target state, which is also
the enclosing state.
In case 2, the outer state is the enclosing state.
In case 3, the outer state is the target state.
When making a self transition, the state machine runs the code associated with
exiting and then reentering the outer state.

==== Examples

[source,fpp]
----
state machine Device {

  action performStuff
  action powerHeater
  action powerSensor

  guard initComplete

  signal PowerOn
  signal RTI
  
  initial enter OFF

  state OFF {
    on PowerOn if initComplete do {
      powerHeater
      powerSensor
    } \
    enter ON
  }

  state ON {
    on RTI do { performStuff }
  }

}
----
