=== State Transition Specifiers

A *state transition specifier* is part of a
<<State-Machine-Behavior-Elements_State-Definitions,state definition>>.
It specifies a transition from the state in which it appears.

==== Syntax

`on` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`if` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
_transition-or-do_

_transition-or-do_ is one of the following:

.  <<State-Machine-Behavior-Elements_Transition-Expressions,_transition-expression_>>

.  <<State-Machine-Behavior-Elements_Do-Expressions,_do-expression_>>

==== Static Semantics

. The identifier after the keyword `on` must
<<Definitions_State-Machine-Definitions_Static-Semantics_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_Signal-Definitions,signal definition>>.
It names the signal that causes the transition to occur.

. If present, the optional identifier after the keyword `if` must
<<Definitions_State-Machine-Definitions_Static-Semantics_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_Guard-Definitions,guard definition>>.
It specifies a guard for the transition.

. The first form of the _transition-or-do_ syntax specifies an *external
transition*, i.e., an optional list of actions and a target state or choice.

. The second form of the _transition-or-do_ syntax specifies an
*internal transition*, i.e., a list of actions to take while remaining
in the same state.
The do expression must be valid.

==== The State Transition Map

The set of all state transition specifiers in a state machine
induces a *state transition map* _m: Signal x State -> GuardedTransition_,
where a guarded transition is a pair consisting of an optional guard
and a transition or do expression.
The map _m_ is constructed as follows.
Let _T_ be a state transition specifier with signal _s_, optional guard _g_,
and transition or do expression _t_, defined in state _S_.

. If _S_ is a leaf state, then _m_ maps _(s, S)_ to _(g, t)_.

. Otherwise, for each leaf state _S~i~_ that is transitively
contained in _S_, _m_ maps _(s, S~i~)_ to _(g, t)_, unless
the mapping is overridden.
Overriding occurs when another state _S'_ that is transitively contained in _S_
maps _(s, S~i~)_ to _(g',t')_ according to items (1) or (2).
In that case, the mapping lower in the hierarchy takes precedence.
This overriding behavior is called *behavioral polymorphism*.

==== Dynamic Semantics

Let _M_ be a state machine.
Suppose _M_ is in state _S_.
Let _m_ be the state transition map of _M_, defined in the previous section.
Let _s_ be a signal of _M_.
*Sending* signal _s_ to _M_ results in the following behavior:

. If _(s,S)_ is not in the domain of _m_, then do nothing.

. Otherwise

.. Let _(g,t) =  m(s,S)_.

.. Evaluate the guard _g_.
If the result is `false`, then do nothing.
Otherwise

... If _t_ is a do expression _E_, then perform the actions
listed in _E_, if any, in the order listed.

... Otherwise _t_ is a transition expression _E_.
<<State-Machine-Behavior-Elements_Transition-Expressions_Dynamic-Semantics,
Run _E_ in the context of _S_>>.

If any of the guard, do expression, or transition expression requires a
typed argument _v_, then according to the static semantics, _v_ must
be available, and it must have a compatible type.
Use _v_ to evaluate the guard, run the do expression, or run
the transition expression.

==== Examples

[source,fpp]
----
state machine Device {

  action performStuff
  action powerHeater
  action powerSensor

  guard initComplete

  signal PowerOn
  signal RTI

  initial enter OFF

  state OFF {
    on PowerOn if initComplete do {
      powerHeater
      powerSensor
    } \
    enter ON
  }

  state ON {
    on RTI do { performStuff }
  }

}
----
