=== Transition Expressions

An *transition expression* specifies a transition as part of an
<<State-Machine-Behavior-Elements_Initial-Transition-Specifiers,initial transition>>,
a <<State-Machine-Behavior-Elements_State-Transition-Specifiers,state transition>>,
or
a <<State-Machine-Behavior-Elements_Choice-Definitions,choice>>.
The transition performs zero or more actions and then
enters a state or choice.

==== Syntax

_[_
<<State-Machine-Behavior-Elements_Do-Expressions,_do-expression_>>
_]_
`enter` <<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>


==== Static Semantics

. The do expression specifies the list of actions to be
performed when making the transition.
If there are no actions, the do expression may be omitted.

. The qualified identifier after the keyword `enter` must
<<Definitions_State-Machine-Definitions_Static-Semantics_Scoping-of-Names,refer>>
to a
<<State-Machine-Behavior-Elements_State-Definitions,state definition>>
or a
<<State-Machine-Behavior-Elements_Choice-Definitions,choice definition>>
It is the state or choice that is entered in the transition.

==== Dynamic Semantics

A transition expression _E_ is run in the context of an
initial transition specifier, a leaf state definition,
or a choice definition.

. To run _E_ in the context of an initial transition specifier
_I_, do the following:

.. Perform the actions, if any, specified in _E_, in the order specified.

.. Run the entry behavior of the
<<State-Machine-Behavior-Elements_State-Definitions_Dynamic-Semantics,state>>
or
<<State-Machine-Behavior-Elements_Choice-Definitions_Dynamic-Semantics,choice>>
referred to in _E_.

+
According to the static semantics, actions and the entry behavior must not require
a typed argument.

. To run _E_ in the context of a leaf state definition or choice definition _D_,
do the following:

.. Let _T_ be the state or choice which is the target of _E_.

.. Let _P_ be the *lowest common ancestor* of _D_ and _T_.
The lowest common ancestor is defined as follows:

... A *point in the state hierarchy* is either the entire state machine
or a state definition.

... The lowest common ancestor of _D_ and _T_ is the lowest
point in the state hierarchy such that (A)
by descending from _P_ at least once it is possible to reach _D_ and (B)
by descending from _P_ at least once it is possible to reach _T_.

.. Ascend through the state hierarchy from _D_ to _P_.
When passing out of a state _S_, perform the
<<State-Machine-Behavior-Elements_State-Definitions_Static-Semantics,
exit actions>> of _S_, in the order specified.

.. Perform the actions, if any, specified in _E_, in the order specified.

.. Descend through the state hierarchy from _P_ to the point just above _T_.
When passing into a state _S_, perform the
<<State-Machine-Behavior-Elements_State-Definitions_Static-Semantics,
entry actions>> of _S_, in the order specified.

.. Run the entry behavior of the
<<State-Machine-Behavior-Elements_State-Definitions_Dynamic-Semantics,state>>
or
<<State-Machine-Behavior-Elements_Choice-Definitions_Dynamic-Semantics,choice>>
_T_.

+
According to the static semantics, if any of the actions or the
entry behavior requires a typed argument _v_, then _v_ must
be available, and it must have a compatible type.
Use _v_ to call the action or run the behavior.

==== Examples

[source,fpp]
----
state machine Device {

  action initDev1
  action initDev2

  initial do {
    initDev1
    initDev2
  } \
  enter OFF

  state OFF

}
----
