#!/bin/sh

cd `dirname $0`

fprime_gcc=../../../../../scripts/fprime-gcc
export FPRIME_GCC_FLAGS="-I../../fprime"
warning_flags="
-Wno-gnu-zero-variadic-macro-arguments
-Wno-return-type
-Wno-sign-conversion
-Wno-unused-parameter
"
include_flags="
-I$FPRIME/gtest/googletest-src/googletest/include
-I..
-I../../../..
-I../base
-I../impl
-I../test-base
"
define_flags="-DPROTECTED="public" -DBUILD_UT=1"

../../fprime/generate_cpp

# Generate headers in base and test-base
for dir in base test-base
do
  echo "running the tests in ../$dir to generate the header files"
  (cd ../$dir; ./run)
done

echo "copying base headers to test-base"
cp ../base/*Ac.hpp ../test-base

# Generate impl headers in impl
(cd ../impl; ../gen_ref_headers)

# Generate header files
../gen_ref_headers

# Compile cpp files
for file in `find . -name '*.ref.cpp' | sort`
do
  base=`basename $file .ref.cpp`
  cp $file $base.cpp
  echo "compiling $base.cpp"
  $fprime_gcc $include_flags -c $define_flags $warning_flags $base.cpp
done
