#!/bin/sh

# ----------------------------------------------------------------------
# Compile ref C++ files, to check them for validity
# ----------------------------------------------------------------------

fprime_gcc=../../../../../scripts/fprime-gcc
export FPRIME_GCC_FLAGS="-I../../fprime"
warning_flags="-Wno-gnu-zero-variadic-macro-arguments -Wno-unused-parameter -Wno-return-type"
include_flags="-I../../../.. -I../base -I../impl -I../test -I.. -I$FPRIME/gtest/googletest-src/googletest/include"
define_flags="-DPROTECTED="public" -DBUILD_UT=1"

. ../generate_cpp.sh

for file in `find . -name '*.ref.cpp'`
do
  echo "compiling $file"
  base=`echo $file | sed 's;\.ref.cpp;;'`
  if [[ "$file" =~ .*Tester.ref.cpp ]]
  then
    cp ${base}.ref.hpp ${base}.hpp
  fi
  cp ${base}.ref.cpp ${base}.cpp
  $fprime_gcc $include_flags -c ${base}.cpp $define_flags $warning_flags
done
