// ======================================================================
// \title  PassiveParamsTestMain.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PassiveParams component test harness implementation class
// ======================================================================

#include "PassiveParamsTester.hpp"

TEST(Nominal, toDo) {
  PassiveParamsTester tester;
  tester.toDo();
}

int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
