// ======================================================================
// \title  PassiveGetProductPortsOnlyTestMain.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PassiveGetProductPortsOnly component test harness implementation class
// ======================================================================

#include "PassiveGetProductPortsOnlyTester.hpp"

TEST(Nominal, toDo) {
  PassiveGetProductPortsOnlyTester tester;
  tester.toDo();
}

int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
