// ======================================================================
// \title  PassiveSyncProductsTestMain.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PassiveSyncProducts component test harness implementation class
// ======================================================================

#include "PassiveSyncProductsTester.hpp"

TEST(Nominal, toDo) {
  PassiveSyncProductsTester tester;
  tester.toDo();
}

int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
