// ======================================================================
// \title  PassiveSyncRecordsOnlyTester.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PassiveSyncRecordsOnly component test harness implementation class
// ======================================================================

#include "PassiveSyncRecordsOnlyTester.hpp"

// ----------------------------------------------------------------------
// Construction and destruction
// ----------------------------------------------------------------------

PassiveSyncRecordsOnlyTester ::
  PassiveSyncRecordsOnlyTester() :
    PassiveSyncRecordsOnlyGTestBase("PassiveSyncRecordsOnlyTester", PassiveSyncRecordsOnlyTester::MAX_HISTORY_SIZE),
    component("PassiveSyncRecordsOnly")
{
  this->initComponents();
  this->connectPorts();
}

PassiveSyncRecordsOnlyTester ::
  ~PassiveSyncRecordsOnlyTester()
{

}

// ----------------------------------------------------------------------
// Tests
// ----------------------------------------------------------------------

void PassiveSyncRecordsOnlyTester ::
  toDo()
{
  // TODO
}
