// ======================================================================
// \title  QueuedParamsTestMain.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for QueuedParams component test harness implementation class
// ======================================================================

#include "QueuedParamsTester.hpp"

TEST(Nominal, toDo) {
  QueuedParamsTester tester;
  tester.toDo();
}

int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
