#!/bin/sh -e

fpp_syntax=../../../../bin/fpp-syntax

skip="|internal_ports"

files=`find . -name '*.ref.txt' | egrep -v "error|missing$skip"`
for file in $files
do
  echo "checking $file"
  $fpp_syntax < $file
done
