=== String Literals

A *string literal expression* is a single-line string literal
or a multiline string literal.
In this section

* *Literal string* means a literal string appearing
in the FPP source text.

* *Interpreted string* means the sequence
of characters represented by the literal string.

* *String interpretation* is the process of converting a literal
string to an interpreted string.

==== Single-Line String Literals

A *single-line string literal* is a sequence of characters enclosed in double
quote characters `"`.
Inside a single-line string literal

* The newline character is not allowed.

* The literal double quote character `"` is not allowed.

For any single-line string literal _s_, the
corresponding interpreted string _s'_
is identical to _s_, except that any character sequence `\q` in _s_
becomes a double quote character `"` in _s'_.

*Examples:*

* `"abc"` is a valid string consisting of the characters `a`, `b`, and `c`.

* `"ab\q"` is a valid string consisting of the characters `a`, `b`, and `"`.

* `"abc` is not a valid string, because it is missing the terminating double quote.

* `"ab"c"` is the valid string `"ab"` followed by the identifier `c` and an
unmatched double quote character.

==== Multiline String Literals

A *multiline string literal* is a sequence of characters enclosed in triple double
quotes `"""`.
Inside a multiline string literal

* The newline character is allowed.

* The literal double quote character `"` is allowed, except no
sequence of three such characters in a row is allowed.

For any multiline string literal _s_, the corresponding interpreted string _s'_
is identical to _s_ except that any character sequence `\q` in _s_
becomes a double quote character `"` in _s'_.
In particular, you can include a sequence of three double quote
characters in _s'_ string by writing at least one of
those characters as `\q` in _s_.

Whitespace inside a multiline string literal is trimmed as follows:

* The first newline after the first `"""` (if it exists) is omitted
from the interpreted string.

* Any whitespace occurring in columns to the left of the first `"""`
is omitted from the interpreted string.

*Example:*

[source,fpp]
----
  """
  // This is a multiline string literal
  // It represents some C++ code
  instance.create(0, 1);
  """
----

The interpreted string consists of the following lines, each terminated by a newline:

. `// This is a multiline string literal`
. `// It represents some C++ code`
. `instance.create(0, 1);`

