#!/bin/sh -e

# ----------------------------------------------------------------------
# Generate framework C++
# ----------------------------------------------------------------------

cd `dirname $0`

echo "generating framework C++"

fpp_files=`find . -name '*.fpp'`
../../../../bin/fpp-to-cpp -p $PWD $fpp_files

# Move config files into place
for base in FppConstantsAc ProcTypeEnumAc
do
  for suffix in hpp cpp
  do
    mv $base.$suffix config
  done
done

# Move Fw aliases (FpConfig.h dependencies) into config
fp_config_aliases="
FwChanIdType
FwDpIdType
FwDpPriorityType
FwEnumStoreType
FwEventIdType
FwOpcodeType
FwPacketDescriptorType
FwPrmIdType
FwSizeStoreType
FwSizeType
FwTimeBaseStoreType
FwTimeContextStoreType
FwTlmPacketizeIdType
FwTraceIdType
"

for base in ${fp_config_aliases}
do
  for suffix in hpp h
  do
    mv ${base}AliasAc.$suffix config
  done
done

# Move files into place by name prefix
for dir in Buffer Cmd Dp Log Prm Time Tlm
do
  mv $dir*.hpp $dir*.cpp Fw/$dir
done
mv Param*.hpp Param*.cpp Fw/Prm
mv Sched*.hpp Sched*.cpp Svc/Sched

# Remaining files go into types
mv *.hpp *.cpp Fw/Types
