#!/bin/sh -e

# ----------------------------------------------------------------------
# Generate framework C++
# ----------------------------------------------------------------------

cd `dirname $0`

echo "generating framework C++"

fpp_files=`find . -name '*.fpp'`
../../../../bin/fpp-to-cpp -p $PWD $fpp_files

# Move config files into place
for base in FppConstantsAc ProcTypeEnumAc
do
  for suffix in hpp cpp
  do
    mv $base.$suffix config
  done
done

# Move definitions from FpConfig.fpp and PlatformTypes.fpp into config
fp_config_aliases="
FwAssertArgType
FwChanIdType
FwDpIdType
FwDpPriorityType
FwEnumStoreType
FwEventIdType
FwIdType
FwIndexType
FwOpcodeType
FwPacketDescriptorType
FwPrmIdType
FwQueuePriorityType
FwSignedSizeType
FwSizeStoreType
FwSizeType
FwTaskIdType
FwTaskPriorityType
FwTimeBaseStoreType
FwTimeContextStoreType
FwTlmPacketizeIdType
FwTraceIdType
"

fp_config_enums="
TimeBase
"

fp_platform_aliases="
PlatformAssertArgType
PlatformIndexType
PlatformQueuePriorityType
PlatformSignedSizeType
PlatformSizeType
PlatformTaskIdType
PlatformTaskPriorityType
"

for base in ${fp_config_aliases}
do
  for suffix in hpp h
  do
    mv ${base}AliasAc.$suffix config
  done
done

for base in ${fp_config_enums}
do
  for suffix in cpp hpp
  do
    mv ${base}EnumAc.$suffix config
  done
done

for base in ${fp_platform_aliases}
do
  for suffix in hpp h
  do
    mv ${base}AliasAc.$suffix Platform
  done
done

# Move files into place by name prefix
for dir in Buffer Cmd Dp Log Prm Time Tlm
do
  mv $dir*.hpp $dir*.cpp Fw/$dir
done
mv Param*.hpp Param*.cpp Fw/Prm
mv Sched*.hpp Sched*.cpp Svc/Sched

# Move config files into place
mv ApidEnum* config

# Remaining files go into types
mv *.hpp *.cpp Fw/Types
