// ======================================================================
// \title  ActiveAsyncProductPortsOnly.template.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ActiveAsyncProductPortsOnly component implementation class
// ======================================================================

#include "ActiveAsyncProductPortsOnly.hpp"
#include "FpConfig.hpp"

// ----------------------------------------------------------------------
// Component construction and destruction
// ----------------------------------------------------------------------

ActiveAsyncProductPortsOnly ::
  ActiveAsyncProductPortsOnly(const char* const compName) :
    ActiveAsyncProductPortsOnlyComponentBase(compName)
{

}

ActiveAsyncProductPortsOnly ::
  ~ActiveAsyncProductPortsOnly()
{

}
