#!/bin/sh -e

. ../../../../../scripts/utils.sh

clean
rm -f default-tests.sh default-update-ref.sh
for file in `find . -name '*out.*' \
  -or -name '*.names.txt' \
  -or -name '*o' \
  -or -name '*.cpp' \
  -or -name '*.hpp' \
  -or -name '*.cpp-template' -and -not -name '*.ref.cpp-template' \
  -or -name '*.hpp-template' -and -not -name '*.ref.hpp-template'`
do
  rm $file
done
