=== Namespace Definitions

A *namespace definition* provides a named scope that encloses other
definitions, including other namespace definitions.

==== Syntax

`namespace`
<<Detailed-Description_Identifiers,_identifier_>>
`{` _namespace-member-sequence_ `}`

_namespace-member-sequence_ is an
<<Detailed-Description_Element-Sequences,element sequence>> in 
which each element is any kind of 
<<Detailed-Description_Definitions,definition>>
except an enumerated constant definition,
and the terminating punctuation is a semicolon.
Syntactically, it is equivalent to a
<<Detailed-Description_Translation-Units,translation unit>>.

==== Semantics

A namespace definition _D_ qualifies the names of all the definitions
inside it with its own name. Inside _D_, you can refer to definitions in
_D_ by their unqualified name (the identifier appearing in the
definition) or by their qualified name. Outside _D_, you have to use the
qualified name. We say that the *scope* of the identifiers in the
definitions in _D_ is limited to the inside of _D_.

For further information about name scoping and qualification, see the
section on
<<Scoping-of-Names,Scoping of Names>>.

==== Example

[source,fpp]
----
namespace N {
  constant a = 0
  constant b = a # Inside N, we can refer to N.a as a
  constant c = N.a # We can also say N.a here
}
constant d = N.a # Outside N, we have to say N.a
constant e = a # Error: a is not in scope here
----
