== Definitions and Uses

=== Uses

A *use* is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> appearing in an
<<Expressions,expression>>
or a
<<Types,type>>
that refers to a
<<Definitions,definition>>
according to the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,scoping rules for names>>.

=== Use-Def Graph

The set of definitions and uses in a tnet model induces a directed
graph called the *use-def graph*. In this graph,

. The nodes are the definitions.

. There is an edge from each definition _d_ to the definitions 
stem:[d_1, ..., d_n] corresponding to the uses 
stem:[u_1, ..., u_n] appearing in _d_.

For example, in the code above, the use-def graph has two nodes `c1` and
`c2` and one edge `c2` stem:[rarr] `c1`.

In a legal tnet model, the use-def graph must be acyclic. For example,
this model is illegal:

[source,tnet]
----
constant a = b
constant b = a
----

This model is also illegal:

[source,tnet]
----
constant a = a
----

=== Order of Definitions and Uses

So long as the
<<Definitions-and-Uses_Use-Def-Graph,use-def graph>> is acyclic, there is no 
constraint either on the ordering of
definitions and uses within a
<<Translation-Units-and-Models,translation unit>>, 
or on the distribution of definitions and uses among translation
units. For example, if the definition `constant c = 0` appears anywhere
in any translation unit of a model _M_, then the use of `c` as a
constant value of type U8 is legal anywhere in any translation unit of
_M_. In particular, this model is legal:

[source,tnet]
----
constant b = a
constant a = 0
----

The model consisting of two translation units

[source,tnet]
----
constant b = a
----

and

[source,tnet]
----
constant a = 0
----

is also legal, and the order in which the units are presented to the
translator does not matter.
