== Evaluation

*Evaluation* is the process of transforming an <<Expressions,expression>> into 
a <<Evaluation_Values,value>>.
In FPP, all evaluation happens during
<<Translation,translation>>,
in resolving expressions to compile-time constant values.

=== Values

A *value* is one of the following:

* An integer value.

* A floating-point value.

Every value belongs to exactly one
<<Evaluation_Concrete-Types,concrete type>>, and the types partition the 
values.

==== Integer Values

An *integer value* is an ordinary (mathematical) integer value.
Its type is _Integer_.

==== Boolean Values

A *Boolean value* is one of the values `true` and `false`.
Its type is `bool`.


==== Floating-Point Values

A *floating-point value* is an IEEE floating-point value of 8-byte
width. Its type is `F64`.

=== Concrete Types

The *concrete types* are the types of values. A concrete type is
identical to a
<<Types,type
appearing in a FPP source program>>, except that
enum types are associated with their definitions, not
their uses. There is only one concrete type per definition.

=== Evaluating Expressions

Evaluation of expressions occurs as stated in the
<<Expressions,expression descriptions>>. Evaluation of integer
expressions occurs at type _Integer_, using enough bits to
represent the result without truncation or overflow.
Evaluation of floating-point expressions occurs using 64-bit arithmetic.
