== Lexical Elements

Before parsing an FPP model, the compiler converts the source
text into a list of **tokens**.
This process is called **lexing**.

A token is one of the following:

* A <<Lexical-Elements_Reserved-Words,reserved word>>.

* A <<Lexical-Elements_Symbols,symbol>>.

* An <<Lexical-Elements_Identifiers,identifier>>.

* An <<Expressions_Integer-Literals,integer literal>>.

* A <<Expressions_Floating-Point-Literals,floating-point literal>>.

* A <<Expressions_Boolean-Literals,Boolean literal>>.

* A <<Expressions_String-Literals,string literal>>.

* A <<Lexical-Elements_Newlines,newline token>>.

* A line of an <<Comments-and-Annotations_Annotations,annotation>>
beginning with `@` or `@<`.

=== Reserved Words

The following are reserved words in FPP.
They may not be used as identifiers.

----
F32
F64
I16
I32
I64
I8
U16
U32
U64
U8
array
at
baseid
bool
component
enum
false
import
instance
locate
module
port
string
struct
true
type
----

=== Symbols

The following sequences of characters are symbol tokens in FPP:

----
,
-
.
:
;
[
]
{
}
----

=== Identifiers

An *identifier* is an unqualified name
consisting of one or more characters. The first character
must be a letter or an underscore. Characters after the first character
may be letters, digits, and underscores.

**Examples:**

----
Identifier
MultiPartIdentifier
_identifier_
identifier
identifier_
multiPartIdentifier
multi_part_identifier
----

=== Newlines

The NL character (ASCII code 0x0A) is a token. Sequences of one or more 
newlines separate the elements of <<Element-Sequences,element sequences>>.

=== Comments

<<Comments,Comments>> are ignored during lexing.

=== Whitespace and Non-Printable Characters

Apart from <<Lexical-Elements_Newlines,newlines>>, the lexer treats whitespace 
as follows:

* Space characters are ignored, except to separate tokens.

* CR characters (ASCII code 0x0D) are ignored.

* No other whitespace or non-printable characters are allowed
outside of a comment or annotation.
In particular, the tab character may not appear
in an FPP model outside of a comment or annotation.

=== Line Continuations

The character `\`, when appearing before a newline, causes the newline to
be ignored. For example, this
```
constant a = \
  1
```
is equivalent to this:
```
constant a = 1 + 1
```

Note that the `\` character is required in this case.
For example, the following is not syntactically correct:
```
constant a = # Error
  1
```
The newline indicates the end of an element sequence, but
`constant a =` is not a valid element sequence.

The lexer ignores any space characters appearing between `\` and the next 
newline.
