== Lexical Elements

Before parsing an FPP program, the compiler converts the source
text into a list of **tokens**.
This process is called **lexing**.

A token is one of the following:

* A <<Lexical-Elements_Reserved-Words,reserved word>>.

* A <<Lexical-Elements_Symbols,symbol>>.

* An <<Lexical-Elements_Identifiers,identifier>>.

* An <<Expressions_Integer-Literals,integer literal>>.

* A <<Expressions_Floating-Point-Literals,floating-point literal>>.

* A <<Expressions_Boolean-Literals,Boolean literal>>.

* A <<Lexical-Elements_String-Literals,string literal>>.

* A <<Lexical-Elements_Newlines,newline character>>.

* A line of an <<Comments-and-Annotations_Annotations,annotation>>
beginning with `@` or `@<`.

=== Reserved Words

The following are reserved words in FPP.
They may not be used as identifiers.

----
F32
F64
I16
I32
I64
I8
U16
U32
U64
U8
array
bool
component
enum
false
import
locate
module
port
string
struct
true
type
----

=== Symbols

The following sequences of characters are symbol tokens in FPP:

----
,
-
.
:
;
[
]
{
}
----

=== Identifiers

An *identifier* is an unqualified name
consisting of one or more characters. The first character
must be a letter or an underscore. Characters after the first character
may be letters, digits, and underscores.

**Examples:**

----
Identifier
MultiPartIdentifier
_identifier_
identifier
identifier_
multiPartIdentifier
multi_part_identifier
----

=== String Literals

A *string literal* is a sequence of characters enclosed in double quotes.
The characters must be printable ASCII characters, and the double
quote character itself is not allowed.

*Examples:*

* `"abc"` is a valid string representing the characters `a`, `b`, and `c`.

* `"abc` is not a valid string, because it is missing the terminating double quote.

* `"ab"c"` is the valid string `"ab"` followed by the identifier `c` and an 
unmatched double quote character.

=== Newlines

The newline character is a token. Sequences of one or more newlines separate 
the elements of <<Element-Sequences,element sequences>>.

=== Comments

<<Comments,Comments>> are ignored during lexing.

=== Whitespace and Non-Printing Characters

Apart from <<Lexical-Elements_Newlines,newlines>>, the lexer treats whitespace 
as follows:

* Space characters are ignored, except to separate tokens.

* No other whitespace or non-printing characters are allowed
outside of a comment or annotation.
In particular, the tab character may not appear
in an FPP program outside of a comment or annotation.

=== Line Continuations

The character `\`, when appearing before a newline, causes the newline to
be ignored. For example, this
```
constant a = \
  1
```
is equivalent to this:
```
constant a = 1 + 1
```

Note that the `\` character is required in this case.
For example, the following is not syntactically correct:
```
constant a = # Error
  1
```
The newline indicates the end of an element sequence, but
`constant a =` is not a valid element sequence.

The lexer ignores any space characters appearing between `\` and the next 
newline.
