== Type Checking

In this section, we explain the rules used to assign types to
expressions. FPP is a statically typed language. That means the
following:

* Type checking of expressions occurs during 
<<Analysis-and-Translation_Analysis,analysis>>.

* If the type checking phase detects a violation of any of these rules,
then translation halts with an error message and does not produce any
code.

Each type represents a collection of
<<Evaluation_Values,values>>.
The type checking rules exist to ensure that whenever an expression of
type stem:[T] is <<Evaluation_Evaluating-Expressions,evaluated>>,
the result is a value of type stem:[T].

=== Internal Types

Internal types do not appear in FPP source models.
The compiler assigns these types to expressions during type checking.

==== Integer

The type _Integer_ represents all integer values, without regard
to bit width.

==== Integer Types

<<Type-Checking_Internal-Types_Integer,_Integer_>> together with the 
<<Types_Primitive-Types,primitive integer types>> are called
the *integer types*.

==== Numeric Types

<<Type-Checking_Internal-Types_Integer,_Integer_>> together with the 
<<Types_Primitive-Types,primitive numeric types>> are called
the *numeric types*.

==== Anonymous Array Types

The type _[_ _n_ _]_ <<Types,_type_>>, where _n_
is an integer, represents an array of _n_ elements,
each of type _type_.

==== Anonymous Struct Types

The type _{_ stem:[m_1] _:_ stem:[T_1, ...,] stem:[m_n] _:_ stem:[T_n] _}_
represents a struct with members stem:[m_i] _:_ stem:[T_i], for
stem:[i in [1,n\]].

=== Integer Literals

To type an
<<Expressions_Integer-Literals,integer
literal expression>>, the semantic analyzer does the following:

. Evaluate the expression to an unsigned integer value stem:[v].

. Check that stem:[v] can be represented in 64 or fewer bits. If not, throw
an error.

. Assign the type <<Type-Checking_Internal-Types_Integer,_Integer_>> to the expression.

**Examples:**

[source,fpp]
----
constant a = 0 # Type is Integer
constant b = 1 # Type is Integer
constant c = 256 # Type is Integer
constant d = 65536 # Type is Integer
constant e = 0x100000000 # Type is Integer
constant f = 0x10000000000000000 # Error; integer value is too large
----

=== Floating-Point Literals

The type of a
<<Expressions_Floating-Point-Literals,floating-point
literal expression>> is `F64`.

=== Boolean Literals

The type of a
<<Expressions_Boolean-Literals,boolean
literal expression>> is `bool`.

=== String Literals

The type of a
<<Expressions_String-Literals,string
literal expression>> is `string`.

=== Array Expressions

To type an
<<Expressions_Array-Expressions,array expression>>
`[` stem:[e_1] `,` stem:[...] `,` stem:[e_n] `]`,
the semantic analyzer does the following:

. For each stem:[i in [1,n]], compute the type stem:[T_i] of stem:[e_i].

. Compute the <<Type-Checking_Computing-a-Common-Type_Lists-of-Types,common type>>
stem:[T] of the list of types stem:[T_i].

. Assign the type _[_ stem:[n] _]_ stem:[T] to the expression.

=== Struct Expressions

To type a
<<Expressions_Struct-Expressions,struct expression>>
`{` stem:[m_1] `=` stem:[e_1] `,` stem:[...] `,` stem:[m_n] `=` stem:[e_n] `}`,
the semantic analyzer does the following:

. Check that the member names stem:[m_i] are distinct.

. For each stem:[i in [1,n]], compute the type stem:[T_i] of stem:[e_i].

. Assign the type _{_ stem:[m_1] _=_ stem:[T_1] _,_ stem:[...] _,_ stem:[m_n] _=_ stem:[T_n] _}_
to the expression.

=== Unary Minus

To type a
<<Expressions_Arithmetic-Expressions,unary
minus expression>> `-` stem:[e], the semantic analyzer does the following:

. Compute the type stem:[T] of stem:[e].

. If stem:[T] is a <<Numeric-Type,numeric type>>, then use stem:[T].

. Otherwise throw an error.

**Examples:**

[source,fpp]
----
constant b = -1.0 # Type is F64
constant c = -1 # Type is Integer
constant d = -c # Type is Integer
constant e = -0xFFFFFFFF # Type is Integer
constant f = -bool # Error
----

=== Identifier Expressions

To type an <<Expressions_Identifier-Expressions,identifier 
expression>> stem:[e], the semantic analyzer 
<<Scoping-of-Names_Resolution-of-Identifiers,resolves the identifier to a 
definition>> and uses the type given in the definition.

**Example:**

[source,fpp]
----
constant a = 42 # a is a constant with type Integer
constant b = a # The expression a refers to the constant a and has type Integer
----

=== Dot Expressions

To type a
<<Expressions_Dot-Expressions,dot
expression>> stem:[e] `.x`, the semantic analyzer does the following:

. If stem:[e]`.x` is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> that represents 
the use of a definition according to the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,rules
for resolving qualified identifiers>>, and the use is a valid
<<Expressions_Dot-Expressions,dot
expression>>, then use the type given in the definition.

. Otherwise stem:[e]`.x` is invalid. Throw an error.

**Example:**

[source,fpp]
----
module M { 
  constant a = 0 # The constant M.a has type Integer
}
constant b = M.a # Expression M.a represents a use of the definition M.a.
                 # Its type is Integer.
----

=== Type Conversion

We say that a type stem:[T_1] *may be converted to* another type stem:[T_2] if
every <<Evaluation_Values,value>> represented by type stem:[T_1] can be
<<Evaluation_Type-Conversion,converted>> into a value of type stem:[T_2].

Here are the rules for type conversion:

. Any <<Type-Checking_Internal-Types_Numeric-Types,numeric
type>> may be converted to any other numeric type.

. An <<Types_Enum-Types,enum type>> may be converted to a
<<Type-Checking_Internal-Types_Numeric-Types,numeric type>>.

. An anonymous array type stem:[T_1 =] _[_ stem:[n] _]_ stem:[T'_1]
may be converted to the anonymous array type
stem:[T_2 =] _[_ stem:[m] _]_ stem:[T'_2]
if stem:[n = m] and stem:[T'_1] may be converted to stem:[T'_2].

. An anonymous array type stem:[T_1 =] _[_ stem:[n] _]_ stem:[T'_1]
may be converted to the array type stem:[T_2] if the number
of elements and the member types are the same for the two types.

. An anonymous struct type stem:[T =]_{_ stem:[m_1] _:_ stem:[T_1] _,_ 
stem:[...] _,_ stem:[m_1] _:_ stem:[T_n] _}_ may be converted to
the anonymous struct type stem:[T'] if for each stem:[i in [1,n\]],

.. stem:[m_i] _:_ stem:[T'_i] is a member of stem:[T']; and

.. stem:[T_i] may be converted to stem:[T'_i].

. An anonymous struct type stem:[T =]_{_ stem:[m_1] _:_ stem:[T_1] _,_ 
stem:[...] _,_ stem:[m_1] _:_ stem:[T_n] _}_ may be converted to
the struct type stem:[T'] if the sets of members in the two types are identical.

. A <<Types_Primitive-Types,primitive type>> type stem:[T_1] may be converted 
to an
<<Types_Array-Types,array type>> stem:[T_2] if
stem:[T_1] may be converted to the member type of stem:[T_2].

. A <<Types_Primitive-Types,primitive type>> type stem:[T] may be converted 
to a
<<Types_Structure-Types,structure type>> stem:[T'] if
for each member stem:[m_i] `:` stem:[T_i] of stem:[T'],
stem:[T] may be converted to stem:[T_i].

. Type convertibility is transitive: if stem:[T_1] may be converted to 
stem:[T_2]
and stem:[T_2] may be converted to stem:[T_3], then stem:[T_1] 
may be converted to stem:[T_3].

=== Computing a Common Type

==== Pairs of Types

Here are the rules for resolving two types stem:[T_1] and stem:[T_2] 
(e.g., the
types of two subexpressions) to a common type stem:[T] (e.g., the type of 
the whole expression):

. If stem:[T_1] and stem:[T_2] are the same type, then let 
stem:[T] be stem:[T_1].

. Otherwise if stem:[T_1] and stem:[T_2] are both
<<Type-Checking_Numeric-Types,numeric types>>, then do the following:

.. If stem:[T_1] and stem:[T_2] are both floating-point types, then use `F64`.

.. Otherwise use <<Type-Checking_Integer,_Integer_>>.

. Otherwise if stem:[T_1] or stem:[T_2] is an enum type stem:[T], then replace 
the enum type with the representation type specified in the definition of stem:[T]
and reapply these rules.

. Otherwise if one of stem:[T_1] and stem:[T_2] is an anonymous array type
stem:[T] and the other is an array type stem:[T'], and stem:[T]
may be converted to stem:[T'], then use stem:[T'].

. Otherwise if stem:[T_1] and stem:[T_2] are anonymous array types with the same size stem:[n]
and member types stem:[T'_1] and stem:[T'_2], then apply these rules to resolve
stem:[T'_1] and stem:[T'_2] to stem:[T'] and let stem:[T] be _[_ stem:[n] _]_ stem:[T'].

. Otherwise if one of stem:[T_1] and stem:[T_2] is an anonymous structure type
stem:[T] and the other is a structure type stem:[T'], and stem:[T]
may be converted to stem:[T'], then use stem:[T'].

. Otherwise if stem:[T_1] and stem:[T_2] are both anonymous structure types, then use
the anonymous structure type stem:[T] with the following members:

.. For each member stem:[m_1] _:_ stem:[T'_1] of stem:[T_1],
if stem:[T_2] has a member stem:[m_1] _:_ stem:[T'_2], then apply these rules
to convert stem:[T'_1] and stem:[T'_2] to a common type stem:[T'] and
use stem:[m_1] _:_ stem:[T']. Otherwise use stem:[m_1] _:_ stem:[T'_1].

.. For each member stem:[m_2] _:_ stem:[T'_2] of stem:[T_2],
if stem:[T_1] has a member stem:[m_2] _:_ stem:[T'_1], then apply these rules
to convert stem:[T'_2] and stem:[T'_1] to a common type stem:[T'] and
use stem:[m_2] _:_ stem:[T']. Otherwise use stem:[m_2] _:_ stem:[T'_2].

. Otherwise if one of stem:[T_1] and stem:[T_2] is a primitive type 
and the other
one is an anonymous array type _[_ stem:[n] _]_ stem:[T'], then apply these 
rules to resolve
the primitive type and stem:[T'] to a common type stem:[T'']. Let 
stem:[T] be the
array type _[_ stem:[n] _]_ stem:[T''].

. Otherwise if one of stem:[T_1] and stem:[T_2] is a primitive type 
and the other
one is an array type stem:[A], and the primitive type
may be converted to the member type of stem:[A], then use stem:[A].

. Otherwise if one of stem:[T_1] and stem:[T_2] is a primitive type and the 
other
one is an anonymous structure type stem:[S], then apply these rules to resolve 
the
primitive type and each of the structure member types to a common type.
Let stem:[T] be the structure type whose member names are the member names of 
stem:[S] and
whose member types are the corresponding common types.

. Otherwise if one of stem:[T_1] and stem:[T_2] is a primitive type 
and the other
one is a structure type stem:[S], and the primitive type
may be converted to each of the member types of stem:[S], then use stem:[S].

. Otherwise the attempted resolution is invalid. Throw an error.

==== Lists of Types

To compute a common type for a list of types
stem:[T_1, ... , T_n], do the following:

.  Check that stem:[n > 0]. If not, then throw an error.

.  Compute the type stem:[T_1] of stem:[e_1].

.  For each stem:[i in [2,n]]

   ..  Compute the type stem:[T] of stem:[e_i].

   ..  Compute the <<Type-Checking_Computing-a-Common-Type,common type>>
stem:[T_i] of stem:[T_(i-1)] and stem:[T].

.  Use stem:[T_n] as the common type of the list.
