== Types

=== Primitive Integer Types

*Primitive integer types* are the types of the primitive integer values supported
by F Prime. There are two kinds of primitive
integer types: unsigned integer types and signed integer types.

* The unsigned integer types are `U8`, `U16`, `U32`, and `U64`. The `U`
stands for "`unsigned.`" The number after the U is the width of the
representation in bits, using the standard binary representation of an
unsigned integer.

* The unsigned integer types are `I8`, `I16`, `I32`, and `I64`. The `I`
stands for "`[signed] integer.`" The number after the I is the width of
the representation in bits, using the standard binary two's complement
representation of a signed integer.

=== Floating-Point Types

The floating-point types are `F32` and `F64`. These are IEEE
floating-point values of width 32 and 64 bits, respectively.

=== Primitive Numeric Types

The <<Types_Primitive-Integer-Types,primitive integer types>>
together with the <<Types_Floating-Point-Types,floating-point types>> are 
called the *primitive numeric types*.

=== The Boolean Type

The type is `bool` represents the two Boolean values `true` and `false`.

=== Primitive Types

Together, the <<Types_Primitive-Numeric-Types,primitive numeric types>>
and the
<<Types_The-Boolean-Type,Boolean type>>
are called the *primitive types*.


=== The String Type

The type `string` is the type of string values.

=== Array Types

An *array type* is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> that 
refers to an
<<Definitions_Array-Type-Definitions,array type definition>> via the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,rules for name 
scoping>>. For example:

[source,fpp]
----
module M {
  array type A = [3] U8
}
array type B = [3] M.A # M.A is an array type
----

=== Enum Types

An *enum type* is a
<<Scoping-of-Names_Qualified-Identifiers,qualified
identifier>> that refers to an
<<Definitions_Enum-Definitions,enum definition>> via the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,rules
for name scoping>>. For example:

[source,fpp]
----
module M {
  enum E { X = 0, Y = 1 }
}
constant a = M.E.X # a has type M.E
----

`M.E` is an enum type.

=== Struct Types

A *struct type* is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> that 
refers to a
<<Definitions_Struct-Type-Definitions,struct type definition>> via the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,rules for name 
scoping>>. For example:

[source,fpp]
----
module M {
  struct type S = {
    x : U32
    y : F32
  }
}
struct type T = {
  s : M.S # M.S is a struct type
}
----

=== Abstract Types

An *abstract type* is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> that refers to 
an
<<Definitions_Abstract-Type-Definitions,abstract type 
definition>> via the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,rules for name 
scoping>>. For example:

[source,fpp]
----
module M {
  abstract type A
}
# A is an array of 3 M.A
# M.A is an abstract type
array A = [3] M.A
----

=== Default Values

Every type _T_ in FPP has an associated *default 
value*.
In generated C++ code, this is the value that is used to initialize a variable 
of type _T_
when no other initializer is specified.
Default values are important, because they ensure that in generated code,
every variable is initialized when it is created.

* The default value associated with each 
<<Types_Primitive-Numeric-Types,primitive numeric type>> is zero.

* The default value associated with
<<Types_The-Boolean-Type,`bool`>> is `false`.

* The default value associated with
<<Types_The-String-Type,`string`>> is the empty string.

* The default value associated with an
<<Types_Array-Types,array type>> _T_ is (1)
the default value specified in the definition of the type,
if one is given; otherwise (2) the unique value
of type _T_ that has the default value of the member type
of _T_ at each member.
See the section on <<Definitions_Array-Type-Definitions,
array type definitions>> for examples.

* The default value associated with an
<<Types_Enum-Types,enum type>> is the first
enumerated constant appearing in the enum definition.

* The default value associated with a
<<Types_Struct-Types,struct type>> _T_ is (1)
the default value specified in the definition of the type,
if one is given; otherwise (2) the unique value of type
_T_ that has the default value of the member type stem:[T_i]
for each member stem:[m_i] `:` stem:[T_i] of _T_.
See the section on <<Definitions_Struct-Type-Definitions,
struct type definitions>> for examples.

* The default value associated with an
<<Types_Abstract-Type,abstract type>> _T_ is not specified
in FPP.
It is up to the implementer of _T_ to provide a default value.

