# ----------------------------------------------------------------------
# General ports
# ----------------------------------------------------------------------

@ A typed sync input port
sync input port typedSync: [3] Typed

@ A typed guarded input
guarded input port typedGuarded: Typed

@ A typed output port
output port typedOut: Typed

@ A serial sync input port
sync input port serialSync: serial

@ A serial guarded input
guarded input port serialGuarded: serial

@ A serial output port
output port serialOut: [5] serial
