@ A typed async input port
async input port typedAsync: Typed

@ A typed async input port with queue full behavior and priority
async input port typedAsyncAssert: Typed assert

@ A typed async input port with queue full behavior and priority
async input port typedAsyncBlockPriority: Typed priority 10 block

@ A typed async input port with queue full behavior and priority
async input port typedAsyncDropPriority: Typed priority 5 drop

@ A serial async input port
async input port serialAsync: serial

@ A serial async input port with queue full behavior and priority
async input port serialAsyncAssert: serial assert

@ A serial async input port with queue full behavior and priority
async input port serialAsyncBlockPriority: serial priority 10 block

@ A serial async input port with queue full behavior and priority
async input port serialAsyncDropPriority: serial priority 5 drop
