#!/bin/sh -e

# Ensure the script can be run from any directory
wd=`dirname $0`
cd $wd

. scripts/utils.sh

sbt clean
rm -rf bin native-fpp-* test-output.txt
clean
for file in `find . -mindepth 2 -name clean`
do
  dir=`dirname $file`
  (cd $dir; ./clean)
done
