#!/bin/sh -e

if test $# -gt 1
then
  echo 'usage: install-native dest-dir' 1>&2
  echo '       install-native' 1>&2
  exit 1
fi

if test -n "$1" 
then
  dest=$1
else
  dest=bin
fi

dir=`dirname $dest`
dir=`cd $dir; pwd`
base=`basename $dest`
dest=$dir/$base

tools1="
fpp-check
fpp-depend
fpp-filenames
fpp-format
"

tools2="
fpp-locate-defs
fpp-locate-uses
fpp-syntax
fpp-to-xml
"

echo "Building native1 files"
(cd native/native1; ../config; sbt nativeLink)

mkdir -p $dest

echo "Installing tools1 at $dest"
for tool in $tools1
do
  echo "  Installing $tool"
  file=`find tools/$tool/target -name "*-out"`
  cp $file $dest/$tool
done

echo "Building native2 files"
(cd native/native2; ../config; sbt nativeLink)

mkdir -p $dest

echo "Installing tools2 at $dest"
for tool in $tools2
do
  echo "  Installing $tool"
  file=`find tools/$tool/target -name "*-out"`
  cp $file $dest/$tool
done

