#!/bin/sh -e

export SBT_OPTS="-Xmx4G"

if test $# -gt 1
then
  echo 'usage: install-native dest-dir' 1>&2
  echo '       install-native' 1>&2
  exit 1
fi

if test -n "$1" 
then
  dest=$1
else
  dest=bin
fi

dir=`dirname $dest`
dir=`cd $dir; pwd`
base=`basename $dest`
dest=$dir/$base

tools="
fpp-check
fpp-depend
fpp-filenames
fpp-format
fpp-locate-defs
fpp-locate-uses
fpp-syntax
fpp-to-xml
"

skipped="
fpp-from-xml
fpp-to-cpp
"

echo "Building native files"
(cd native; ./config; sbt nativeLink)

mkdir -p $dest

echo "Installing tools at $dest"
for tool in $tools
do
  echo "  Installing $tool"
  file=`find tools/$tool/target -name "*-out"`
  cp $file $dest/$tool
done

echo "Note: there is no native build for"
for tool in $skipped
do
  echo "  $tool"
done
