= Compiler

== Requirements

* A Unix environment, such as Linux, Mac OS, or the Windows Subsystem for Linux.
* The https://www.scala-sbt.org[Simple Build Tool (sbt)] for Scala.

== Installing

To install in the `bin` directory, run `./install`.
This step also runs all the unit tests.
To install to a different directory, run `./install` _dir-name_.

Once you have installed the FPP compiler to a directory `FPP_INSTALL_DIR`, you
should put `FPP_INSTALL_DIR` in your shell path. For example, in bash:

[source,bash]
----
% export FPP_INSTALL_DIR=[path-to-fpp-install-dir]
% export PATH=$PATH:$FPP_INSTALL_DIR
----

That way you can run the tools from anywhere.

The currently available tools are as follows:

* `fpp-check`
* `fpp-depend`
* `fpp-format`
* `fpp-from-xml`
* `fpp-locate-defs`
* `fpp-locate-uses`
* `fpp-syntax`
* `fpp-to-cpp`
* `fpp-to-xml`

As of v0.3.0, modeling and translation of constants, types, enums, and ports is 
supported.
Topology support is planned for v0.4.0.

See https://fprime-community/fpp/wiki/Tools
for more information.

== Testing

* Run `./install` or `./sbt test` to run all unit tests.

* Run `./test` to run all integration tests.
Do this after running `./install`.
If you update the build, rerun `./install` before running `./test`.

== Development

. Start up the sbt shell.

. In the shell, run `compile` to compile everything, `test` to run all unit tests,
and `assembly` to create jar files.
The `install` script runs these commands automatically.
It also moves the jar files to the install directory and puts executable
shell scripts there.

== Cleaning

To clean the repository, run `./clean` in this directory.
This will run `sbt clean` and delete generated build
and test artifacts.
