= Compiler

*Requirements:*
Install the 
https://www.scala-sbt.org[Simple Build Tool (sbt)] for Scala.

*Installing:*
To install in the `bin` directory, run `./install`.
This step also runs all the unit tests.
To install to a different directory, run `./install` _dir-name_.

The currently available tools are

* `fpp-check` (constants, types, and enums only)
* `fpp-depend`
* `fpp-format`
* `fpp-syntax`
* `fpp-to-xml` (structs and enums only)

See https://github.jpl.nasa.gov/bocchino/fpp/wiki/Tools
for more information.

*Testing:*
Run `./install` or `./sbt test` to run all unit tests.
Run `./test` to run all integration tests.
Do this after running `./install`.
If you update the build, rerun `./install` before running `./test`.

*Development:*

. Start up the sbt shell.

. In the shell, run `compile` to compile everything, `test` to run all unit tests,
and `assembly` to create jar files.
The installer script runs these commands automatically.
It also moves the jar files to the install directory and puts executable
shell scripts there.

*Cleaning:*
To clean the repository, run `./clean` in this directory.
This will run `sbt clean` and delete generated build
and test artifacts.
