@startuml

[*] --> OFF

state OFF
state ON
state ON_OR_ERROR <<choice>>
state ERROR

OFF --> ON_OR_ERROR : cmdOn
ON_OR_ERROR --> ON : [ powerOnIsSafe ]
ON_OR_ERROR --> ERROR : [ else ]
ON --> OFF : cmdOff
ERROR --> OFF : cmdReset

@enduml
