
@startuml

[*] --> ON

state ON {
    ON:Entry: turnLedOn()
}

state OFF {
    OFF:Entry: turnLedOff()
}

state WAITING {
    WAITING:Entry: blinkLed()
}

ON --> OFF : RTI
OFF --> ON : RTI
ON --> WAITING : WAIT
OFF --> WAITING : WAIT
@enduml
