#!/bin/sh -e

. ../../../../scripts/utils.sh

clean
rm -f default-tests.sh default-update-ref.sh
for file in `find . -name '*out.*' -or -name '*.names.txt' -or -name '*o' -or -name '*Ac.cpp' -or -name '*Ac.hpp'`
do
  rm $file
done
