// ======================================================================
// \title  AliasStringAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for AliasString alias
// ======================================================================

#ifndef AliasStringAliasAc_HPP
#define AliasStringAliasAc_HPP

#include <FpConfig.hpp>

#include "Fw/Types/String.hpp"

//! Alias of a string
using AliasString = Fw::String;

#endif
