#!/bin/sh

# ----------------------------------------------------------------------
# Compile ref C++ files, to check them for validity
# ----------------------------------------------------------------------

cd `dirname $0`

fprime_gcc=../../../../scripts/fprime-gcc

for file in `find . -name 'FppConstantsAc_*.ref.cpp'`
do
  base=`basename $file .ref.cpp`
  echo "compiling $base"
  dest_base=`echo $base | sed 's;\(.*FppConstantsAc\).*;\1;'`
  cp $base.hpp $dest_base.hpp
  cp $base.cpp $dest_base.cpp
  $fprime_gcc -I../../.. -c $dest_base.cpp
done
