#!/bin/sh

export COMPILER_ROOT=../../..

. $COMPILER_ROOT/scripts/test-utils.sh

fpp_filenames=$COMPILER_ROOT/bin/fpp-filenames

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_filenames $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

include()
{
  run_test "" include
}

include_template()
{
  run_test "-t" "include" include_template
}

include_test()
{
  run_test "-u" "include" include_test
}

include_test_auto_helpers()
{
  run_test "-u -a" "include" include_test_auto_helpers
}

include_test_template()
{
  run_test "-u -t" "include" include_test_template
}

include_test_template_auto_helpers()
{
  run_test "-u -t -a" "include" include_test_template_auto_helpers
}

ok()
{
  run_test "" ok
}

ok_template()
{
  run_test "-t" "ok" ok_template
}

ok_test()
{
  run_test "-u" "ok" ok_test
}

ok_test_auto_helpers()
{
  run_test "-u -a" "ok" ok_test_auto_helpers
}

ok_test_template()
{
  run_test "-u -t" "ok" ok_test_template
}

ok_test_template_auto_helpers()
{
  run_test "-u -t -a" "ok" ok_test_template_auto_helpers
}

template()
{
  run_test "" template
}

template_template()
{
  run_test "-t" "template" template_template
}

template_test()
{
  run_test "-u" "template" template_test
}

# ----------------------------------------------------------------------
# Differential tests
#
# template_hand.fpp is template.fpp with the expansion written out by
# hand. The two models must yield the same file names, so check the
# output of the hand-written model against the reference output of the
# model that uses a module template. That way there is a single
# reference, and it pins the two models together: if the names
# contributed by an expansion are dropped again, updating the reference
# will not hide it.
# ----------------------------------------------------------------------
run_hand_test()
{
  args=$1
  outfile=$2
  reffile=$3
  $fpp_filenames $args template_hand.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  diff -u $reffile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

template_hand()
{
  run_hand_test "" template_hand template
}

template_hand_template()
{
  run_hand_test "-t" template_hand_template template_template
}

template_hand_test()
{
  run_hand_test "-u" template_hand_test template_test
}

tests="
include
include_template
include_test
include_test_auto_helpers
include_test_template
include_test_template_auto_helpers
ok
ok_template
ok_test
ok_test_auto_helpers
ok_test_template
ok_test_template_auto_helpers
template
template_template
template_test
template_hand
template_hand_template
template_hand_test
"

run_suite $tests
