#!/bin/sh

export COMPILER_ROOT=../../..

. $COMPILER_ROOT/scripts/test-utils.sh

fpp_filenames=$COMPILER_ROOT/bin/fpp-filenames

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  echo "updating $outfile.ref.txt"
  $fpp_filenames $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

update "" include
update "-t" "include" include_template
update "-u" "include" include_test
update "-u -a" "include" include_test_auto_helpers
update "-u -t" "include" include_test_template
update "-u -t -a" "include" include_test_template_auto_helpers
update "" ok
update "-t" "ok" ok_template
update "-u" "ok" ok_test
update "-u -a" "ok" ok_test_auto_helpers
update "-u -t" "ok" ok_test_template
update "-u -t -a" "ok" ok_test_template_auto_helpers
