
== State Machine Behavior

Blah blah

=== State Events

*state events* specifies _events_ that are dispatched to the state machine which causes the state machine to run to completion.

==== Syntax
`event`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`:` 
<<Definitions_Struct-Definitions,struct definition>>
`]`

==== Semantics
. The _identifier_ specifies the event name.

. The _struct definition_ specifies an optional data structure associated with the event

==== Examples

[source,fpp]
----
struct FaultData {
    id: U32
    data: U32
}

# An event without data
event RTI

# An event with data
event Fault: FaultData

----

=== State Actions

*state actions* specifies _actions_ that are invoked upon transitions

==== Syntax
`action`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`:` 
<<Definitions_Struct-Definitions,struct definition>>
`]`

==== Semantics
. The _identifier_ specifies the action name.

. The _struct definition_ specifies an optional data structure associated with the action and will be
passed into the action function when invoked.

==== Examples

[source,fpp]
----
struct FaultData {
    id: U32
    data: U32
}

# An action without data
action initPower

# An action with data
action reportFault: FaultData

----

=== State Guards

*state guards* specifies _guards_ that are associated with transitions

==== Syntax
`guard`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`:` 
<<Definitions_Struct-Definitions,struct definition>>
`]`

==== Semantics
. The _identifier_ specifies the guard name wich is a function that returns a boolean.  When the guard is evaluated to True, it allows the transition to be invoked.

. The _struct definition_ specifies an optional data structure associated with the guard and will be
passed into the guard function when invoked.

==== Examples

[source,fpp]
----
struct FaultData {
    id: U32
    data: U32
}

# A guard without data
guard noRecovery

# A guard with data
guard noRecovery: FaultData

----

=== State Definition

A *state definition* specifies a state in a 
<<Definitions_State-Machine-Definitions,state machine>>  

==== Syntax

`state` <<Lexical-Elements_Identifiers,_identifier_>>
_[_ `{` _state_sequence_ `}` _]_

_state-sequence_ is an 
<<Element-Sequences,element sequence>> in
which each element is a *state member*,
and the terminating punctuation is a semicolon.
A state member is one of the following

* A <<State-Machine-Behavior_State-Definition,state definition>>
* A <<State-Machine-Behavior_State-Junction,state junction>>
* A <<State-Machine-Behavior_State-Initial,state initial>>
* A <<State-Machine-Behavior_State-Transition,state transition>>


==== Semantics

. The _identifier_ specifies the name of a state in the state machine

. The state can be hierarchical, a state can be defined within another state

. The state is required to have one _initial_ specification if it is a hierarchical state

. The state can have _junctions_

. All _transitions_ that originate from a state are required to be specified inside that state


==== Examples

[source,fpp]
----
state machine MonitorSm {

    event Complete
    event Drive
    event Calibrate
    event RTI
    event Stop
    event Fault
    
    action init2
    action doCalibrate
    action motorControl
    action reportFault

    guard calibrateReady

    
    state DeviceOn {

        initial Initializing do init2

        state Initializing {
            on Complete visit Idle
        }

        state Idle {
            on Drive visit Driving
            on Calibrate if calibrateReady visit Calibrating
        }

        state Calibrating {
            on RTI do doCalibrate
            on Fault go Idle do reportFault
            on Complete visit Idle
        }

        state Driving {
            on RTI do motorControl
            on Stop visit Idle
        }

    }

}
----

=== State Initial

A *state initial* specifies an initial state transition  

==== Syntax

`initial` 
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`do`
<<Lexical-Elements_Identifiers,_identifier_>>
_]_

==== Semantics

. The first _identifier_ specifies the state or junction that will initially be transitioned into.

. An _initial_ specification is required at the top of the state machine

. An _initial_ specification is required at the top of every hierarchical state
 
. The optional _identifier_ after the keyword `do` specifies the action performed on the initial transition
 

==== Examples

[source,fpp]
----
state machine Device {

    action initDevices

    initial DeviceOn

    state DeviceOn {

        initial PoweringUp do initDevices

        state PoweringUp {

        }
    }
----

=== State Junction

A *state junction* specifies a state junction in a  
<<Definitions_State-Machine-Definitions,state machine>>  

==== Syntax

`junction` <<Lexical-Elements_Identifiers,_identifier_>>
`{`
`if` <<Lexical-Elements_Identifiers,_identifier_>> `visit` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`do` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
`else` `visit` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`do` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
`}`

==== Semantics

. The _identifier_ after the keyword `junction` is the name of the _junction_. 

. Each _junction_ requires a unique name.

. Each _junction_ requires two exit transitions in which one must have one guard and the other transition no guard.

. The _identifier_ after the keywrod `if` specifies the name of the _guard_

. The _identifier_ after the keyword `visit` specifies the target state for the transition

. The _identifier_ after the keyword `do` specifies the action performed when the transition is taken

==== Examples

[source,fpp]
----
state machine Device {

    action initPower
    guard coldStart

    junction j1 {
            if coldStart visit DeviceOff
            else visit DeviceOn do initPower
    }

    state DeviceOff {

    }

    state DeviceOn {

    }

}

----

=== State Transition

A *state transition* specifies a state transition in a  
<<Definitions_State-Machine-Definitions,state machine>>  

==== Syntax

`on` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`if` <<Lexical-Elements_Identifiers,_identifier_>>
_]_
`visit` <<Lexical-Elements_Identifiers,_identifier_>>
_[_
`do` <<Lexical-Elements_Identifiers,_identifier_>>
_]_

==== Semantics

. The _identifier_ after the keyword `on` is the name of the _event_ that triggers this transition 

. The optional _identifier_ after the keyword `if` is the name of the _guard_ for this transition

. The _identifier_ after the keyword `visit` specifies the name of the target state

. The optional _identifier_ after the keyword `do` specifies the action performed when the transition is taken

==== Examples

[source,fpp]
----
state machine Device {

    event RTI
    event PowerOn
    
    action performStuff
    action getReady

    guard initComplete

    state DeviceOff
        on PowerOn if initComplete visit DeviceOn do getReady

    }

    state DeviceOn {
        on RTI do performStuff

    }

}

----
