#!/bin/sh -e

. ../../../../scripts/utils.sh

clean
rm -f default-tests.sh default-update-ref.sh

for file in `find . -name '*.ref.txt' -or -name '*.out.txt'`
do
  rm $file
done

for dir in `find . -type d -name '*Layout.ref'`
do
  rm -r $dir
done
