== Defining and Using Module Templates

When you are constructing an FPP model, you may find that you need to repeat
essentially the same structure at different points of the model, possibly with
variations in detail.
For example:

* You may need to use the same subtopology in different deployments
of the same multi-deployment system.
For example, each of the deployments may require the same subtopology for 
command and data handling.

* Different deployments may need variants of the same subtopology.
For example, a deployment for testing may need a communication subtopology
that connects directly to a test harness, whereas the flight deployment
may need a communication subtopology that includes a radio.

For this kind of replicated structure, FPP provides a feature called a
*module template*.
By defining a module template, you can specify model elements (types, 
constants, components, topologies, etc.)
that may occur at the top level or within a module definition.
Then you can *expand* the template any number of times, each in a different
module.
This process creates a distinct element for each expansion.
For example, you can define a module template that includes the
definition of a constant `c`.
Expanding that template inside a module `M` would create a definition
`M.c`, whereas expanding that template inside a module `N` would
create a definition `N.c`.
In this section, we explain how to define and use module templates.

=== Basic Module Templates

Here is a basic example of defining and using a module template.
It is based on the constant definition example sketched at the
beginning of this section.

[source,fpp]
----
module template T {
  constant c = 0
}

module M {
  expand T
}

module N {
  expand T
}
----

In this example, we have done the following:

. We have defined a module template `T` containing the constant
definition `constant c = 0`.
In general, to write a module template definition you write
`module` `template` followed by the name of the template
and the elements of the template enclosed in curly braces.
A module template definition is an
<<Writing-Comments-and-Annotations_Annotations,annotatable element>>.

. We have expanded the template `T` twice, once inside
module `M` and once inside module `N`.

=== Module Template Parameters

==== Constant Parameters

TODO

==== Type Parameters

TODO

==== Interface Instance Parameters

TODO

=== Resolving Names in Expanded Templates

TODO

=== Nesting of Module Templates

TODO
