== Defining Ports

A *port definition* defines an F Prime port.
In F Prime, a port specifies the endpoint of a connection
between two component instances.
Components are the basic units of FSW function in F Prime
and are described in the
<<Defining-Components,next section>>.
A port definition specifies (1) the name of the port, (2) the type of the data
carried
on the port, and (3) an optional return type.

=== Port Names

The simplest port definition consists of the keyword `port` followed
by a name.
For example:

[source,fpp]
----
port P
----

This code defines a port named `P` that carries no data and returns
no data.
This kind of port can be useful for sending or receiving a triggering event.

=== Formal Parameters

More often, a port will carry data.
To specify the data, you write *formal parameters*
enclosed in parentheses.
The formal parameters of a port definition are similar to the formal parameters
of a function in a programming
language: each one has a name and a type, and you may write
zero or more of them.
For example:

[source,fpp]
----
port P1() # Zero parameters; equivalent to port P1
port P2(a: U32) # One parameter
port P3(a: I32, b: F32, c: string) # Three parameters
----

The type of a formal parameter may be any valid type, including an
array type, a struct type, an enum type, or an abstract type.
For example, here is some code that defines an enum type `E` and
and abstract type `T`, and then uses those types in the
formal parameters of a port:

[source,fpp]
----
enum E { A, B }
type T
port P(e: E, t: T)
----

The formal parameters form an
<<Defining-Constants_Multiple-Definitions-and-Element-Sequences,element
sequence>> in which the optional terminating punctuation is a comma.  As usual
for element sequences, you can omit the comma and use a newline instead.  So,
for example, we can write the definition shown above in this alternate way:

[source,fpp]
----
enum E { A, B }
type T
port P(
  e: E
  t: T
)
----

=== Handler Functions

As discussed further in the sections on
<<Defining-Components,defining components>>
and
<<Defining-Component-Instances,instantiating components>>,
when constructing an F Prime application, you
instantiate port definitions as *output ports* and
*input ports* of component instances.
Output ports are connected to input ports.
For each output port `pOut` of a component instance `c1`,
there is a corresponding auto-generated function that the
implementation of `c1` can call in order to *invoke* `pOut`.
If `pOut` is connected to an input
port `pIn` of component instance `c2`, then invoking `pOut` runs a
*handler function* `pIn_handler` associated with `pIn`.
The handler function is part of the implementation of the component
`C2` that `c2` instantiates.
In this way `c1` can send data to `c2` or request
that `c2` take some action.
Each input port may be *synchronous* or *asynchronous*.
A synchronous invocation directly calls a handler function.
An asynchronous invocation calls a short function that puts
a message on a queue for later dispatch.
Dispatching the message calls the handler function.

*Translating handler functions:*
In FPP, each output port `pOut` or input port `pIn` has a *port type*.
This port type refers to an FPP port definition `P`.
In the {cpp} translation, the signature of a handler function
`pIn_handler` for `pIn`
is derived from `P`.
In particular, the {cpp} formal parameters of `pIn_handler`
correspond to the
<<Defining-Ports_Formal-Parameters,FPP formal parameters>> of `P`.

When generating the handler function `pIn_handler`, F
Prime translates each formal parameter _p_ of `P` in the following way:

. If _p_ carries a
<<Defining-Constants_Expressions_Primitive-Values,primitive value>>,
then _p_ is translated to a {cpp} value parameter.

. Otherwise _p_ is translated to a {cpp} `const` reference
parameter.

As an example, suppose that `P` looks like this:

[source,fpp]
----
type T
port P(a: U32, b: T)
----

Then the signature of `pIn_handler` might look like this:

[source,cpp]
----
virtual void pIn_handler(U32 a, const T& b);
----

*Calling handler functions:*
Suppose again that output port `pOut` of component instance `c1`
is connected to input port `pIn` of component instance `c2`.
Suppose that the implementation of `c1` invokes `pOut`.
What happens next depends on whether `pIn` is synchronous
or asynchronous.

If `pIn` is synchronous, then the invocation is a direct
call of the `pIn` handler function.
Any value parameter is passed by copying the value on
the stack.
Any `const` reference parameter provides a reference to
the data passed in by `c1` at the point of invocation.
For example, if `pIn` has the port type `P` shown above,
then the implementation of `pIn_handler` might look like this:

[source,cpp]
----
// Assume pIn is a synchronous input port
void C2::pIn_handler(U32 a, const T& b) {
  // a is a local copy of a U32 value
  // b is a const reference to T data passed in by c1
}
----

Usually the `const` reference is what you want, for efficiency reasons.
If you want a local copy of the data, you can make one.
For example:

[source,cpp]
----
// Copy b into b1
auto b1 = b
----

Now `b1` has the same data that the parameter `b` would have
if it were passed by value.

If `pIn` is asynchronous, then the invocation does not
call the handler directly. Instead, it calls
a function that puts a message on a queue.
The handler is called when the message is dispatched.
At this point, any value parameter is passed by
copying the value out of the queue and onto the stack.
Any `const` reference parameter is passed by
(1) copying data out of the queue and onto the stack and
(2) then providing a `const` reference to the data on the stack.
For example:

[source,cpp]
----
// Assume pIn is an asynchronous input port
void C2::pIn_handler(U32 a, const T& b) {
  // a is a local copy of a U32 value
  // b is a const reference to T data copied across the queue
  // and owned by this component
}
----

Note that unlike in the synchronous case, const references
in parameters refer to data owned by the handler
(residing on the handler stack),
not data owned by the invoking component.
Note also that the values must be small enough to permit
placement on the queue and on the stack.

If you want the handler and the invoking component to share data
passed in as a parameter, or if the data values are too large
for the queue and the stack, then you can use a data structure
that contains a pointer or a reference as a member.
For example, `T` could have a member that stores a reference
or a pointer to shared data.
F Prime provides a type `Fw::Buffer` that stores a
pointer to a shared data buffer.

=== Reference Parameters

You may write the keyword `ref` in front of any formal parameter _p_
of a port definition.
Doing this specifies that _p_ is a *reference parameter*.
Each reference parameter in an FPP port becomes a mutable
{cpp} reference at the corresponding place in the
handler function signature.
For example, suppose this port definition

[source,fpp]
----
type T
port P(a: U32, b: T, ref c: T)
----

appears as the type of an input port `pIn` of component `C`.
The generated code for `C` might contain a handler function with a
signature like this:

[source,cpp]
----
virtual void pIn_handler(U32 a, const T& b, T& c);
----

Notice that parameter `b` is not marked `ref`, so it is
translated to `const T& b`, as discussed in the previous section.
On the other hand, parameter `c` is marked ref, so it
is translated to `T& c`.

Apart from the mutability, a reference parameter has the same
behavior as a `const` reference parameter, as described in
the previous section.
In particular:

* When `pIn` is synchronous, a reference parameter _p_ of `pIn_handler`
refers to the data passed in by the invoking component.

* When `pIn` is asynchronous, a reference parameter _p_ of `pIn_handler`
refers to data copied out of the queue and placed on the local stack.

The main reason to use a reference parameter is to
return a value to the sender by storing it through
the reference.
We discuss this pattern in the section on
<<Defining-Ports_Returning-Values,returning values>>.

=== Returning Values

Optionally, you can give a port definition a return type.
To do this you write an arrow `pass:[->]` and a type
after the name and the formal parameters, if any.
For example:

[source,fpp]
----
type T
port P1 -> U32 # No parameters, returns U32
port P2(a: U32, b: F32) -> T # Two parameters, returns T
----

Invoking a port with a return type is like calling a function with
a return value.
Such a port may be used only in a synchronous context (i.e.,
as a direct function call, not as a message placed
on a concurrent queue).

In a synchronous context only, `ref` parameters provide another way to return
values on the port,
by assigning to the reference, instead of executing a {cpp} `return` statement.
As an example, consider the following two port definitions:

[source,fpp]
----
type T
port P1 -> T
port P2(ref t: T)
----

The similarities and differences are as follows:

. Both `P1` and `P2` must be used in a synchronous context,
because each returns a `T` value.

. In the generated {cpp} code,

.. The function for invoking `P1`
has no arguments and returns a `T` value.
A handler associated with `P1` returns a value of type `T`
via the {cpp} `return` statement.
For example:
+
----
T C::p1In_handler() {
  ...
  return T(1, 2, 3);
}
----

.. The function for invoking `P1` has one argument `t`
of type `T&`.
A handler associated with `P2` returns a value of type `T`
by updating the reference `t` (assigning to it, or updating
its fields).
For example:
+
----
void C::p2In_handler(T& t) {
  ...
  t = T(1, 2, 3);
}
----
+
+

The second way may involve less copying of data.

Finally, there can be any number of reference parameters,
but at most one return value.
So if you need to return multiple values on a port, then reference
parameters can be useful.
As an example, the following port attempts to update a result
value of type `U32`.
It does this via reference parameter.
It also returns a status value indicating whether the update
was successful.

[source,fpp]
----
enum Status { SUCCEED, FAIL }
port P(ref result: U32) -> Status
----

A handler for `P` might look like this:

----
Status C::pIn_handler(U32& result) {
  Status status = Status::FAIL;
  if (...) {
    ...
    result = ...
    status = Status::SUCCEED;
  }
  return status;
}
----

=== Pass-by-Reference Semantics

Whenever a {cpp} formal parameter _p_ enables sharing of data between
an invoking component and a handler function `pIn_handler`,
we say that _p_ has *pass-by-reference semantics*.
Pass-by-reference semantics occurs in the following cases:

. _p_ has reference or `const` reference type,
and the port `pIn` is synchronous.

. _p_ has a type _T_ that contains a pointer or
a reference as a member.

When using pass-by-reference semantics,
you must carefully manage the
use of the data to avoid concurrency bugs
such as data races.
This is especially true for references that can modify
shared data.

Except in special cases that require special expertise (e.g.,
the implementation of highly concurrent data structures),
you should enforce the rule that at most
one component may use any piece of data at any time.
In particular, if component `A` passes a reference to component `B`,
then component `A` should not use the reference while
component `B` is using it, and vice versa.
For example:

. Suppose component `A` owns some data `D` and passes a reference
to `D` via a synchronous port call to component `B`.
Suppose the port handler in component `B` uses the data but
does not store the reference, so that when the handler exits,
the reference is lost.
This is a good pattern.
In this case, we may say that ownership of `D` resides in `A`, temporarily
goes to `B` for the life of the handler, and goes back to `A`
when the handler exits.
Because the port call is synchronous, the handler in `B`
never runs concurrently with any code in `A` that uses `D`.
So at most one of `A` or `B` uses `D` at any time.

. Suppose instead that the handler in `B` stores the reference
into a member variable, so that the reference
persists after the handler exits.
If this happens, then you should make sure that `A` cannot use
`D` unless and until `B` passes ownership of `D` to `A` and vice versa.
For example, you could use state variables of enum type in `A` and in `B` to
track ownership, and you could have a port invocation from `A` to `B` pass the
reference and transfer ownership from `A` to `B` and vice versa.

=== Annotating a Port Definition

A port definition is an
<<Writing-Comments-and-Annotations_Annotations,annotatable element>>.
Each formal parameter is also an annotatable element.
Here is an example:

[source,fpp]
----
@ Pre annotation for port P
port P(
  @ Pre annotation for parameter a
  a: U32
  @ Pre annotation for parameter b
  b: F32
)
----
