== Defining Systems

A *system* represents the highest level of architecture in an F Prime
application.
In the current version of FPP, there is a close coupling
between systems and <<Defining-Topologies_A-Simple-Example,deployment 
topologies>>; in fact, a system
is just a thin wrapper around a single deployment topology.
This is because in the current modeling approach, only single-deployment
systems are modeled.
To construct a multi-deployment system, you have to manually connect
several single-deployment systems.
In a future version of FPP, we will provide a more direct way
to model a system consisting of multiple deployments.

To define a system, you write the keyword `system` followed
by a name, a colon, and the name of a <<Defining-Topologies,topology>>.
The topology must be a deployment topology.
For example:

[source,fpp]
----
deployment topology T {

}

system S: T
----

Currently, the FPP tools use the topology `T` to generate a
system dictionary for `S`.
In the future, you will be able to do the following:

. Specify a system consisting of multiple deployment topologies
and connections between them.
The translator will automatically generate code for
implementing the connections that span the deployments.

. Specify <<Defining-Topologies_Telemetry-Packets,telemetry packets>>
at the system level.

A system definition may appear at the top level or inside a
<<Defining-Modules,module definition>>.
A system definition is an
<<Writing-Comments-and-Annotations_Annotations,annotatable element>>.
