== Defining Enums

An FPP model may contain *enum definitions*.
Enum is short for enumeration.
An FPP enum is similar to an enum in C or {cpp}.
It defines a named type called an *enum type* and a set of named constants
called *enumerated constants*.
The enumerated constants are the values associated with the type.

An enum definition may appear at the top level or inside a
<<Defining-Modules,module definition>>.
An enum definition is an 
<<Writing-Comments-and-Annotations_Annotations,annotatable element>>.

=== Writing an Enum Definition

Here is an example:

[source,fpp]
----
enum Decision {
  YES
  NO
  MAYBE
}
----

This code defines an enum type `Decision` with three
enumerated constants: `YES`, `NO`, and `MAYBE`.

In general, to write an enum definition, you write the following:

* The keyword `enum`.

* The name of the enum.

* A sequence of enumerated constants enclosed in curly braces `{` ... `}`.


The enumerated constants form an
<<Defining-Constants_Multiple-Definitions-and-Element-Sequences,element 
sequence>>
with a comma as the optional terminating punctuation.
For example, this definition is equivalent to the one above:

[source,fpp]
----
enum Decision { YES, NO, MAYBE }
----

There must be at least one enumerated constant.

=== Using the Enumerated Constants

TODO

=== Specifying the Constant Values

TODO

=== The Representation Type

TODO

=== The Default Value

TODO
