== Defining Topologies

In F Prime, a *topology* or connection graph is the
highest level of software architecture in a FSW application.
A topology specifies what
<<Defining-Component-Instances,component instances>>
are used in the application and how their
<<Defining-Components_Port-Instances,port instances>>
are connected.

An F Prime FSW application consists of a topology _T_;
all the types, ports, and components used by _T_;
and a small amount of top-level {cpp} code that you write by hand.
In the section on
<<Writing-C-Plus-Plus-Implementations_Implementing-Deployments,
implementing deployments>>, we will explain more about the top-level
{cpp} code.
In this section we explain how to define a topology in FPP.

=== A Simple Example

We begin with a simple example that shows how many of the pieces
fit together.

[source,fpp]
----
port P

passive component C {
  sync input port pIn: P
  output port pOut: P
}

instance c1: C base id 0x100
instance c2: C base id 0x200

@ A simple topology
topology Simple {

  @ This specifier says that instance c1 is part of the topology
  instance c1
  @ This specifier says that instance c2 is part of the topology
  instance c2

  @ This code specifies a connection graph C1
  connections C1 {
    c1.pOut -> c2.pIn
  }

  @ This code specifies a connection graph C2
  connections C2 {
    c2.pOut -> c1.pIn
  }

}
----

In this example, we define a <<Defining-Ports,port>> `P`.
Then we define a <<Defining-Components,passive component>> `C`
with an input port and an output port, both of type `P`.
We define two  <<Defining-Component-Instances,instances>> of
`C`, `c1` and `c2`.
We put these instances into a topology called `Simple`.

As shown, to define a topology, you write the keyword `topology`,
the name of the topology, and the members of the topology
definition enclosed in curly braces.
In this case, the topology has two kinds of members:

. Two *instance specifiers* specifying that instances
`c1` and `c2` are part of the topology.

. Two *graph specifiers* that specify connection graphs
named `C1` and `C2`.

As shown, to write an instance specifier, you write the
keyword `instance` and the name of a component instance
definition.
In general the name may be a qualified name such as `A.B`
if the instance is defined inside a
<<Defining-Modules,module>>; in this simple
example it is not.
Each instance specifier states that the instance it names
is part of the topology.
The instances appearing in the list must be distinct.
For example, this is not correct:

[source,fpp]
--------
topology T {
  instance c1
  instance c1 # Error: duplicate instance c1
}
--------

A graph specifier specifies one or more connections
between component instances.
Each graph specifier has a name.
By dividing the connections of a topology into named
graphs, you can organize the connections in a meaningful way.
For example you can have one graph group
for connections that send commands, another one
for connections that send telemetry, and so forth.
We will have more to say about this in a later section.

As shown, to write a graph specifier, you may write the keyword `connections`
followed by the name of the graph; then you may list
the connections inside curly braces.
(In the next section, we will explain another way to write a graph specifier.)
Each connection consists of an endpoint, an arrow `pass:[->]`,
and another endpoint.
An endpoint is the name of a component instance
(which in general may be a qualified name), a dot,
and the name of a port of that component instance.

In this example there are two connection graphs, each containing
one connection:

. A connection graph `C1` containing a connection from `c1.pOut` to `c2.pIn`.

. A connection graph `C2` containing a connection from `c2.pOut` to `c1.pIn`.

As shown, topologies and their members are
<<Writing-Comments-and-Annotations_Annotations,annotatable elements>>.
The topology members form an
<<Defining-Constants_Multiple-Definitions-and-Element-Sequences,
element sequence>> in which the optional
terminating punctuation is a semicolon.

=== Connection Graphs

In general, an FPP topology consists of a list of instances
and a set of named connection graphs.
There are two ways to specify connection graphs:
*direct graph specifiers* and *pattern graph specifiers*.

==== Direct Graph Specifiers

A direct graph specifier provides a name and a list
of connections.
We illustrated direct graph specifiers in the
previous section, where the simple topology example
included direct graph specifiers for graphs named
`C1` and `C2`.
Here are some more details about direct graph specifiers.

Each instance named in a connection must be part of the
instance list in the topology.
For example, if you write a connection `a.b pass:[->] c.d` inside
a topology `T`, and the specifier `instance a` does not
appear inside topology `T`, then you will get an error --
even if `a` is a valid instance name for the FPP model.
The reason for this rule is that in flight code we need
to be very careful about which instances are included
in the application.
Naming all the instances also lets us check for
<<Analyzing-and-Translating-Models_Checking-Models,
unconnected ports>>.

You may use the same name in more than one direct
graph specifier in the same topology.
If you do this, then all specifiers with the same
name are combined into a single graph with that name.
For example, this code

[source,fpp]
--------
connections C {
  a.p -> b.p
}
connections C {
  c.p -> d.p
}
--------

is equivalent to this code:

[source,fpp]
--------
connections C {
  a.p -> b.p
  c.p -> d.p
}
--------

The members of a direct graph specifier form an
<<Defining-Constants_Multiple-Definitions-and-Element-Sequences,
element sequence>> in which the optional
terminating punctuation is a comma.
For example, you can write this:

[source,fpp]
--------
connections C { a.p -> b.p, c.p -> d.p }
--------

==== Pattern Graph Specifiers

A few connection patterns are so common in F Prime that they
get special treatment in FPP.
For example, an F Prime topology typically includes an
instance of the component `Svc.Time`.
This component has a port `timeGetPort`
of type `Fw.Time` that other components can use to get the system
time.
Any component that gets the system time
(and there are usually several) has a connection to
the `timeGetPort` port of the `Svc.Time` instance.

Suppose you are constructing a topology in which
(1) `sysTime` is an instance of `Svc.Time`; and (2)
each of the instances
`a`, `b`, `c`, etc., has a
<<Defining-Components_Special-Port-Instances_Time-Get-Ports, time get port>>
`timeGetOut` port connected to `sysTime.timeGetPort`,
If you used a direct graph specifier to write all these connections,
the result might look like this:

[source,fpp]
--------
connections Time {
  a.timeGetOut -> sysTime.timeGetPort
  b.timeGetOut -> sysTime.timeGetPort
  c.timeGetOut -> sysTime.timeGetPort
  ...
}
--------

This works, but it is tedious and repetitive. So FPP provides
a better way. Instead, you can use a *pattern graph specifier*
to specify this common pattern.
You can write

[source,fpp]
--------
time connections instance sysTime
--------

This code says the following:

. Use the instance `sysTime` as the instance of `Fw.Time`
for the time connection pattern.

. Automatically construct a direct graph specifier named `Time`.
In this direct graph specifier, include one connection
from each component instance that has a time get port
to the input port of `sysTime` of type `Fw.Time`.

The result is as if you had written the direct graph specifier
yourself.
All the other rules for direct graph specifiers apply: for example,
if you write another direct graph specifier with name `Time`, then
the connections in that specifier are merged with the connections
generated by the pattern specifier.

In the example above, we call `time` the *kind* of the pattern
graph specifier.
We call `sysTime` the *source instance* of the pattern.
It is the source of all the time pattern connections
in the topology.
We call the instances that have time get ports (and so contribute
connections to the pattern) the *target instances*.
They are the instances targeted by the pattern once the source
instance is named.

Table <<pattern-graph-specifiers>> shows the pattern graph
specifiers allowed in FPP.
The columns of the table have the following meanings:

* *Kind:* The keyword or keywords denoting the kind.
When writing the specifier, these appear just before
the keyword `connections`, as shown above for the time example.

* *Source Instance:* The source instance for the pattern.

* *Graph Name:* The name of the connection graph
generated by the pattern.

* *Connections:* The connections generated by the pattern.

The command pattern specifier generates three connection graphs:
`Command`, `CommandRegistration`, and `CommandResponse`.

[[pattern-graph-specifiers]]
.Pattern Graph Specifiers
|===
|Kind|Source Instance|Graph Name|Connections

|
|
|`Command`
|All connections from the unique output port of type `Fw::Cmd`
of the source instance to the
<<Defining-Components_Special-Port-Instances_Command-Ports,
`command` `recv` port>>
of each target instance.

|`command`
|An instance of `Svc.CommandDispatcher` or a similar component for
dispatching commands.
|`CommandRegistration`
|All connections from the
<<Defining-Components_Special-Port-Instances_Command-Ports,
`command` `reg` port>> of each target instance to the
unique input port of type `Fw.CmdReg` of the source instance.

|
|
|`CommandResponse`
|All connections from the
<<Defining-Components_Special-Port-Instances_Command-Ports,
`command` `resp` port>> of each target instance to the
unique input port of type `Fw.CmdResponse` of the source instance.

|`event`
|An instance of `Svc.ActiveLogger` or a similar component for
logging event reports.
|`Events`
|All connections from the
<<Defining-Components_Special-Port-Instances_Event-Ports,
`event` port>> of each target instance to the unique
input port of type `Fw.Log` of the source instance.

|`health`
|An instance of `Svc.Health` or a similar component for
health monitoring.
|`Health`
|(1) All connections from the unique output port of type
`Svc.Ping` of each target instance to the unique input
port of type `Svc.Ping` of the source instance.
(2) All connections from the unique output port of type
`Svc.Ping` of the source instance to the unique
input port of type `Svc.Ping` of each target instance.

|`param`
|An instance of `Svc.PrmDb` or a similar component representing
a database of parameters.
|`Parameters`
|(1) All connections from the
<<Defining-Components_Special-Port-Instances_Parameter-Ports,
`param` `get` port>> of each target instance
to the unique port of type `Fw.PrmGet` of the source instance.
(2) All connections from the
<<Defining-Components_Special-Port-Instances_Parameter-Ports,
`param` `set` port>> of each target instance
to the unique port of type `Fw.PrmSet` of the source instance.

|`telemetry`
|An instance of `Svc.TlmChan` or a similar component for
storing channelized telemetry.
|`Telemetry`
|All connections from the
<<Defining-Components_Special-Port-Instances_Telemetry-Ports,
`telemetry` port>> of each target instance to the unique input
port of type `Fw.Tlm` of the source instance.

|`text` `event`
|An instance of `Svc.PassiveTextLogger` or a similar component
for logging event reports in textual form.
|`TextEvents`
|All connections from the
<<Defining-Components_Special-Port-Instances_Event-Ports,
`text` `event` port>> of each target instance to the unique
input port of type `Fw.LogText` of the source instance.

|`time`
|An instance of `Svc.Time` or a similar component for providing
the system time.
|`Time`
|All connections from the
<<Defining-Components_Special-Port-Instances_Time-Get-Ports,
`time` `get` port>> of each target instance to the unique
input port of type `Fw.Time` of the source instance.

|===

Here are some rules for writing graph pattern specifiers:

. At most one occurrence of each pattern kind is allowed in
each topology.

. For each pattern, the required ports shown in the table
must exist and must be unambiguous.
For example, if you write a time pattern
+
[source,fpp]
--------
time connections instance sysTime
--------
+
then you will get an error if `sysTime` has no
input ports of type `Fw.Time`,
You will also get an error if `sysTime` has two or more
such ports.

As discussed above, the default behavior for a pattern is
to generate all the connections for the pattern.
If you wish, you may generate connections for a selected
set of target instances.
To do this, you write a list of target instances enclosed in
curly braces after the source instance.
For example, suppose a topology contains instances
`a`, `b`, and `c` each of which has an output port
that satisfies the time pattern.
And suppose that `sysTime` is an instance of `Svc.Time`.
Then if you write this pattern

[source,fpp]
--------
time connections instance sysTime
--------

you will get a connection graph `Time` containing
time connections from each of `a`, `b`, and `c` to `sysTime`.
But if you write this pattern

[source,fpp]
--------
time connections instance sysTime {
  a
  b
}
--------

then you will just get the connections from `a` and `b`
to `sysTime`.
As with connections, you can write the instances `a` and `b`
each on its own line, or you can separate them with commas:

[source,fpp]
--------
time connections instance sysTime { a, b }
--------

=== Port Numbering

==== Explicit Numbering

TODO

==== Matched Numbering

TODO

==== General Numbering

TODO

=== Importing Topologies

==== Merging Connection Graphs

TODO

==== Private Instances

TODO
