== Defining and Using Module Templates

When you are constructing an FPP model, you may find that you need to repeat
essentially the same structure at different points of the model, possibly with
variations in detail.
For example:

* You may need to use the same subtopology in different deployments
of the same multi-deployment system.
For example, each of the deployments may require the same subtopology for 
command and data handling.

* Different deployments may need variants of the same subtopology.
For example, a deployment for testing may need a communication subtopology
that connects directly to a test harness, whereas the flight deployment
may need a communication subtopology that includes a radio.

For this kind of replicated structure, FPP provides a feature called a
*module template*.
By defining a module template, you can specify a list of model elements (types, 
constants, components, topologies, etc.)
that may occur at the top level or within a module definition.
Then you can *expand* the template any number of times, each in a different
module.
This process creates a distinct element for each expansion.
For example, you can define a module template that includes the
definition of a constant `c`.
Expanding that template inside a module `M` would create a definition
`M.c`, whereas expanding that template inside a module `N` would
create a definition `N.c`.
In this section, we explain how to define and use module templates.

=== Basic Module Templates

Here is a basic example of defining and using a module template.
It is based on the constant definition example sketched at the
beginning of this section.

[source,fpp]
----
module template T {

  constant c = 0

}

module M {

  expand T

}

module N {

  expand T

}
----

In this example, we have done the following:

. We have defined a module template `T` containing the constant
definition `constant c = 0`.
In general, to write a module template definition you write
`module` `template` followed by the name of the template
and the elements of the template enclosed in curly braces.
A module template definition is an
<<Writing-Comments-and-Annotations_Annotations,annotatable element>>.

. We have expanded the template `T` twice, once inside
module `M` and once inside module `N`.

When you run the FPP analyzer on this model, it carries out a
process called *template expansion*.
Template expansion causes the syntax elements specified in the
template definition to be replicated at each expansion point.
After template expansion, the model looks like this:

[source,fpp]
--------
module template T {

  constant c = 0

}

module M {

  expand T {

    constant c = 0

  }

}

module N {

  expand T {

    constant c = 0

  }

}
--------

You can see this by running the tool `fpp-to-fpp -t` on the
original model shown above.
We will explain this tool in the section on 
<<Analyzing-and-Translating-Models_Rewriting-FPP-Source,rewriting FPP source>>.

Notice that in the expanded version, each template expansion
contains within it the constant specified in the template
definition.
Also, because we put each expansion in a separate module,
each expanded definition has a separate name.
If we tried to expand the same template twice at the top
level, we would get an error, because the names would clash.
(Try this in `fpp-check`. Note that we have to run `fpp-check`
to see this error, because `fpp-to-fpp` just does syntactic
expansion, not semantic error checking.)

Notice also that each of the expanded templates has the
syntax `expand { ... }` around it.
The purpose of this extra bit of syntax is to
keep track of arguments to template parameters and
scopes of definitions.
We will explain these concepts below.
In this simple example, the expanded templates behave
in the same way as if the syntax `expand { ... }` were not there.

=== Module Template Parameters

In the example given in the previous section, we used template
expansion to produce
two modules `M` and `N` that are structurally identical,
except for their names.
Sometimes this is useful.
More often, though, you will want to expand a template
with one or more elements that you provide at the
point of expansion.
That way, each expansion can be slightly different.
For example, in model from the previous section, 
it may be more useful to specify the values of the
constants `M.c` and `N.c` at the point of expansion,
instead of giving them both the same value zero
specified in the definition.

To carry out this kind of customized expansion, FPP
provides a feature called *module template parameters*.
As with templates in {cpp}, you can specify that a
template has one or more parameters.
The parameters introduce names that you can use
in the template definition, but the values bound
to the names are unknown in the definition; the
values become bound by providing *parameter arguments*
when the template is expanded.

There are three kinds of module template parameters:
constant parameters, type parameters, and interface
instance parameters.
We discuss each kind in turn.

==== Constant Parameters

TODO

==== Type Parameters

TODO

==== Interface Instance Parameters

TODO

=== Resolving Names in Expanded Templates

TODO

=== The expand Syntax

TODO

=== Nesting of Module Templates

TODO
