*The technical data in this document is controlled under the U.S. export 
regulations. Release to foreign persons may require an export authorization.*

== Introduction

This document provides an overview of **F Prime Prime**, also known 
as FPP or F Double Prime.
FPP is a modeling language for the https://github.com/nasa/fprime[F Prime 
flight software framework].
A https://digitalcommons.usu.edu/smallsat/2018/all2018/328/[paper presented at 
SmallSat 2018]
provides an overview of F Prime.

The goals of FPP are as follows:

* To provide a modeling language for F Prime that is simple, easy to use, and
well-tailored to the domain.

* To provide semantic checking and error reporting for F Prime models.

* To generate code in the *target languages* that F Prime uses, e.g.,
C++, Python, XML.

Code generated from FPP models may be combined with handwritten code in
a target language to create, e.g., deployable FSW programs and ground
data environments.

*Purpose:* The purpose of this document is to describe FPP in a way that is accessible
to users.
A more detailed and precise description is available in
https://github.jpl.nasa.gov/pages/bocchino/fpp[_The FPP Language
Specification_].
It is recommended that users read this document before consulting that one.

*Scope:* This document covers the following features of FPP, which are the
currently implemented features in the FPP compiler:

* Constant definitions

* Type and enum definitions

* Specifying, analyzing, and translating models containing these kinds of
definitions

Future versions of this document will cover additional features of FPP.
