*The technical data in this document is controlled under the U.S. export 
regulations. Release to foreign persons may require an export authorization.*

== Introduction

This document describes **F Prime Prime**, also known as FPP or F Double Prime.
FPP is a modeling language for the https://github.com/nasa/fprime[F Prime 
flight software framework].
A https://digitalcommons.usu.edu/smallsat/2018/all2018/328/[paper presented at 
SmallSat 2018]
provides an overview of F Prime.

The goals of FPP are as follows:

* To provide a modeling language for F Prime that is simple, easy to use, and
well-tailored to its purpose.

* To provide semantic checking and error reporting for F Prime models.

* To generate code in the various languages that F Prime uses, e.g.,
{cpp}, Python, XML.
In this document, we will call these languages the *target languages*.

Developers may combine code generated from FPP with code written by hand to
create, e.g., deployable FSW programs and ground data environments.

The name "F Double Prime" (or F'') deliberately suggests the idea of a 
"derivative"
of F Prime (or F').
By "integrating" an FPP model (i.e., running the tools) you get a partial
FSW implementation in the F Prime framework; and then by "integrating" again 
(i.e., providing
the project-specific {cpp} implementation) you get a FSW application.

*Purpose:* The purpose of this document is to describe FPP in a way that is accessible
to users, including beginning users.
A more detailed and precise description is available in
https://fprime-community.github.io/fpp[_The FPP Language
Specification_].
It is recommended that users read this document before consulting that one.

*Scope:* This document covers the following features of FPP, which are the
currently implemented features in the FPP compiler:

* Constant definitions

* Type and enum definitions

* Port definitions

* Specifying, analyzing, and translating models containing these kinds of
definitions

Future versions of this document will cover additional features of FPP.

*XML limitations:*
Currently we translate FPP to F Prime XML and then to {cpp}.
Some features of FPP are not supported in the XML representation.
Where a feature is not supported, we will call out this fact in a
note marked *XML limitation*.
A future version of FPP will generate {cpp} directly and will support
all the features described here.

