== Introduction

This document describes **F Prime Prime**, also known as FPP or F Double Prime.
FPP is a modeling language for the https://github.com/nasa/fprime[F Prime 
flight software framework].
A https://digitalcommons.usu.edu/smallsat/2018/all2018/328/[paper presented at 
SmallSat 2018]
provides an overview of F Prime.

The goals of FPP are as follows:

* To provide a modeling language for F Prime that is simple, easy to use, and
well-tailored to its purpose.

* To provide semantic checking and error reporting for F Prime models.

* To generate code in the various languages that F Prime uses, e.g.,
{cpp}, Python, XML.
In this document, we will call these languages the *target languages*.

Developers may combine code generated from FPP with code written by hand to
create, e.g., deployable FSW programs and ground data environments.

The name "F Double Prime" (or F'') deliberately suggests the idea of a 
"derivative"
of F Prime (or F').
By "integrating" an FPP model (i.e., running the tools) you get a partial
FSW implementation in the F Prime framework; and then by "integrating" again 
(i.e., providing
the project-specific {cpp} implementation) you get a FSW application.

*Purpose:* The purpose of this document is to describe FPP in a way that is accessible
to users, including beginning users.
A more detailed and precise description is available in
https://fprime-community.github.io/fpp[_The FPP Language
Specification_].
It is recommended that users read this document before consulting that one.

*XML limitations:*
Currently we translate FPP to F Prime XML and then to {cpp}.
Some features of FPP are not supported in the XML representation,
or were not supported until very recently.
Where a feature is not supported, we will call out this fact in a
note marked *XML limitation*.
A future release of FPP will generate {cpp} directly and will support
all the features described here.

*Overview:* The rest of this document proceeds as follows.
Section 2 explains how to get up and running with FPP.
Sections 3 through 11 describe the elements of an FPP
model, starting with the simplest elements (constants
and types) and working towards the most complex (components
and topologies).
Section 12 explains how to specify complete models of realistic
size; for example it covers the management of dependencies
between the files that describe a model.
Section 13 explains how to analyze FPP models and how
to translate FPP models to and from F Prime XML
and to {cpp}.
