== Writing C Plus Plus Implementations

When constructing an F Prime deployment in {cpp}, there are generally
four kinds of implementations you have to write:

. Implementations of
<<Defining-Types_Abstract-Type-Definitions,abstract types>>.
These are types that are named in the FPP model but are defined
directly in {cpp}.

. Implementations of 
<<Defining-Components,components>>.

. Implementations of any libraries used by the component implementations,
e.g., algorithm libraries or hardware device driver libraries.

. A top-level implementation including a `main` function for running
the FSW application.

Implementing a component involves filling out the API provided by
the {cpp} component base class.
This process is covered in detail in the F Prime user's guide;
we won't cover it further here.
Similarly, implementing libraries is unrelated to FPP, so we
won't cover it in this manual.
Here we focus on items (1) and (4): implementing abstract types
and implementing deployments.

=== Implementing Abstract Types

Except for a few built-in types (see below), when translating to XML and then {cpp}, an
<<Defining-Types_Abstract-Type-Definitions,abstract type definition>>
represents a {cpp} class that you write directly in {cpp}.
When you use an abstract type _T_ in an FPP definition _D_ (for example, as the 
member type of an array definition)
and you translate _D_ to XML, then the generated XML node for _D_ contains an 
`include_header` node that
includes a header file for _T_.

As an example, try this:

----
% fpp-to-xml -p $PWD
type T
array A = [3] T
^D
----

Notice that we used the option `-p $PWD`.
This is to make the generated include path relative to the current directory.

Now run

----
% cat AArrayAi.xml
----

You should see the following line in the generated XML:

[source,xml]
----
<include_header>T.hpp</include_header>
----

This line says that when the F Prime autocoder translates this XML file
to a {cpp} class, in order to compile that class, a header file `T.hpp`
must exist in the current directory. It is up to you to provide that header
file.

When implementing an abstract type `T` in {cpp}, you must define
a class that extends `Fw::Serializable` from the F Prime framework.
Your class definition must include the following:

* An implementation of the virtual function
+
----
Fw::SerializeStatus T::serialize(Fw::SerializeBufferBase&) const
----
+
that specifies how to *serialize* a class instance (i.e., convert a class 
instance to a byte string).

* An implementation of the function
+
----
Fw::SerializeStatus T::serialize(Fw::SerializeBufferBase&)
----
+
that specifies how to *deserialize* a class instance (i.e., reconstruct a class
instance from a byte string).

* A constant `T::SERIALIZED_SIZE` that specifies the size in bytes
of a byte string serialized from the class.

* A zero-argument constructor `T()`.

* An overloaded equality operator
+
----
bool operator==(const T& that) const;
----

Here is a minimal complete implementation of an abstract type `T`.
It has one member variable `x` of type `U32` and no methods other than
those required by F Prime.
We have made `T` a {cpp} struct (rather than a class) so that
all members are public by default.

----
// A minimal implementation of abstract type T

#ifndef T_HPP
#define T_HPP

// Include Fw/Types/Serializable.fpp from the F Prime framework
#include "Fw/Types/Serializable.hpp"

struct T : public Fw::Serializable { // Extend Fw::Serializable

  // Define some shorthand for F Prime types
  typedef Fw::SerializeStatus SS;
  typedef Fw::SerializeBufferBase B;

  // Define the constant SERIALIZED_SIZE
  enum Constants { SERIALIZED_SIZE = sizeof(U32) };

  // Provide a zero-argument constructor
  T() : x(0) { }

  // Define a comparison operator
  bool operator==(const T& that) const { return this->x == that.x; }

  // Define the virtual serialize method
  SS serialize(B& b) const { return b.serialize(x); }

  // Define the virtual deserialize method
  SS deserialize(B& b) { return b.deserialize(x); }

  // Provide some data
  U32 x;

};

#endif
----

*Built-in types:*
The following types are abstract in the FPP model but are known to
the XML translator:

----
FwBuffSizeType
FwChanIdType
FwEnumStoreType
FwEventIdType
FwOpcodeType
FwPacketDescriptorType
FwPrmIdType
FwTimeBaseStoreType
FwTimeContextStoreType
NATIVE_INT_TYPE
NATIVE_UINT_TYPE
POINTER_CAST
----

Each of these types is an alias for a {cpp} integer type, and each
has default value zero.

The F Prime framework automatically provides the {cpp} definitions
for these types.
You have to declare them as abstract types in the FPP model, but
once you do that you can use them.
You don't have to define header files for these types.

=== Implementing Deployments

TODO

* Main function

* TopologyDefs.hpp and TopologyDefs.cpp

** Health configuration

** User-specified types, constants, and variables
