#!/bin/sh -e

fpp_to_cpp=../../../../../../bin/fpp-to-cpp
fprime_gcc=../../../../../../scripts/fprime-gcc

echo '  removing old files'
./clean

dir=`cd ../..; echo $PWD`

echo '  generating C++'
fpp-to-cpp -p $dir -i ../../builtin.fpp ../../health.fpp

for suffix in hpp cpp
do
  cp ../../HealthTopologyAc.ref.$suffix HealthTopologyAc.$suffix
done

echo '  compiling C++'
$fprime_gcc -I.. -I../../../fprime -I../../../fprime/config -Wno-unused-parameter -c HealthTopologyAc.cpp
