#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_depend=../../../bin/fpp-depend

compare()
{
  outfile=$1
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_depend $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  compare $outfile
}

def_component_instance()
{
  run_test '' def_component_instance
}

include()
{
  run_test -i include
}

locate_constant_1()
{
  run_test '' locate_constant_1
}

locate_constant_consistent()
{
  run_test '' locate_constant_consistent
}

locate_constant_include_i()
{
  run_test -i locate_constant_include_1 locate_constant_include_i
}

locate_constant_include_no_i()
{
  run_test '' locate_constant_include_1 locate_constant_include_no_i
}

locate_constant_inconsistent()
{
  run_test '' locate_constant_inconsistent
}

locate_constant_modules_1()
{
  run_test '' locate_constant_modules_1
}

locate_constant_modules_2()
{
  run_test '' locate_constant_modules_2
}

missing()
{
  run_test '-m tmp.out.txt' missing
  remove_path_prefix < tmp.out.txt > missing_output.out.txt
  compare missing_output
}

spec_comp_instance()
{
  run_test '' spec_comp_instance
}

spec_connection_graph_direct()
{
  run_test '' spec_connection_graph_direct
}

spec_connection_graph_pattern()
{
  run_test '' spec_connection_graph_pattern
}

tests="
def_component_instance
include
locate_constant_1
locate_constant_consistent
locate_constant_include_i
locate_constant_include_no_i
locate_constant_inconsistent
locate_constant_modules_1
locate_constant_modules_2
missing
spec_comp_instance
spec_connection_graph_direct
spec_connection_graph_pattern
"

run_suite $tests
