#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_depend=../../../bin/fpp-depend

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_depend $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

include()
{
  run_test -i include
}

locate_constant_1()
{
  run_test '' locate_constant_1
}

locate_constant_consistent()
{
  run_test '' locate_constant_consistent
}

locate_constant_inconsistent()
{
  run_test '' locate_constant_inconsistent
}

tests="
include
locate_constant_1
locate_constant_consistent
locate_constant_inconsistent
"

run_suite $tests
