#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_depend=../../../bin/fpp-depend

compare()
{
  outfile=$1
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_depend $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  compare $outfile
}

tests="
def_array
def_component_instance
def_constant
def_enum
def_port
def_struct
enum_constant
include
locate_constant_1
locate_constant_consistent
locate_constant_include_i
locate_constant_include_no_i
locate_constant_inconsistent
locate_constant_modules_1
locate_constant_modules_2
missing
spec_command
spec_comp_instance
spec_connection_graph_direct
spec_connection_graph_pattern
spec_event
spec_init
spec_port_instance
spec_top_import
spec_unused_ports
"

# Default tests
for t in $tests
do
  echo "
$t()
{
  run_test '' $t
}"
done > default_tests.sh
. ./default_tests.sh

# Custom tests
include()
{
  run_test -i include
}

locate_constant_include_no_i()
{
  run_test '' locate_constant_include_1 locate_constant_include_no_i
}

locate_constant_include_i()
{
  run_test -i locate_constant_include_1 locate_constant_include_i
}

missing()
{
  run_test '-m tmp.out.txt' missing
  remove_path_prefix < tmp.out.txt > missing_output.out.txt
  compare missing_output
}

run_suite $tests
