#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_depend=../../../bin/fpp-depend

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_depend $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

update '' def_component_instance
update '' locate_constant_1
update '' locate_constant_consistent
update '' locate_constant_include_1 locate_constant_include_no_i
update '' locate_constant_inconsistent
update '' locate_constant_modules_1
update '' locate_constant_modules_2
update '-m tmp.out.txt' missing; remove_path_prefix < tmp.out.txt > missing_output.ref.txt
update -i include
update -i locate_constant_include_1 locate_constant_include_i
update '' spec_comp_instance
