#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_depend=../../../bin/fpp-depend

update()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpp_depend $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.ref.txt
}

for file in `find . -name '*.ref.txt'`
do
  rm $file
done

. ./tests.sh

# Default update ref
for t in $tests
do
  echo "
$t()
{
  update '' $t
}"
done > default-update-ref.sh
. ./default-update-ref.sh

include() {
  update -i include
}

locate_constant_include_i() {
  update -i locate_constant_include_1 locate_constant_include_i
}

locate_constant_include_no_i()
{
  update '' locate_constant_include_1 locate_constant_include_no_i
}

missing() {
  update '-m tmp.out.txt' missing; remove_path_prefix < tmp.out.txt > missing_output.ref.txt
}

for t in $tests
do
  echo "updating ref output for $t"
  $t
done
