==== Type Definitions

A *type definition* defines a new type and gives it a name. The new type
is associated with an existing type, called the *representation type*.
Elsewhere in the program, you can use the defined type.

===== Syntax

`type`
<<Detailed-Description_Identifiers,_identifier_>>
`=`
<<Detailed-Description_Types,_type_>>

===== Semantics

The identifier on the left-hand side is the name of the defined type.
The type on the right-hand side of the definition is the representation
type. We say that the named type *represents* its representation type.

At any program point where the
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>> _Q_ refers to a 
definition `type` _I_ `=` _T_ according to the
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,scoping
rules for names>>, you can use _Q_.

If the representation type is a
<<Detailed-Description_Types_Structure-Types,structure type>>,
then the representation type may not have a structure or array type for
any of its members. Named types that represent structure or array types are
allowed as the member types.

If the representation type is an
<<Detailed-Description_Types_Array-Types,array type>>, then the representation 
type may not have a structure or array type for
its element type. A named type that represents a structure or
array type is allowed as the element type.

===== Examples

[source,tnet]
----
include::./Detailed-Description/Definitions/src/Type_Definitions/Examples_1.tnt[tag=visible]
----

[source,tnet]
----
include::./Detailed-Description/Definitions/src/Type_Definitions/Examples_2.tnt[tag=visible]
----

In the second example, the type `GoldilocksStatus` is defined with type
a definition. `PorridgeStatus` is an
<<Detailed-Description_Types_Enum-Types,enum type>> defined with an
<<Detailed-Description_Definitions_Enum-Definitions,enum definition>>.

This example is not allowed, because the representation type is a
structure type with an unnamed structure type in one of its members:

[source,tnet]
----
include::./Detailed-Description/Definitions/src/Type_Definitions/Examples_3.tnt[tag=visible]
----

This example is allowed:

[source,tnet]
----
include::./Detailed-Description/Definitions/src/Type_Definitions/Examples_4.tnt[tag=visible]
----
