=== Connection Graph Specifiers

A *connection graph specifier* specifies one or more *connection graphs*
as part of a
<<Definitions_Topology-Definitions,topology definition>>.
A connection graph is a named set of *connections*.
A connection connects an <<Specifiers_Port-Instance-Specifiers,output port 
instance>> of one
<<Specifiers_Component-Instance-Specifiers,component instance>>
to an
<<Specifiers_Port-Instance-Specifiers,input port instance>> of
another.

==== Syntax

A connection graph specifier is one of the following:

* A *direct graph specifier:*
`connections` 
<<Lexical-Elements_Identifiers,_identifier_>>
`{` _connection-sequence_ `}`

* A *graph pattern specifier:*
`connections` 
`instance` <<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
_[_
`{` _instance-sequence_ `}`
_]_
`pattern` <<Expressions,_expression_>>

_connection-sequence_ is an
<<Element-Sequences,element sequence>> in 
which each element is a *connection*,
and the terminating punctuation is a comma.
A connection is the following:

<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>> `.`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`[`
<<Expressions,_expression_>>
`]`
_]_
`pass:[->]`
<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>> `.`
<<Lexical-Elements_Identifiers,_identifier_>>
_[_
`[`
<<Expressions,_expression_>>
`]`
_]_

_instance-sequence_ is an
<<Element-Sequences,element sequence>> in 
which each element is a
<<Scoping-of-Names_Qualified-Identifiers,qualified identifier>>,
and the terminating punctuation is a comma.

==== Semantics

*Direct graph specifiers.*
A direct graph specifier directly specifies a named connection graph.

. The identifier following the keyword `connections` names
the connection graph.

. The connection sequence specifies the set of connections in the graph.
For each connection _C_:

.. For each qualified identifier _Q_ in _C_:

... _Q_ must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a component instance _I_ that is available in the enclosing topology,
either through
<<Specifiers_Component-Instance-Specifiers,direct specification>>
or through
<<Specifiers_Topology-Import-Specifiers,import>>.

... _I_ must refer to a <<Definitions_Component-Instance-Definitions,component 
instance definition _I'_>>.

... _I'_ must refer to a <<Definitions_Component-Definitions,component 
definition _C'_>>. 

... The identifier following _Q_
must refer to a
<<Specifiers_Port-Instance-Specifiers,port instance specifier _P_>>
of _C'_.

... The optional expression _e_ following the identifier, if it is present, 
represents a
port array index.
The type of _e_ must be a
<<Types_Internal-Types_Numeric-Types,numeric type>>, and
_e_ must
<<Evaluation,evaluate>> to a compile-time constant
that becomes a non-negative integer _n_ when 
<<Evaluation_Type-Conversion,converted to>> type _Integer_.
_n_ must be within bounds for
the array size specified in _P_.

.. The arrow represents the direction of the connection (left to right).

.. The connection must go from an
<<Specifiers_Port-Instance-Specifiers,output port instance>>
to an
<<Specifiers_Port-Instance-Specifiers,input port instance>>.

.. The types specified in the two port instances must match,
except that a `serial` port at either end can be connected
to any port at the other end.

*Graph pattern specifiers.*
A graph pattern specifier indirectly specifies one or more named connection 
graphs
by specifying a source component, a set of target components,
and a pattern for connecting the source component to each of the
target components.

. The expression following the keyword `pattern` must have
a <<Types_Internal-Types_Numeric-Types,numeric type>>.
It provides an integer identifier for a connection pattern.

. The qualified identifier following the keyword `instance` must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a component instance that is available in the enclosing topology,
either through
<<Specifiers_Component-Instance-Specifiers,direct specification>>
or through
<<Specifiers_Topology-Import-Specifiers,import>>.

. If the instance sequence _I_ appears, then each qualified identifier
_Q_ appearing in _I_ must refer to a component instance that is available
in the enclosing topology, and each instance must be valid for the pattern
(i.e., must have a port of the type required for the pattern).
The instances in the sequence name the target instances for the
pattern. If no instance sequence appears, then the target instances are
all instances specified directly in the enclosing topology (not via import)
that are valid for the pattern.

The meaning of the pattern identifiers depends on the translation context.
Typical patterns include the following:

. `COMMANDS`: The source instance _I_ is a command dispatcher.
The following connection graphs are generated:

.. A connection graph named `Command` consisting of all connections
from the output port of type `Fw::Cmd` of _I_ to the input port of type 
`Fw::Cmd` of each target component.

.. A connection graph named `CommandRegistration` consisting of all
connections from the output port of type `Fw::CmdReg` of each target component
to the input port of type `Fw::Cmd` of _I_.

.. A connection graph named `CommandResponse` consisting of all connections 
from the output port of type `Fw::CmdResp` of each target component
to the input port of type `Fw::CmdResp` of _I_.

. `EVENTS`: The source instance _I_ is an active logger.
The generated connection graph has name `Events` and contains
all connections for sending events to _I_.

. `HEALTH`: The source instance _I_ is a health component.
The generated connection graph has name `Health` and contains
all connections between the health component and the ping
ports of the target components.

. `TIME`: The source instance _I_ is a time component.
The generated connection graph has name `Time` and contains
all connections for getting the time from _I_.

==== Example

Assume the following instances are available in the enclosing topology,
and all have command ports:

[source,fpp]
----
commandDispatcher
commandSequencer
engineeringTelemetryLogger
eventLogger
telemetryDatabase
timeSource
----

Here is a graph pattern specifier:

[source,fpp]
----
connections pattern COMMAND instance commandDispatcher
----

It is equivalent to the following direct graph specifiers:

[source,fpp]
----
connections CommandRegistration {
  commandDispatcher.cmdRegOut -> commandDispatcher.cmdRegIn
  commandSequencer.cmdRegOut -> commandDispatcher.cmdRegIn
  engineeringTelemetryLogger.cmdRegOut -> commandDispatcher.cmdRegIn
  eventLogger.cmdRegOut -> commandDispatcher.cmdRegIn
  telemetryDatabase.cmdRegOut -> commandDispatcher.cmdRegIn
  timeSource.cmdRegOut -> commandDispatcher.cmdRegIn
}

connections Command {
  commandDispatcher.cmdOut -> commandDispatcher.cmdIn
  commandDispatcher.cmdOut -> commandSequencer.cmdIn
  commandDispatcher.cmdOut -> engineeringTelemetryLogger.cmdIn
  commandDispatcher.cmdOut -> eventLogger.cmdIn
  commandDispatcher.cmdOut -> telemetryDatabase.cmdIn
  commandDispatcher.cmdOut -> timeSource.cmdIn
}

connections CommandResponse {
  commandDispatcher.cmdRespOut -> commandDispatcher.cmdRespIn
  commandSequencer.cmdRespOut -> commandDispatcher.cmdRespIn
  engineeringTelemetryLogger.cmdRespOut -> commandDispatcher.cmdRespIn
  eventLogger.cmdRespOut -> commandDispatcher.cmdRespIn
  telemetryDatabase.cmdRespOut -> commandDispatcher.cmdRespIn
  timeSource.cmdRespOut -> commandDispatcher.cmdRespIn
}
----

See also the <<Definitions_Topology-Definitions_Examples,examples for topology 
definitions>>.
