=== Init Specifiers

An *init specifier* associates some initialization
code with a 
<<Definitions_Component-Instance-Definitions,
component instance>>.

==== Syntax

`init` <<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
`phase` <<Expressions,_expression_>>
<<Expressions_String-Literals,_string-literal_>>

==== Semantics

* The qualified identifier must 
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a
<<Definitions_Component-Instance-Definitions,
component instance definition _D_>>.

* The expression following the keyword `phase` must have
a <<Types_Internal-Types_Numeric-Types,numeric type>>.
It provides an integer identifier for an initialization phase.

* The code string specifies some code in a target language
that is associated with the instance.

The meaning of the initialization phase and the code depends
on the translation context.

==== Example

[source,fpp]
----
@ Phases of initialization
enum Phases {
  @ When components are constructed
  CONSTRUCTION
  @ After components are constructed, and before connections are established
  BEFORE_CONNECTIONS
  @ After connections are established
  AFTER_CONNECTIONS
}

init commandDispatcher phase BEFORE_CONNECTIONS \
"""
commandDispatcher.init(QueueDepth::commandDispatcher);
"""
----

In this example, the code generator provides three phases,
`CONSTRUCTION`, `BEFORE_CONNECTIONS`, and `AFTER_CONNECTIONS`.
In the `CONSTRUCTION` phase, the code generator generates
a default constructor invocation that looks like this:

[source,fpp]
----
Svc::CommandDispatcher commandDispatcher("commandDispatcher");
----

By default, the code generator would generate this code
to run before connections are established:

[source,c++]
----
commandDispatcher.init(
    QueueDepth::commandDispatcher,
    InstanceID::commandDispatcher
);
----

The code shown above overrides the code generated for the second
phase to remove the instance ID from the arguments of the `init` method.
