=== Port Export Specifiers

A port export specifier maps a <<Port-Instance-Specifiers,port instance>>
out to a port instance for the parent <<Definitions_Topology-Definitions,topology definition>>.

==== Syntax

`port`
<<Component-Instance-Member-Identifiers_Port-Instance-Identifiers,_port-instance-id_>>
_[_ `[` <<Expressions,_expression_>> `]` _]_

_[_
`as`
<<Lexical-Elements_Identifiers,_identifier_>>
_]_

==== Semantics

. The port instance identifier references a <<Port-Instance-Specifiers,port instance>>
inside a component instance named in the enclosing topology _T_.

.. The optional expression _e_ following the port instance identifier, if it is present,
represents a port number, i.e., an index into an
array of port instances.
The type of _e_ must be a
<<Types_Internal-Types_Numeric-Types,numeric type>>, and
_e_ must
<<Evaluation,evaluate>> to a compile-time constant
that becomes a non-negative integer _n_ when
<<Evaluation_Type-Conversion,converted to>> type _Integer_.
_n_ must lie in the range [0,2^31^) and must be in bounds for the
array size of the port instance specifier named in _I_.

. The optional identifier _I2_, if provided, will rename the port being exported.
If not provided, the name of the port being exported will match the name of the port instance identifier.

. The port referenced must be either a
<<Specifiers_Port-Instance-Specifiers,output port instance>>
or an
<<Specifiers_Port-Instance-Specifiers,input port instance>>.

.. Exporting an input or output port will expose a port instance of the same
type to the enclosing topology _T_. Any connections made on this exposed port will
internally be mapped to the port instance identifier _I_.

==== Example

[source,fpp]
----
topology T {
    instance c1
    instance c2

    connections {
        # [...] Internal connections
    }

    export c1.portOut
    export c2.portIn as customPortName
}

topology Y {
    import T

    instance c3
    connections {
        T.portOut -> c3.portIn
        c3.portOut -> T.customPortName
    }
}
----

See also the <<Definitions_Topology-Definitions_Examples,examples for topology
definitions>>.
