=== Port Export Specifiers

A port export specifier names a <<Specifiers_Port-Instance-Specifiers,port instance>>
of an internal port in a <<Definitions_Topology-Definitions,topology definition>>.

==== Syntax

`export`
<<Component-Instance-Member-Identifiers_Port-Instance-Identifiers,_port-instance-id_>>
_[_
`as`
<<Lexical-Elements_Identifiers,_identifier_>>
_]_

==== Semantics

. The port instance identifier references a <<Specifiers_Port-Instance-Specifiers,port instance>>
endpoint named in the enclosing topology _T_.

. The optional identifier _I2_, if provided, will rename the port being exported.
If not provided, the name of the port being exported will match the name of the port instance identifier.

. The port referenced must be either a
<<Specifiers_Port-Instance-Specifiers,output port instance>>
or an
<<Specifiers_Port-Instance-Specifiers,input port instance>>.

.. Exporting an input or output port will expose a port instance of the same
type to the enclosing topology _T_. Any connections made on this exposed port will
internally be mapped to the port instance identifier _I_.

. An exported port allows another topology that <<Specifiers_Topology-Import-Specifiers, imports>> this topology
to connect directly to this named port.

.. Providing a set of exported ports encapulates port instance names and component instance names from
the interface of the parent topology.

==== Example

[source,fpp]
----
topology T {
    instance c1
    instance c2

    connections {
        # [...] Internal connections
    }

    export c1.portOut
    export c2.portIn as customPortName
}

topology Y {
    import T

    instance c3
    connections {
        T.portOut -> c3.portIn
        c3.portOut -> T.customPortName
    }
}
----

See also the <<Definitions_Topology-Definitions_Examples,examples for topology
definitions>>.
