=== Record Specifiers

A *record specifier* specifies a data product record as part of a
<<Definitions_Component-Definitions,component definition>>.
A record is a unit of data that is stored in a
<<Specifiers_Container-Specifiers,container>>.

==== Syntax

`product` `record` <<Lexical-Elements_Identifiers,_identifier_>>
`:` _record-type_
_[_
`id` <<Expressions,_expression_>>
_]_

_record-type_ is one of the following:

. <<Type-Names,_type-name_>>

. `raw`

==== Semantics

. The identifier names the record.

. _record-type_ name specifies the type of the data stored in the record.

.. If the type is a type name _T_, then the record stores one
element of type _T_.

.. If the type is `raw`, then the record is a raw or uninterpreted
record.
A raw record consists of a size _s_ and a data payload
consisting of _s_ bytes.

. The optional expression _e_ after the keyword `id` specifies the
numeric identifier for the record.
If _e_ is present, then the type of _e_ must be
<<Type-Checking_Type-Conversion,convertible to>>
<<Types_Internal-Types_Integer,_Integer_>>, and _e_ must evaluate
to a nonnegative integer.
If _e_ is not present, then the
default identifier is either zero (for the first record appearing in a
component) or the previous record identifier plus one.

==== Examples

[source,fpp]
----
@ An array of 3 F64 values
array F64x3 = [3] F64

@ Record 0
@ Implied id is 0x00
product record Record0: U32

@ Record 1
product record Record1: U32 id 0x02

@ Record 2
@ Implied id is 0x03
product record Record2: F64x3
----
