=== Telemetry Packet Group Specifiers

A *telemetry packet group specifier* groups the telemetry channels of a
topology into <<Specifiers_Telemetry-Packet-Specifiers,telemetry packets>>.
A telemetry packet group specifier is part of a
<<Definitions_Topology-Definitions, topology definition>>.

==== Syntax

`telemetry` `packets`
<<Lexical-Elements_Identifiers,_identifier_>>
`{` _telemetry-packet-specifier-sequence_ `}`
_[_
`omit`
`{` _telemetry-channel-specifier-sequence_ `}`
_]_

_telemetry-packet-specifier-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is a <<Specifiers_Telemetry-Packet-Specifiers,telemetry
packet specifier>>,
and the terminating punctuation is a comma.

_telemetry-channel-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is a
<<Component-Instance-Member-Identifiers_Telemetry-Channel-Identifiers,
telemetry channel identifier>>,
and the terminating punctuation is a comma.

==== Semantics

. Each telemetry packet specifier in _telemetry-packet-specifier-sequence_ must
be <<Specifiers_Telemetry-Packet-Specifiers,valid>>,

. Each telemetry packet specifier in _telemetry-packet-specifier-sequence_ must
must have a distinct name and a distinct identifier.

. For every component instance _I_ available in the enclosing topology, either through
<<Specifiers_Component-Instance-Specifiers,direct specification>>
or through
<<Specifiers_Topology-Import-Specifiers,import>>,
for every telemetry channel _T_ that is a member of _I_,
exactly one of the following must be true:

.. _T_ appears in at least one of the packets of
_telemetry-packet-specifier-sequence_.

.. _telemetry-channel-sequence_ is present, and _T_ appears in
_telemetry-channel-sequence_.

==== Example

[source,fpp]
----
packets Packets {

  packet CDH id 0 level 0 {
    commandDispatcher.commandsDispatched
    rateGroup1Hz.rgMaxTime
    fileUplink.filesReceived
  }

  packet ADCS id 1 level 2 {
    adcs.mode
    adcs.attitude
  }

} omit {
  adcs.extraTelemetry
}
----
