=== Template Instantiation Specifiers

A *template instantiation specifier* takes a
<<Definitions_Module-Template-Definitions,template>> and
applies a set of values to its <<Template-Parameter-Lists,parameters>>
to generate a new concrete definition.

=== Syntax

_definition-type_
<<Lexical-Elements_Identifiers,_identifier_>>
`=`
<<Scoping-of-Names_Qualified-Identifiers,_qual-ident>>
`(` _parameter-sequence_ `)`

_definition-type_ is one of following keywords:

. `component`
. `interface`
. `topology`

_parameter-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is an
<<Values,value expression>> or qualified identifier,
and the terminating punctuation is a semicolon.

=== Semantics

. The identifier names the new *definition*.

. The qualified identifier must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a
<<Definitions_Module-Template-Definitions,module template definition _T_>>.

. The parameter sequence is the set of parameters that map to
the template parameters of the template _T_.

==== Checking parameter types

When passing values and references to template instantiation, each parameter
is checked with the following rules:

. If the parameter type is `constant`, the type of the value will be
<<Type-Checking_Type-Conversion,converted to>> the type specified in the parameter list.

. If the parameter type is `interface` _I_, the value must be a
<<Scoping-of-Names_Qualified-Identifiers,_qualified-identifier_>> of a
<<Port-Interfaces_Port-Interface-Instance,port interface instance>>
that can <<Port-Interfaces_Binding,bind>> to _I_.

. If the parameter type is `type`, the value must name a type.

=== Examples

[source,fpp]
----
@ Command and data handling topology
topology CDH {
  # ----------------------------------------------------------------------
  # Private instances
  # ----------------------------------------------------------------------
}

template (...) topology C implements ... {
    topology T1 = C1(0) // TODO(DO not add)
}


topology T2 = C(1, )

template topology T(...) implements  {
    topology T1 = C1(0)
    instance I: FPPComponent
}
----
