=== Template Expansion Specifiers

A *template expansion specifier* takes a
<<Definitions_Module-Template-Definitions,template>> and
applies a set of values to its parameters
to generate concrete definitions.

=== Syntax

`expand`
<<Scoping-of-Names_Qualified-Identifiers,_qual-ident>>
`(` _parameter-sequence_ `)`

_parameter-sequence_ is an
<<Element-Sequences,element sequence>> in
which each element is an
<<Values,value expression>> or qualified identifier,
and the terminating punctuation is a semicolon.

=== Semantics

. The qualified identifier must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a
<<Definitions_Module-Template-Definitions,module template definition _T_>>.

. The parameter sequence is the set of parameters that map to
the template parameters of the template _T_.

==== Checking parameter types

When passing values and references to template expansion, each parameter
is checked with the following rules:

. If the parameter type is `constant`, the type of the value will be
<<Type-Checking_Type-Conversion,converted to>> the type specified in the parameter list.

. If the parameter type is `interface` _I_, the value must be a
<<Scoping-of-Names_Qualified-Identifiers,_qualified-identifier_>> of a
<<Ports_Port-Interface-Instances,port interface instance>>
which is a <<Ports_Sub-Interfaces,sub-interface>> to _I_.

. If the parameter type is `type`, the value must name a type.

==== Template Expansion

When a template is expanded, the uses of parameters are replaced with the values
given in the parameter list. The syntax inside _T_ is cloned
and placed into the scope of the template expansion. Uses are resolved relative to
the _T_'s scope rather than the template expansion's.

=== Examples

[source,fpp]
----
port P

@ A basic template parameterizing an interface port count
template Templ(
  constant numPorts: U32
) {
  interface I {
    output port N[numPorts]: P
  }

  passive component C {
    import I
  }
}

@ Instantiate the template giving the parameters concrete values
module M {
  expand Templ(30)
}
# M.I => interface { output port N[30]: P }
# M.C => passive component { output port N[30]: P }
----
