=== Template Expansion Specifiers

A *template expansion specifier* names a 
<<Definitions_Module-Template-Definitions,template>>
and specifies arguments for the parameters of the template.
During <<Expansion-of-Templates,template expansion>>, it generates the definitions specified 
by the template and the arguments.

==== Syntax

`expand`
<<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>
_[_
`(` _template-arg-list_ `)`
_]_

_template-arg-list_ is an
<<Element-Sequences,element sequence>> in
which the elements are template arguments, and
the terminating punctuation is a comma.

Each template argument is one of the following:

. A *constant template argument* `constant` <<Expressions,_expression_>>

. A *port interface instance template argument*
`instance` <<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>

. A *type template argument* `type` <<Type-Names,_type-name_>>

==== Semantics

. The qualified identifier must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
the definition of a
<<Definitions_Module-Template-Definitions,module template _T_>>.

. The number of template arguments must match the number of template
parameters in _T_.
If there are no parameters, then the argument list may be omitted.

. For each template parameter _P_, let _A_ be the corresponding argument.

.. If _P_ is a constant template parameter, then _A_ must be a constant
template argument. The type of the expression in _A_ must be 
<<Type-Checking_Type-Conversion,convertible to>> the type specified in _P_.

.. If _P_ is an interface instance template parameter, then _A_
must be an interface instance template argument.
The qualified identifier in _A_ must
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a <<Ports_Port-Interface-Instances,port interface instance>> _N_.
The port interface of referred to in _P_ must be a
<<Ports_Sub-Interfaces,sub-interface>> of the <<Ports_Port-Interfaces,port 
interface of _N_>>.

.. If _P_ is a type template parameter, then _A_ must be a type
template argument.

=== Examples

[source,fpp]
----
port P

@ A basic template parameterizing an interface port count
template T(constant numPorts: U32) {

  interface I {
    output port p: [numPorts] P
  }

  passive component C {
    import I
  }

}

@ Instantiate the template giving the parameters concrete values
module M {

  expand T(constant 30)
  # Definition interface I { output port p: [30] P }
  # Definition passive component C { output port p: [30] P }

}

----
