=== Topology Import Specifiers

A *topology import specifier* imports one topology into another one.

==== Syntax

`import` <<Scoping-of-Names_Qualified-Identifiers,_qual-ident_>>

==== Semantics

The qualified identifier must 
<<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a
<<Definitions_Topology-Definitions,topology definition>>.

*Importing instances:*
FPP uses the following algorithm to import the instances
of topology _T'_ into topology _T_:

. Let _I_ be the set of 
<<Specifiers_Component-Instance-Specifiers,instances>>
of _T_.

. Let _I'_ be the set of 
<<Specifiers_Component-Instance-Specifiers,public instances>>
of _T'_.

. Let _I''_ be the set union of _I_ and _I'_.
That means that if either or both of _I_ and _I'_ contain the instance _S_,
then _I''_ contains the instance _S_ once.
Each instance in _I''_ has private visibility if it is private
in either _I_ or _I'_, otherwise public visibility.

*Importing connections:*
FPP uses the following algorithm to import the connections
of topology _T'_ into topology _T_.

. For each
<<Specifiers_Connection-Graph-Specifiers,connection graph name>> stem:[N_i]
that appears in either _T_ or _T'_:

.. Let stem:[G_i] be the connection graph named stem:[N_i] in _T_.
If no such graph exists, then let stem:[G_i] be the empty connection graph
with name stem:[N_i].

.. Let stem:[G'_i] be the connection graph named stem:[N_i] in _T'_.
If no such graph exists, then let stem:[G'_i] be the empty connection graph
with name stem:[N_i].

.. Let stem:[C_i] be the set of 
<<Specifiers_Connection-Graph-Specifiers,connections>>
of stem:[G_i] such that each of the two instances at
the ends of the connection is in _I''_.

.. Let stem:[C'_i] be the set of
<<Specifiers_Connection-Graph-Specifiers,connections>>
of stem:[G'_i] such that each of the two the instances at
the ends of the connection is in _I''_, and the connection
is defined by a direct or pattern specifier in _T'_ 
(i.e., not imported into _T'_ from another topology).

.. Let stem:[C''_i] be the disjoint union of stem:[C_i] and stem:[C'_i].
That means that if stem:[C_i] contains _n_ connections between port
_p_ and port _p'_, and stem:[C'_i] contains _m_ connections between
port _p_ and port _p'_, then stem:[C_i] contains _n + m_ connections
between port _p_ and port _p'_.

.. Let stem:[G''_i] be the connection graph with name stem:[N_i]
and connections stem:[C''_i].

. Return the connection graphs stem:[G''_i].

==== Example

[source,fpp]
----
topology A {

  instance a
  private instance b
  instance c

  connections C1 {
    a.p1 -> c.p
  }

  connections C2 {
    b.p -> c.p
  }

}

topology B {

  import A

  instance d
  instance e
  instance f

  connections C1 {
    a.p1 -> d.p
  }

  connections C2 {
    a.p2 -> e.p
  }

  connections C3 {
    a.p3 -> f.p
  }

}
----

After importing, topology `B` is equivalent to this topology:

[source,fpp]
----
topology B {

  instance a
  instance c
  instance d
  instance e
  instance f 

  connections C1 {
    a.p1 -> c.p
    a.p2 -> d.p
  }

  connections C2 {
    a.p2 -> e.p
  }

  connections C3 {
    a.p3 -> f.p
  }

}
----

Note the following:

* The connections from topologies `A` and `B` are merged graph by graph.

* Because instance b is private to topology `A`, neither it nor any
of its connections appear in topology `B`.

