=== Topology Port Specifiers

A topology port specifiers names a <<Specifiers_Port-Instance-Specifiers,
port instance>> of an internal port in a <<Definitions_Topology-Definitions,
topology definition>>. This allows topology connections to be made directly
on a topology rather than referencing the instances named inside. It also
allows topologies to <<Port-Interfaces_Binding,bind to interfaces>>.

==== Syntax

`port`
<<Lexical-Elements_Identifiers,_identifier_>>
`=`
<<Instance-Member-Identifiers_Port-Instance-Identifiers,_port-instance-id_>>

==== Semantics

For each topology port specifier defined in an enclosing topology _T_:

. The port instance identifier references a <<Specifiers_Port-Instance-Specifiers,port instance>>
endpoint in _T_.

. The port referenced must be either a
<<Specifiers_Port-Instance-Specifiers,output port instance>>
or an
<<Specifiers_Port-Instance-Specifiers,input port instance>>.

.. Exporting an input or output port will expose a port instance of the same
type to the enclosing topology _T_. Any connections made on this exposed port will
internally be mapped to the port instance identifier _I_.

. An exported port allows another topology that <<Specifiers_Topology-Import-Specifiers, imports>> this topology
to connect directly to this named port.

.. Providing a set of exported ports encapulates port instance names and component instance names from
the interface of the parent topology.

==== Example

[source,fpp]
----
topology T {
    instance c1
    instance c2

    connections {
        # [...] Internal connections
    }

    port portOut = c1.portOut
    port customPortName = c2.portIn
}

topology Y {
    import T

    instance c3
    connections {
        T.portOut -> c3.portIn
        c3.portOut -> T.customPortName
    }
}
----

See also the <<Definitions_Topology-Definitions_Examples,examples for topology
definitions>>.
