=== Lexical Elements

Before parsing a tnet program, the compiler converts the source
text into a list of 
<<Detailed-Description_Lexical-Elements_Tokens,tokens>>.
This process is called lexing.

==== Tokens

A token is one of the following:

* A <<Detailed-Description_Lexical-Elements_Reserved-Words,reserved word>>.

* A <<Detailed-Description_Lexical-Elements_Symbols,symbol>>.

* An <<Detailed-Description_Identifiers,identifier>>.

* An <<Detailed-Description_Expressions_Integer-Literals,integer literal>>.

* A <<Detailed-Description_Expressions_Floating-Point-Literals,floating-point literal>>.

* A <<Detailed-Description_Expressions_Boolean-Literals,Boolean literal>>.

* A <<Detailed-Description_Expressions_String-Literals,string literal>>.

* A line of an <<Detailed-Description_Comments-and-Annotations_Annotations,annotation>>
beginning with `@` or `@<`.

==== Comments

<<Detailed-Description_Comments-and-Annotations_Comments,Comments>>
are ignored during lexing.

==== Whitespace

The lexer treats whitespace as follows:

* Space characters are ignored, except to separate tokens.

* The newline character is a token. It is used to separate the
elements of <<Detailed-Description_Element-Sequences,element sequences>>.

* No other whitespace characters are allowed. In particular, the
tab character may not appear (outside of a comment, annotation, or string 
literal) in a tnet program.

==== Line Continuations

The character `\`, when appearing before a newline, causes the newline to
be ignored. For example, this
```
constant a = 1 + \
  1
```
is equivalent to this:
```
constant a = 1 + 1
```

Note that the `\` character is required in this case.
For example, the following is not syntactically correct:
```
constant a = 1 + # Error
  1
```
The newline indicates the end of an expression, but
`1 +` is not a valid expression.

The lexer ignores any space characters appearing between `\` and the next 
newline.

==== Reserved Words

The following are reserved words in tnet.
They may not be used as identifiers.

----
F32
F64
I16
I32
I64
I8
U16
U32
U64
U8
and
boolean
cleanup
command
constant
contingency
duration
end
enum
false
from
impact
in
maint
module
opcode
planning
post
pre
range
rate
set
start
state
string
task
tasknet
template
timeline
true
type
with
----

==== Symbols

The following sequences of characters are symbol tokens in tnet:

----
*
+
+-
+=
,
-
.
..
/
:
;
=
[
]
{
}
----
