#!/bin/sh -e

fpp_to_cpp=../../../../../../bin/fpp-to-cpp
fprime_gcc=../../../../../../scripts/fprime-gcc

echo '  removing old files'
./clean

dir=`cd ../..; echo $PWD`
fprime_dir=../../../fprime

echo '  generating C++'
fpp-to-cpp -p $dir -i $fprime_dir/config/FpConfig.fpp,$fprime_dir/Fw/Prm/Prm.fpp,../../phases.fpp \
  $fprime_dir/Fw/Cmd/Cmd.fpp ../../params.fpp
for suffix in hpp cpp
do
  cp ../../ParamsTopologyAc.ref.$suffix ParamsTopologyAc.$suffix
done

echo '  compiling C++'
$fprime_gcc -I.. -I../../../fprime -I../../../fprime/config -Wno-unused-parameter -c ParamsTopologyAc.cpp
