#!/bin/sh -e

export FPRIME_GCC_FLAGS="-I../../../fprime -Wno-unused-parameter -Wno-unused-variable"
fpp_to_cpp=../../../../../../bin/fpp-to-cpp

echo '  removing old files'
./clean

dir=`cd ../..; echo $PWD`
fprime_dir=../../../fprime

echo '  generating C++'
fpp-to-cpp -p $dir -i $fprime_dir/config/FpConfig.fpp,$fprime_dir/Fw/Prm/Prm.fpp,../../phases.fpp \
  $fprime_dir/Fw/Cmd/Cmd.fpp ../../params.fpp
for suffix in hpp cpp
do
  cp ../../ParamsTopologyAc.ref.$suffix ParamsTopologyAc.$suffix
done

echo '  compiling C++'
fprime-gcc -I .. -c ParamsTopologyAc.cpp
