// ======================================================================
// \title  AliasTypeArrayAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for AliasType array
// ======================================================================

#ifndef AliasTypeArrayAc_HPP
#define AliasTypeArrayAc_HPP

#include <initializer_list>

#include "ATAliasAc.hpp"
#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

//! An array of abstract type
class AliasType :
  public Fw::Serializable
{

  public:

    // ----------------------------------------------------------------------
    // Types
    // ----------------------------------------------------------------------

    //! The element type
    using ElementType = AT;

  public:

    // ----------------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------------

    enum {
      //! The size of the array
      SIZE = 3,
      //! The serialized size of each element
      ELEMENT_SERIALIZED_SIZE = sizeof(AT),
      //! The size of the serial representation
      SERIALIZED_SIZE = SIZE * ELEMENT_SERIALIZED_SIZE
    };

  public:

    // ----------------------------------------------------------------------
    // Constructors
    // ----------------------------------------------------------------------

    //! Constructor (default value)
    AliasType();

    //! Constructor (primitive array)
    AliasType(
        const ElementType (&a)[SIZE] //!< The array
    );

    //! Constructor (single element)
    AliasType(
        const ElementType& e //!< The element
    );

    //! Constructor (initializer list)
    AliasType(
        const std::initializer_list<ElementType>& il //!< The initializer list
    );

    //! Constructor (multiple elements)
    AliasType(
        const ElementType& e1, //!< Element 1
        const ElementType& e2, //!< Element 2
        const ElementType& e3 //!< Element 3
    );

    //! Copy constructor
    AliasType(
        const AliasType& obj //!< The source object
    );

  public:

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    //! Subscript operator
    ElementType& operator[](
        const FwSizeType i //!< The subscript index
    );

    //! Const subscript operator
    const ElementType& operator[](
        const FwSizeType i //!< The subscript index
    ) const;

    //! Copy assignment operator (object)
    AliasType& operator=(
        const AliasType& obj //!< The source object
    );

    //! Copy assignment operator (primitive array)
    AliasType& operator=(
        const ElementType (&a)[SIZE] //!< The source array
    );

    //! Copy assignment operator (initializer list)
    AliasType& operator=(
        const std::initializer_list<ElementType>& il //!< The initializer list
    );

    //! Copy assignment operator (single element)
    AliasType& operator=(
        const ElementType& e //!< The element
    );

    //! Equality operator
    bool operator==(
        const AliasType& obj //!< The other object
    ) const;

    //! Inequality operator
    bool operator!=(
        const AliasType& obj //!< The other object
    ) const;

#ifdef BUILD_UT

    //! Ostream operator
    friend std::ostream& operator<<(
        std::ostream& os, //!< The ostream
        const AliasType& obj //!< The object
    );

#endif

  public:

    // ----------------------------------------------------------------------
    // Public member functions
    // ----------------------------------------------------------------------

    //! Serialization
    Fw::SerializeStatus serializeTo(
        Fw::SerializeBufferBase& buffer //!< The serial buffer
    ) const;

    //! Deserialization
    Fw::SerializeStatus deserializeFrom(
        Fw::SerializeBufferBase& buffer //!< The serial buffer
    );

    //! Get the dynamic serialized size of the array
    FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

    //! Convert array to string
    void toString(
        Fw::StringBase& sb //!< The StringBase object to hold the result
    ) const;

#endif

  private:

    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! The array elements
    ElementType elements[SIZE];

};

#endif
