// ======================================================================
// \title  ATF32AliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for ATF32 alias
// ======================================================================

#ifndef ATF32AliasAc_HPP
#define ATF32AliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"

extern "C" {
#include "ATF32AliasAc.h"
}

#endif
