#!/bin/sh -e

. ../../../../scripts/utils.sh

clean
rm -f default-tests.sh default-update-ref.sh
for file in `find . -not \( -path ./include -prune \)\
    \( -name '*out.*' -o -name '*.names.txt' -o -name '*o' -o -name '*Ac.cpp' -o -name '*Ac.hpp' \)`
do
  rm $file
done
