// ======================================================================
// \title  BuiltInTypePortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for BuiltInType port
// ======================================================================

#include <cstdio>
#include <cstring>

#include "BuiltInTypePortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/StringUtils.hpp"

// ----------------------------------------------------------------------
// Input Port Member functions
// ----------------------------------------------------------------------

InputBuiltInTypePort ::
  InputBuiltInTypePort() :
    Fw::InputPortBase(),
    m_func(nullptr)
{

}

void InputBuiltInTypePort ::
  init()
{
  Fw::InputPortBase::init();
}

void InputBuiltInTypePort ::
  addCallComp(
      Fw::PassiveComponentBase* callComp,
      CompFuncPtr funcPtr
  )
{
  FW_ASSERT(callComp);
  FW_ASSERT(funcPtr);

  this->m_comp = callComp;
  this->m_func = funcPtr;
  this->m_connObj = callComp;
}

void InputBuiltInTypePort ::
  invoke(
      FwOpcodeType t,
      FwOpcodeType& tRef
  )
{
#if FW_PORT_TRACING == 1
  this->trace();
#endif

  FW_ASSERT(this->m_comp);
  FW_ASSERT(this->m_func);

  return this->m_func(this->m_comp, this->m_portNum, t, tRef);
}

// ----------------------------------------------------------------------
// Output Port Member functions
// ----------------------------------------------------------------------

OutputBuiltInTypePort ::
  OutputBuiltInTypePort() :
    Fw::OutputPortBase(),
    m_port(nullptr)
{

}

void OutputBuiltInTypePort ::
  init()
{
  Fw::OutputPortBase::init();
}

void OutputBuiltInTypePort ::
  addCallPort(InputBuiltInTypePort* callPort)
{
  FW_ASSERT(callPort);

  this->m_port = callPort;
  this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
  this->m_serPort = nullptr;
#endif
}

void OutputBuiltInTypePort ::
  invoke(
      FwOpcodeType t,
      FwOpcodeType& tRef
  )
{
#if FW_PORT_TRACING == 1
  this->trace();
#endif

#if FW_PORT_SERIALIZATION
  FW_ASSERT(this->m_port || this->m_serPort);
#else
  FW_ASSERT(this->m_port);
#endif

  return this->m_port->invoke(t, tRef);
}
