#!/bin/sh

cd `dirname $0`

fprime_gcc=../../../../scripts/fprime-gcc

../fprime/generate_cpp

echo "running tests to generate the headers"
./run

for file in `find . -name '*.ref.cpp'`
do
  base=`basename $file .ref.cpp`
  cp $base.ref.hpp $base.hpp
  cp $base.ref.cpp $base.cpp
  echo "compiling $base.cpp"
  $fprime_gcc -DFW_PORT_TRACING=1 -DFW_PORT_SERIALIZATION=1 -I../fprime/config -c $base.cpp
done
