#!/bin/sh

# ----------------------------------------------------------------------
# Compile ref files, to check them for C++ validity
# ----------------------------------------------------------------------

fprime_gcc=../../../scripts/fprime-gcc

for file in `find . -name 'FppConstants_*.ref.cpp'`
do
  echo "compiling $file"
  base=`echo $file | sed 's;\.cpp;;'`
  dest_base=`echo $base | sed 's;\(.*FppConstants\).*;\1;'`
  cp $base.hpp $dest_base.hpp
  cp $base.cpp $dest_base.cpp
  $fprime_gcc -c $dest_base.cpp
done
