// ======================================================================
// \title  Choice_StateEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Choice_State enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "Choice_StateEnumAc.hpp"

namespace FppTest {

  namespace SmInitial {

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    Choice_State& Choice_State ::
      operator=(const Choice_State& obj)
    {
      this->e = obj.e;
      return *this;
    }

    Choice_State& Choice_State ::
      operator=(T e1)
    {
      this->e = e1;
      return *this;
    }

#ifdef BUILD_UT

    std::ostream& operator<<(std::ostream& os, const Choice_State& obj) {
      Fw::String s;
      obj.toString(s);
      os << s;
      return os;
    }

#endif

    // ----------------------------------------------------------------------
    // Member functions
    // ----------------------------------------------------------------------

    bool Choice_State ::
      isValid() const
    {
      return ((e >= __FPRIME_UNINITIALIZED) && (e <= T));
    }

    Fw::SerializeStatus Choice_State ::
      serializeTo(
          Fw::SerialBufferBase& buffer,
          Fw::Endianness mode
      ) const
    {
      const Fw::SerializeStatus status = buffer.serializeFrom(
          static_cast<SerialType>(this->e),
          mode
      );
      return status;
    }

    Fw::SerializeStatus Choice_State ::
      deserializeFrom(
          Fw::SerialBufferBase& buffer,
          Fw::Endianness mode
      )
    {
      SerialType es;
      Fw::SerializeStatus status = buffer.deserializeTo(es, mode);
      if (status == Fw::FW_SERIALIZE_OK) {
        this->e = static_cast<T>(es);
        if (!this->isValid()) {
          status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
        }
      }
      return status;
    }

#if FW_SERIALIZABLE_TO_STRING

    void Choice_State ::
      toString(Fw::StringBase& sb) const
    {
      Fw::String s;
      switch (e) {
        case __FPRIME_UNINITIALIZED:
          s = "__FPRIME_UNINITIALIZED";
          break;
        case S:
          s = "S";
          break;
        case T:
          s = "T";
          break;
        default:
          s = "[invalid]";
          break;
      }
      sb.format("%s (%" PRIu8 ")", s.toChar(), e);
    }

#elif FW_ENABLE_TEXT_LOGGING

    void Choice_State ::
      toString(Fw::StringBase& sb) const
    {
      sb.format("%" PRIu8 "", e);
    }

#endif

  }

}
