// ======================================================================
// \title  SequenceU32_StateEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for SequenceU32_State enum
// ======================================================================

#include <cstring>
#include <limits>

#include "SequenceU32_StateEnumAc.hpp"

namespace FppTest {

  namespace SmChoice {

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    SequenceU32_State& SequenceU32_State ::
      operator=(const SequenceU32_State& obj)
    {
      this->e = obj.e;
#ifdef BUILD_UT
      this->m_serializeNumericValue = obj.m_serializeNumericValue;
      this->m_numericValue = obj.m_numericValue;
#endif
      return *this;
    }

    SequenceU32_State& SequenceU32_State ::
      operator=(enum T e1)
    {
      FW_ASSERT(isValid(e1), static_cast<FwAssertArgType>(e1));
      this->e = e1;
#ifdef BUILD_UT
      this->m_serializeNumericValue = false;
      this->m_numericValue = __FPRIME_UNINITIALIZED;
#endif
      return *this;
    }

#ifdef BUILD_UT

    std::ostream& operator<<(std::ostream& os, const SequenceU32_State& obj) {
      Fw::String s;
      obj.toString(s);
      os << s;
      return os;
    }

#endif

    // ----------------------------------------------------------------------
    // Member functions
    // ----------------------------------------------------------------------

    bool SequenceU32_State ::
      isValid() const
    {
      return isValid(this->e);
    }

    Fw::SerializeStatus SequenceU32_State ::
      serializeTo(
          Fw::SerialBufferBase& buffer,
          Fw::Endianness mode
      ) const
    {
      SerialType es = static_cast<SerialType>(this->e);
#ifdef BUILD_UT
      // Unit testing only: On request, override the enum value
      // with the numeric value, which is allowed to be invalid
      if (this->m_serializeNumericValue) {
        es = this->m_numericValue;
      }
#endif
      const Fw::SerializeStatus status = buffer.serializeFrom(es, mode);
      return status;
    }

    Fw::SerializeStatus SequenceU32_State ::
      deserializeFrom(
          Fw::SerialBufferBase& buffer,
          Fw::Endianness mode
      )
    {
      SerialType es;
      Fw::SerializeStatus status = buffer.deserializeTo(es, mode);
      if ((status == Fw::FW_SERIALIZE_OK) && !isValid(es)) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
      if (status == Fw::FW_SERIALIZE_OK) {
        this->e = static_cast<enum T>(es);
      }
      return status;
    }

#if FW_SERIALIZABLE_TO_STRING

    void SequenceU32_State ::
      toString(Fw::StringBase& sb) const
    {
      Fw::String s;
      switch (e) {
        case __FPRIME_UNINITIALIZED:
          s = "__FPRIME_UNINITIALIZED";
          break;
        case S1:
          s = "S1";
          break;
        case S2:
          s = "S2";
          break;
        case S3:
          s = "S3";
          break;
        case S4:
          s = "S4";
          break;
        default:
          s = "[invalid]";
          break;
      }
      sb.format("%s (%" PRIu8 ")", s.toChar(), e);
    }

#endif

#ifdef BUILD_UT

    void SequenceU32_State ::
      setSerializeValue(SerialType serializeValue)
    {
      this->m_numericValue = serializeValue;
      this->m_serializeNumericValue = true;
    }

#endif

    // ----------------------------------------------------------------------
    // Static functions
    // ----------------------------------------------------------------------

    bool SequenceU32_State ::
      isValid(SerialType serialTypeValue)
    {
      return ((serialTypeValue >= __FPRIME_UNINITIALIZED) && (serialTypeValue <= S4));
    }

  }

}
