#!/bin/sh

for folder in *.refs; do
    cd $folder
    rm -rf *.diff.txt *.out.txt *.ast.out.txt *.loc-map.out.txt *.analysis.out.txt *ast.diff.txt *.loc-map.diff.txt *.analysis.diff.txt
    cd ..
done
