#!/bin/sh -e

. ../../../scripts/test-utils.sh

fpp_to_json=../../../bin/fpp-to-json


run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi


  {
    # Run fpp_to_json and concatenate the output files
    $fpp_to_json $infile.fpp $args 2>&1 | remove_path_prefix > $outfile.out.txt && \
    remove_path_prefix < fpp-ast.json >> $outfile.out.txt && \
    remove_path_prefix < fpp-loc-map.json >> $outfile.out.txt
  } && \
  {
    # Validate the location map
    if which python3 > /dev/null 2>&1
    then
      python3 python/locationMapValidator.py fpp-ast.json fpp-loc-map.json
    else
      # Work around an issue in CI
      echo "python3 is not available; skipping map validation" 1>&2
    fi
  } && \
  {
    # Clean up
    if [ "$args" = "-s" ]; then
      rm fpp-ast.json fpp-loc-map.json
    else
      remove_path_prefix < fpp-analysis.json >> $outfile.out.txt
      # Delete the JSON files
      rm fpp-ast.json fpp-loc-map.json fpp-analysis.json
    fi
  } && \
  {
    # Compare the output
    diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
  }
}


# Run fpp-to-json on fpp-check test case
# Success criteria: "Exception in thread" (case insensitive) does not exist in the stdout/stderr of fpp-to-json
run_fpp_check_test() {
  f=$1
  outfile="${f##*/}"
  outfile="${outfile%.*}"
  outfile=$dir_name"_"$outfile
  status=0
  if $fpp_to_json $f 2>&1 | grep -qi "Exception in thread"; then
    status=1
  fi
  rm -f fpp-ast.json fpp-loc-map.json fpp-analysis.json
  return $status
}

activeComponents(){
  run_test "" activeComponents
}

commands(){
  run_test "" commands
}

constTypesComponents(){
  run_test "" constTypesComponents
}

constants()
{
  run_test "" constants
}

dataProducts(){
  run_test "" dataProducts
}

enums()
{
  run_test "" enums
}

events(){
  run_test "" events
}

importedTopologies(){
  run_test "" importedTopologies
}

internalPorts()
{
  run_test "" internalPorts
}

matchedPorts(){
  run_test "" matchedPorts
}

modules()
{
  run_test "" modules
}

parameters(){
  run_test "" parameters
}

passiveComponent(){
  run_test "" passiveComponent
}

patternedConnections(){
  run_test "fprime/defs.fpp" patternedConnections
}

ports()
{
  run_test "" ports
}

queuedComponents(){
  run_test "" queuedComponents
}

simpleComponents()
{
  run_test "" simpleComponents
}

simpleTopology(){
  run_test "" simpleTopology
}

specialPorts()
{
  run_test "" specialPorts
}

stateMachine()
{
  run_test "" ../../fpp-syntax/test/state-machine stateMachine
}

syntaxOnly(){
  run_test "-s" syntaxOnly 
}

telemetry(){
  run_test "" telemetry
}

telemetryPackets(){
  run_test "" telemetryPackets
}

types()
{
  run_test "" types
}

fpp_to_json_tests="
activeComponents
commands
constTypesComponents
constants
dataProducts
enums
events
importedTopologies
internalPorts
matchedPorts
modules
parameters
passiveComponent
patternedConnections
ports
queuedComponents
simpleComponents
simpleTopology
specialPorts
stateMachine
syntaxOnly
telemetry
telemetryPackets
types
"

# Generate fpp-check test cases by doing the following:
# Get all .fpp test cases in the fpp-check/test/* directories
# For each test case:
#   1.) Create a function with the following name: fpp_check_<directory name>_<file name>
#   2.) In the function, call the run_fpp_check_test (defined in this file) and provide the filename of the FPP model to run
# After iterating all test cases:
#   1.) Write all functions to a new file called fpp-check-tests.sh
#   2.) Return string containing all test names so they can be executed below
test_names=""
fpp_check_test_dir="../../fpp-check/test/"
fpp_check_tests=$(for d in "$fpp_check_test_dir"*
do
if [[ -d $d ]]; then
  dir_name="${d##*/}"
  for f in "$d"/*
  do
  if [[ -f $f ]]; then
    if [ "${f##*.}" == "fpp" ]; then  
    file_name="${f##*/}"
    file_name="${file_name%.*}"
    func_name="fpp_check"_$dir_name"_"$file_name

    test_names+="\n$func_name"
echo "
$func_name()
{
  run_fpp_check_test $f
}"
    fi
  fi
  done
fi
done > fpp-check-tests.sh && \
echo $test_names)

. ./fpp-check-tests.sh

run_suite $fpp_to_json_tests$fpp_check_tests
