#!/bin/sh

. ../../../scripts/test-utils.sh

fpp_to_json=../../../bin/fpp-to-json

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi

  # Run fpp_to_json and concatenate the output files
  $fpp_to_json $args $infile.fpp 2>&1 | remove_path_prefix > $outfile.out.txt
  cat fpp-ast.json fpp-loc-map.json fpp-analysis.json >> $outfile.out.txt

  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1

  # Delete the JSON files
  rm fpp-ast.json fpp-loc-map.json fpp-analysis.json
}

constants()
{
  run_test "" constants
}


tests="
constants
"

run_suite $tests
